### ISSUE TITLE
Can we have lottie integrated with nativescript (lottie-nativescript)

### ISSUE THREAD

**Issue by mohammedzamakhan** [airbnb/lottie-react-native#10]
@NathanWalker

**Comment by lelandrichardson** [comment]
@mohammedzamakhan I'm not very familiar with exposing native views/libraries to NativeScript, but it sounds very possible. You may want to reach out specifically on the `lottie-ios` and `lottie-android` repos, but I'm happy to help in any way that I can.

**Comment by lelandrichardson** [comment]
Looks like someone beat you to it? :)

https://github.com/bradmartin/nativescript-lottie
