### ISSUE TITLE
1.1.0?

### ISSUE THREAD

**Issue by aaronsky** [airbnb/lottie-react-native#101]
I can observe the v1.1.0 commit in the log, but there is no new release for the recent changes. Was this intentional, and if so, does a contributor have any idea as to the timeline for a new release?

(cc: @lelandrichardson)

**Comment by lelandrichardson** [comment]
@aaronsky 1.1.0 was released with the `@next` tag to prevent people from using it until it's stable. There are still a couple of kinks to work out. Will hopefully be able to publish as `@latest` tonight or tomorrow. Sorry for the wait!
