### ISSUE TITLE
[6.0.0-rc.4] Need to specify dimensions on Lottie component to display it

### ISSUE THREAD

**Issue by TomCorvus** [airbnb/lottie-react-native#1015]
### Description

Hi 👋
Since 6.0.0-rc.4 version, I need to specify dimensions on Lottie or LottieView component to get animation visible.

### Steps to Reproduce

1. create new react-native app
2. install and configure Lottie-react-native 6.0.0-rc.4
3. Create a View with styles and dimensions and put Lottie inside.

```
<View style={{ backgroundColor: "#F1F1F1", height: 100, width: 100 }}>
        <Lottie
          source={require("./142605-firework-animation.json")}
          autoPlay
          loop
        />
</View>
```

With this piece of code, the animation doesn't display on 6-rc4 but does on 6-rc3.
You need to set `height: 100, width: 100` on Lottie component to display it on 6-rc4.

**Expected behavior:** Keep the same behavior of previous version. Is it the good one btw?

**Actual behavior:** Need to set dimensions on Lottie component to have the animation visible.

**Comment by idrissakhi** [comment]
Same issue on rc5

**Comment by matinzd** [comment]
You can read about this breaking change here:

https://github.com/lottie-react-native/lottie-react-native/pull/992

**Comment by matinzd** [comment]
I will try to come up with a solution as we are iterating on this. Thanks for your feedback! 
If I see that is causing a lot of confusion in community I can revert back the aspect ratio at least in order to have default values.

**Comment by TomCorvus** [comment]
Thanks @matinzd!
Or you can add a prop to have the aspect ratio. I don't know if a lot of people add width and height on Lottie component or let the component manage himself like image for example.
In my project 80% of my animations have dimensions but not this one. Just a width: 100% to get the good ratio on each screens size and keep the text below and above near by.
