### ISSUE TITLE
Build failed on iOS w/ v1.1.1

### ISSUE THREAD

**Issue by DavoCg** [airbnb/lottie-react-native#103]
Hello,

I have a build fail error using:

lottie-react-native v1.1.1
react-native v0.42.3

I did 
``` react-native link lottie-ios```
```react-native link lottie-react-native ```

And i get this error when I try to build

```/node_modules/lottie-react-native/lib/ios/LottieReactNative/LRNContainerView.h:19:9: 'Lottie/Lottie.h' file not found```

Anybody encountered the same issue ?

Thank for your work and this really nice project

**Comment by carly-lee** [comment]
I had the same issue. In my case, 'Parallelize Build' was checked on Scheme. 
After I unchecked it, I was able to build the app with no errors.

![screen shot 2017-03-30 at 5 18 46 pm](https://cloud.githubusercontent.com/assets/6396721/24494401/1022f72e-156d-11e7-8946-5fc695d72b0c.png)

**Comment by fdnhkj** [comment]
I have this error as well when using `release` build configuration (no issue with the `debug` one).

**Comment by Kowaio** [comment]
Hello all,
I wanted to let you know that unchecking `Parallelize Build` on my Scheme solved my build issue referenced on #59 and #91. I don't know if that's the best fix but will do for now.

Thanks!

**Comment by tech-know** [comment]
Hey guys @carly-lee's solution work for me.

**Comment by sibelius** [comment]
can we close this?

**Comment by Kowaio** [comment]
Yep I guess. Thanks!
