### ISSUE TITLE
onAnimationComplete() method? 

### ISSUE THREAD

**Issue by mmckinley8** [airbnb/lottie-react-native#104]
Wondering if there are any handler methods for animations completing. Am I missing something?

**Comment by browniefed** [comment]
If you're using `Animated` when you call `Animated.timing().start(() => {//Animation is complete here})

**Comment by mmckinley8** [comment]
I tried using `Animated.timing().start(() => {}` but kept getting errors so I opted to use the imperative API. I will move back to using Animated though.

**Comment by mmckinley8** [comment]
That worked, thanks @browniefed
