### ISSUE TITLE
iOS ignores initial progress value

### ISSUE THREAD

**Issue by iggyfisk** [airbnb/lottie-react-native#107]
It seems like the `<Animation>` component always assumes the `progress` property is 0 on mount, but only on iOS. Simple to reproduce: clone the latest 1.1.1 version. Change [line 34](https://github.com/airbnb/lottie-react-native/blob/master/example/LottieAnimatedExample.js#L34) of `example/LottieAnimatedExample.js` to `progress: new Animated.Value(0.5),` which should initialize the animation in "the middle". On Android this works as expected, the Hamburger -> Arrow -> Hamburger animation shows the Arrow "in the middle":

![screenshot_2017-03-30-14-38-24](https://cloud.githubusercontent.com/assets/6059552/24504677/766638f4-1557-11e7-96a6-96e889264078.png)

But iOS doesn't care that the `progress` property is 0.5, it just shows the Hamburger as if `progress` were 0 (even though the indicator below properly shows 0.5):
![screen shot 2017-03-30 at 14 37 16](https://cloud.githubusercontent.com/assets/6059552/24504722/9d0e03a6-1557-11e7-8c32-3e3e47a7686b.png)

If we use the example picker above the animation to `setState` with a new animation source, these are properly initialized with `progress` 0.5 on iOS as well. So if we just switch to Line Animation then back to Hamburger, we see the arrow as expected.

**Comment by gpeal** [comment]
@iggyfisk I just tried this on master and it seems to be working as expected. I'm going to push a new release today. If it's still an issue, feel free to reopen.
