### ISSUE TITLE
Could you have a tag for 1.1.1 at least

### ISSUE THREAD

**Issue by dryganets** [airbnb/lottie-react-native#108]
Since 1.0.6 you stopped tagging your releases.
While 1.0.6 is not compatible with most of the current android versions as it doesn't override opt methods of the JSONObject in JSONReadableMap class.

**Comment by aaronsky** [comment]
The rationale I was given in #101 was that these were pre-releases, but tags to reflect that would be nice

**Comment by gpeal** [comment]
We will start tagging new releases. Sorry for any inconvenience!
