### ISSUE TITLE
use lottie in screen splash 

### ISSUE THREAD

**Issue by frixid** [airbnb/lottie-react-native#109]
is possible to use lottie like a screen splash on ios/android?

**Comment by n8stowell82** [comment]
I doubt this can ever be supported. You can only display static content in a splash screen. The app is not technically running yet and so no code is being executed.

**Comment by jdnichollsc** [comment]
You can create a static splash screen with a background and later load the same image from a component to animate a logo or something like that! 👍

**Comment by UsamaIslam** [comment]
Yes, it is possible.
You can create an activity using lottie and in manifest file make it launcher activity, then set a timer 3-5 second and after that call your main activity. 
It will act as splash screen with animation (android). 
I hope same can be achieved on iOS.

**Comment by nlabofa** [comment]
anyone implemented this on IOS and Android?

**Comment by camharless** [comment]
> Yes, it is possible.
> You can create an activity using lottie and in manifest file make it launcher activity, then set a timer 3-5 second and after that call your main activity.
> It will act as splash screen with animation (android).
> I hope same can be achieved on iOS.

I am so new to this. Do you know of a tutorial or walkthrough that I could look at for this? I'm trying to put an animation I made in After Effects/Bodymovin that I would love to open my app with, even if I have to start with a static background color splash screen first.

**Comment by namereva** [comment]
> anyone implemented this on IOS and Android?

I did this. So use https://github.com/crazycodeboy/react-native-splash-screen with Lottie.
Follow the instructions and change your launch_screen.xml in the end
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:orientation="vertical" android:layout_width="match_parent"
                android:layout_height="match_parent">
  <com.airbnb.lottie.LottieAnimationView
          android:id="@+id/launch"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          app:lottie_autoPlay="true"
          app:lottie_loop="true"
          app:lottie_rawRes="@raw/launch" />
</RelativeLayout>
`
This works on android (didn't test on ios)

**Comment by shrynshjain** [comment]
@camharless I want to do the same too. Did you figure it out?

**Comment by HwangTaehyun** [comment]
Hi, If you looking for lottie launch screen in react native, i would suggest looking into this package.

> https://www.npmjs.com/package/react-native-lottie-splash-screen

It implements animation splash screen using airbnb lottie files. Also, I apply this for multiple react native projects and it worked well. Have a nice day!
