### ISSUE TITLE
List of supported After Effects features

### ISSUE THREAD

**Issue by ricardogo** [airbnb/lottie-react-native#110]
Hello,

After some testing with Lottie, we're embarking on using it in production for a new project.
We're wondering if there's a list of supported After Effects features and effects so we can design around that. We already hit a couple of walls we'll have to design around, but making sure there are no hidden things we haven't anticipated.
I think this will be super useful for the community.

Thanks!

**Comment by fdnhkj** [comment]
You can have a look at this issue: https://github.com/airbnb/lottie-react-native/issues/88

**Comment by ricardogo** [comment]
Hi @fdnhkj, thank you!
