### ISSUE TITLE
Animation not showing up on device iOS

### ISSUE THREAD

**Issue by kyleleite** [airbnb/lottie-react-native#114]
I cant get the animation to show up on my device, I'm not getting any errors but just a blank screen. When opening the inspector on my device (iphone 6) I can see that there are 2 animations but nothing is displaying.

Don't know what i'm doing wrong!

attaching my code and screenshots from device. Any help would be great!

![screenshot_3](https://cloud.githubusercontent.com/assets/17218896/24882042/b60ce142-1e0d-11e7-85ea-4774e6bd1a06.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/17218896/24882231/59e7eeec-1e0e-11e7-938b-e639347be7cd.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/17218896/24882236/5c67ff54-1e0e-11e7-96a2-315610cd913e.png)

**Comment by johnnycopperstone** [comment]
Experiencing the same issue, have you made any progress with this?

**Comment by johnnycopperstone** [comment]
This worked for me actually https://github.com/airbnb/lottie-react-native/issues/82#issuecomment-290963691

**Comment by gpeal** [comment]
Closing this because it's probably not relevant with the latest version. Feel free to reopen if it is.

**Comment by kaushal9678** [comment]
I was facing same issue, I did following things and it worked fine on both iOS and Android
1. First I install pod file in iOS folder by using **pod init**
2. Then install npm i --save lottie-react-native 
3. After installing lottie-react-native run link command
            *  react-native link lottie-ios
            *react-native link lottie-react-native
4. Go to Xcode and in libraries folder add lottie-ios and lottie-react-native xcode project  like attached screenshot from node_modules
5. Then add Lottie.framework from Lottie products to Embedded Binaries
6. add libLottieReactNative.a and libLottie.a to Linked frameworks and libraries. That .a file you can find in Libraries product folder. **See enclosed screenshot** 2

1. <img width="271" alt="screenshot 2019-01-06 at 11 32 46 am" src="https://user-images.githubusercontent.com/4991337/50733032-71553480-11ab-11e9-9f52-b75013d7078b.png">
2. 
<img width="271" alt="screenshot 2019-01-06 at 11 32 46 am" src="https://user-images.githubusercontent.com/4991337/50733047-f3ddf400-11ab-11e9-80e3-6aae49b2731c.png">
3. <img width="660" alt="screenshot 2019-01-06 at 12 05 32 pm" src="https://user-images.githubusercontent.com/4991337/50733050-f93b3e80-11ab-11e9-903d-95a2b379784a.png">
