### ISSUE TITLE
provided dependencies can only be jar 

### ISSUE THREAD

**Issue by vokhuyet** [airbnb/lottie-react-native#115]
i had this issue when try build in android
please reply me with any solutions.
Thank you very much.
<img width="687" alt="screen shot 2017-04-11 at 19 39 03" src="https://cloud.githubusercontent.com/assets/16424696/24909558/9e3eb45a-1eee-11e7-9c0c-65816e836c56.png">

**Comment by programmer-1** [comment]
use latest gradle and gradle plugin version and change your library version in build.gradl to + instead specific version.

**Comment by vokhuyet** [comment]
thank you very much. i can fix this by change provided into complied
