### ISSUE TITLE
Animation not shown when using Expo 50 with lottie-react-native 6.5.1

### ISSUE THREAD

**Issue by eliasljubec** [airbnb/lottie-react-native#1168]
### Description

I've recently upgraded to Expo 50 with lottie-react-native version 6.5.1 but haven't had any success yet. The issue is that the animation is simply not showing - can’t really tell why since the implementation is fairly simple and no warnings/errors are shown.
When I revert back to lottie-react-native version 5.1.6, everything works as expected.

### Steps to Reproduce

```
"react-native": "0.73.2",
"expo": "^50.0.0"
"lottie-react-native": "6.5.1",
```

```
<LottieView
    autoPlay={true}
    style={{ width: '100%', height: '100%' }}
    loop={true}
    speed={2.2}
    source={require('../assets/lottie/animation.json')}
/>
```

**Expected behavior:** Should show animation as expected 

**Actual behavior:** Does not show the animation

### React Native Environment

Using iPhone SE 3rd gen simulator.
Using dev client & the hermes engine.

**Comment by TheRogue76** [comment]
Hi @eljubec. Can we have the lottie file in question so we can check things out?

**Comment by TheRogue76** [comment]
> Sure! Following animation is in use:
> 
> [animation.json](https://github.com/lottie-react-native/lottie-react-native/files/14075602/animation.json)
> 
> 

Alrighty. We will take a look and see what we find

**Comment by matinzd** [comment]
Hi @eljubec,

I created a [repo](https://github.com/matinzd/lottie-react-native-expo) with the latest Expo SDK and configured it with a dev client. 

Here is the screenshot of the result:

<img width="1728" alt="Screenshot 2024-01-28 at 14 07 01" src="https://github.com/lottie-react-native/lottie-react-native/assets/24797481/2a2a45bc-cdc3-4cb1-b7c3-361c9eddab25">

**Comment by JoelNgiamKeeYong** [comment]
Same issue as well with lottie-react-native v6.5.1 with Expo SDK 50. But when reverted to v5.1.6, some animations do not fully animate and will be slow.

**Comment by TheRogue76** [comment]
> Same issue as well with lottie-react-native v6.5.1 with Expo SDK 50. But when reverted to v5.1.6, some animations do not fully animate and will be slow.

@JoelNgiamKeeYong Please provide a reproducible. @eljubec Any updates on your side?

**Comment by matinzd** [comment]
Any updates?

**Comment by Rolls98** [comment]
I had the same problem, but for it to work you have to define the size in pixels instead of in percentage.

**Comment by matinzd** [comment]
@Rolls98 

Relative values shouldn't be a problem as you can see in the example repo I created. Can you please give us a reproducible where relative width and height is not working?

https://github.com/matinzd/lottie-react-native-expo

**Comment by Rolls98** [comment]
@matinzd 

What I had as a problem was that I had to define a height without the width,
and on version 5.1.4 I have no problem, but with version 6.5.1 the animation only works when I specify the height and width.

**Comment by TheRogue76** [comment]
> @matinzd 
> 
> 
> 
> What I had as a problem was that I had to define a height without the width,
> 
> and on version 5.1.4 I have no problem, but with version 6.5.1 the animation only works when I specify the height and width.
> 
> 
> 
> exemple code work on 5.1.4 but not on 6.5.1
> 
> 
> 
> ` 
> 
> const CartAnimation = () => {
> 
>   return (
> 
>     <LottieView
> 
>       style={{ height: hp('6%')}}
> 
>       source={require('./cart.json')}
> 
>       autoPlay
> 
>       loop={false}
> 
>     />
> 
>   );
> 
> };
> 
> `
> 
> 
> 
> when i specify width on 6.5.1 it's work
> 
> 
> 
> `const CartAnimation = () => {
> 
>   return (
> 
>     <LottieView
> 
>       style={{ height: hp('6%'), width: hp('6%') }}
> 
>       source={require('./cart.json')}
> 
>       autoPlay
> 
>       loop={false}
> 
>     />
> 
>   );
> 
> };
> 
> `
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

https://github.com/lottie-react-native/lottie-react-native/blob/master/MIGRATION-5-TO-6.md

**Comment by TheRogue76** [comment]
@eljubec Any updates?

**Comment by rytilahti-juuso** [comment]
> @eljubec Any updates?

The problem was fixed for me at least when the width and height are defined in the Lottie animation, just like in the Migration link (from v5 to v6) you provided. 

Did not work (old code, notice the style definition missing from Lottie!)

```
< CustomContainerView style={{width: 100, height: 100}}>
    <Lottie source={{...etc}}/>
< CustomContainerView >
```

Started working after defining the styles directly to Lottie:

```
< CustomContainerView style={{width: 100, height: 100}}>
    <Lottie source={{...etc}} style={{width: 100, height: 100}} />
< CustomContainerView >
```

What caused this issue was probably that the Expo did not clearly state that the Lottie animations would break with the Expo SDK update (or I and others missed it :D).

**Comment by TheRogue76** [comment]
> What caused this issue was probably that the Expo did not clearly state that the Lottie animations would break with the Expo SDK update (or I and others missed it :D).

Glad it's working for you. I am unaware of Expo's explicit recommendation regarding setting up dependencies, but I always got the impression that it recommends that you install the dependencies yourself, even if it is included with the Expo SDK out of the box (https://docs.expo.dev/versions/latest/sdk/lottie/). Otherwise maintaining and handling breaking changes between so many different third-party SDKs would become unreasonable on their side. I could be wrong though.

**Comment by WidevisionDesign** [comment]
If you don't want to set specific width/height values, you can also use:
`<LottieView
          style={{ flex: 1, pointerEvents: 'none' }}
          resizeMode="cover"
          source={getLottie()}
          loop
          autoPlay
        />`

Flex: 1 seems to be working fine with `lottie-react-native` version `6.5.1`

**Comment by steson322** [comment]
> If you don't want to set specific width/height values, you can also use: `<LottieView style={{ flex: 1, pointerEvents: 'none' }} resizeMode="cover" source={getLottie()} loop autoPlay />`
> 
> Flex: 1 seems to be working fine with `lottie-react-native` version `6.5.1`

Had same issue after upgrade to SDK50

This worked for me with no updates needed.
Wild that the layout behavior is incompatible cross SDK versions

**Comment by bidery** [comment]
I have the same problems. I created a package where i want to store all of my lottie animations etc. however the animation isn't shown when the screen is visible.

OS:
- Android

Packages:
- react: 18.2.0
- react-native: 0.73.6
- lottie-react-native: 6.7.0

My Code:
```jsx
import SpinnerLottie from './assets/spinner.json';

export const Spinner = memo(
  forwardRef<LottieView, SpinnerProps>(function Spinner(
    {color = Colors.RED, height = 100, width = 100, style},
    ref,
  ) {
    return (
      <LottieView
        ref={ref}
        style={[
          {
            width,
            height,
          },
          style,
        ]}
        testID="lottie:spinner"
        colorFilters={[
          {
            keypath: 'Shape Layer 1',
            color,
          },
        ]}
        source={SpinnerLottie}
        autoPlay={true}
        loop={true}
      />
    );
  }),
);

 ```
 
 Can someone help?

**Comment by bibhuti9** [comment]
I found a solution. Please remove the height and width point values.

Before

"h": 121.07,
 "w": 153.26,
After

"h": 121,
"w": 153,

**Comment by mosestenai** [comment]
I experienced the same issue on my end but i solved it by adding width on the lottie style,, previously i had only defined the height

**Comment by brayohmurithidev** [comment]
https://github.com/user-attachments/assets/2bf0f33f-cf86-41da-8796-08b2f8ccc2ed

am having a funny behavior here on iOS, I don't know where the black object on the left is coming from. The android works just fine.
