### ISSUE TITLE
Crashing on Android: TypeError: expected dynamic type `int64', but had type `double'

### ISSUE THREAD

**Issue by lukaleli** [airbnb/lottie-react-native#118]
I'm successfully running lottie on iOS but have problems with it on Android. App crashes just on the start when I try to show an animation. Stacktrace from the logcat:

```
AndroidRuntime  
E  FATAL EXCEPTION: AsyncTask #1
E  Process: <MY APP PACKAGE NAME>, PID: 15990
E  java.lang.RuntimeException: An error occured while executing doInBackground()
E      at android.os.AsyncTask$3.done(AsyncTask.java:304)
E      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E      at java.lang.Thread.run(Thread.java:818)
E  Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `int64', but had type `double'
E      at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
E      at com.airbnb.android.react.lottie.JSONReadableMap.optInt(JSONReadableMap.java:178)
E      at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:188)
E      at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:17)
E      at com.airbnb.lottie.JsonCompositionLoader.doInBackground(JsonCompositionLoader.java:7)
E      at android.os.AsyncTask$2.call(AsyncTask.java:292)
E      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E      ... 3 more
```

Package.json
```
"react-native": "0.41.2",
"lottie-react-native": "^1.1.1",
```

Gradle configuration:
```
android {
    compileSdkVersion 25
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "..."
        minSdkVersion 16
        targetSdkVersion 22
```

**Comment by NicolasBonduel** [comment]
I had the same issue but managed to fix it by manually changing the "fr" value to an int inside the JSON file.
I changed `"fr":29.9700012207031` to `"fr":29` in my case.

**Comment by lukaleli** [comment]
@NicolasBonduel actually this hack worked out. thanks a lot for a suggestion!
but animation is still not showing up on android whereas it works perfectly on iOS... does it require another hack to make it working?

**Comment by jdpigeon** [comment]
I've noticed this error as well and am currently working around it by loading assets through the android src instead of the js src (See this thread https://github.com/airbnb/lottie-react-native/issues/78)

As for @NicolasBonduel's suggestion, I tried that as well and, although it avoided the crash, noticed that it didn't allow animations to run properly

**Comment by NicolasBonduel** [comment]
My guess is that we're trying to generate the animations with a version of the bodymovin plugin that is not yet supported by Lottie. I will try to work around that by using a previous version.

**Comment by NicolasBonduel** [comment]
I actually fixed it by doing like @jdpigeon does here:
https://github.com/airbnb/lottie-react-native/issues/78

**Comment by lukaleli** [comment]
Yeah, I did that too. It works but it's just a workaround that results in keeping duplicated assets in two places. Not pretty.

**Comment by NicolasBonduel** [comment]
It's definitely a hack, until Lottie is updated.

**Comment by Minishlink** [comment]
With the new 1.2.0 version, it doesn't crash anymore, but the animation doesn't seem to be running :/

I got warnings but no errors:
> - Animation contains merge paths but they are disabled
> - Composition larger than the screen 900x302 vs 720x1184. Scaling down.

**Comment by gpeal** [comment]
This should be fixed in the latest version.

**Comment by spalanci** [comment]
You can also get this error when you forget to import a package
