### ISSUE TITLE
Import AI file into After Effects

### ISSUE THREAD

**Issue by jongmin92** [airbnb/lottie-react-native#121]
I'm using lottie-react-native: **1.0.6**
**I make a shape with an illustrator and then Import AI file into After Effects and “Create Shapes from Vector Layer”**
The result looks like this:
How can I fix it if it does not come out as intended?

![image](https://cloud.githubusercontent.com/assets/15906302/25362803/314a1aee-2991-11e7-8a36-f80e10b4b855.png)

[failed.aep.zip](https://github.com/airbnb/lottie-android/files/953453/failed.aep.zip)

**Comment by therealsalih** [comment]
@jongmin92 Not everything that works in illustrator will import as a shape layer in after effects. Things like pattern fills and some gradients and a bunch of other stuff just don't get converted. Best thing to try is to re-build whatever is missing in After Effects itself

**Comment by gpeal** [comment]
@jongmin92 Also, the slightly off rendering is probably due to https://github.com/airbnb/lottie-react-native/issues/128 and will be fixed very soon.
