### ISSUE TITLE
Setting initial progress only works asynchronously

### ISSUE THREAD

**Issue by ragnorc** [airbnb/lottie-react-native#122]
When setting the progress prop of the animation to 1 the animation does not show up.
It only works using an async function such as setTimeout in componentWillMount().

```
componenentWillMount() {
setTimeout(()=>{this.setState({progress: 1})}, 1);
}
```

Related: [https://github.com/airbnb/lottie-ios/pull/91](https://github.com/airbnb/lottie-ios/pull/91)
               [https://github.com/airbnb/lottie-ios/issues/56](https://github.com/airbnb/lottie-ios/issues/56)

**Comment by simonmitchell** [comment]
Did you have any luck with this @ragnorc? It seems like they've fixed it in the Lottie library, but it's still broken for me in lottie-react-native

**Comment by simonmitchell** [comment]
See PR here: https://github.com/airbnb/lottie-ios/pull/245

**Comment by ragnorc** [comment]
@simonmitchell No luck yet. Still waiting for them to fix it in RN as well.

**Comment by simonmitchell** [comment]
I've submitted a PR to fix it which you can see above :) if you want to give our fork a go, let me know if it works okay for you!

**Comment by ragnorc** [comment]
@simonmitchell  Awesome!

**Comment by gpeal** [comment]
This should be fixed in the latest release! Feel free to reopen if it's still an issue.
