### ISSUE TITLE
Animation is not displayed into <MapView.Marker> custom view 

### ISSUE THREAD

**Issue by weswes** [airbnb/lottie-react-native#123]
I want to use a lottie animation into a Map Marker (https://github.com/airbnb/react-native-maps) custom view, but it's not working on Android (it's ok with iOS).
I use a sample animation provided to test it (HamburgerArrow.json).

CustomMarker:

```
export default class CustomMarker extends Component {
  componentDidMount() {
    console.log('CustomMarker did mount');
    this.animation.play();
  }

  render() {
    return (
      <View style={{width: 80,height: 80, 
                    flex:1, alignItems:'center',
                    backgroundColor:'#55443355'}}>
          <Animation
                ref={animation => { this.animation = animation; }}
                style={{ width: 50,height: 50 }}
                loop={true}
                source={require('../animations/HamburgerArrow.json')}
            />
         <View style={{backgroundColor:'#FFFFFF', width:5, height:5}}></View>
        </View>
    );
  }
}
```

Animation into CustomMarker working with this simple view (Android ok, iOS ok)

```
export default class TestView extends Component {
  render () {
        return (
          <ScrollView style={{backgroundColor:'#000000', flex:1, marginTop:50}}>
             <CustomMarker></CustomMarker >
          </ScrollView> 
        );
    }

}
```
Result:
![screenshot_1493133386](https://cloud.githubusercontent.com/assets/3978000/25393370/953859b8-29db-11e7-8602-cc404a377473.png)

Animation not displayed into map view (Android ko, iOS ok)

```
render () {
        return (
            <MapView
                provider={PROVIDER_GOOGLE}
                customMapStyle={mapStyle} 
                style={this.props.style}
                region={getRegionForCoordinates(this.props.markers)}
               >
                <MapView.Marker
                    key='me' anchor={{x:0.5 , y:0.5}}
                    coordinate={{latitude: 48.866667,longitude: 2.333333}}
                  >
                  <UserMarker></UserMarker>
                </MapView.Marker>
               
            </MapView>
        );
    }
```
Result:
![screenshot_1493133383](https://cloud.githubusercontent.com/assets/3978000/25393464/cfa76b2a-29db-11e7-9d7f-c43a5ecbbb58.png)

Lib Version:
 "lottie-react-native": "^1.1.1",
 "react-native": "0.43.3",
 "react-native-maps": "^0.13.0",

Tested on emulator and real device.
No error in debugger. No error in Android monitor.

Is there a particular behavior of MapView.Marker that is not compatible with Animation on Android?

**Comment by moritzschaefer** [comment]
I observe the same issue with Android and th AnimatedViews example (https://github.com/airbnb/react-native-maps/tree/master/example/examples)

**Comment by weswes** [comment]
Found in Readme: 

>Issue: Since android needs to render its marker views as a bitmap, the animations APIs may not be compatible with the Marker views. Not sure if this can be worked around yet or not.

**Comment by neo125874** [comment]
@weswes hi, so it means the maps on android would never work with animation, right?  so sad...

**Comment by weswes** [comment]
Only animation into Markers yes.

The workaround is to add a custom view as our marker upon the map component and place it at the right position.

**Comment by moritzschaefer** [comment]
Could you elaborate on that please? How do get the x/y coordinates of the
markers given there latitude/longitude?


weswes <notifications@github.com> schrieb am Fr., 7. Juli 2017, 10:59:

**Comment by neo125874** [comment]
@weswes same as @moritzschaefer , what's the custom view for?  put inside the marker? or any other maps component?

**Comment by weswes** [comment]
The idea is to put a custom view that you will use as your animated marker as sibling of the MapView component (in my case it's an Animation component from lottie lib but can be any other view)

```
<View >
              <MapView
                onLayout={(event) => this.measureMapView(event)}
                region={this.state.mapRegion}
                onRegionChangeComplete={this.regionChanged.bind(this)}/>
            <Animation
                ref={animation => { this.animation = animation; }}
                style={{ width: viewportWidth,height: viewportWidth , position:'absolute',
                        left: this.state.markerPosition.x, top: this.state.markerPosition.y}}
                loop={true}
                source={this.state.animationSource}
                pointerEvents="none"
            />
</View>
```

Listen for onRegionChangeComplete and then update your custom component position with some Math:

```
regionChanged(region){
      const {initialRegion} = this.state;
          if ( (initialRegion && initialRegion.latitude == region.latitude 
             && initialRegion.longitude == region.longitude
             && initialRegion.latitudeDelta == region.latitudeDelta
             && initialRegion.longitudeDelta == region.longitudeDelta)
             ) {
            return; // do nothing if region is the same
          }
      this.placeMarker(region);
 }

placeMarker(region){
   // longitude of the right side of your map
    rightLongitude = region.longitude + (region.longitudeDelta/2);
   // longitude of the left side of your map
    leftLongitude = region.longitude - (region.longitudeDelta/2);
  // latitude of the top side of your map
    topLatitude = region.latitude - (region.latitudeDelta/2);
  // latitude of the bottom side of your map
    bottomLatitude = region.latitude + (region.latitudeDelta/2);
  
// this.props.position contains the longitude/latitude of your marker  
// X position of your component in pixels
    left = ( viewportWidth / PixelRatio.get()
              * (this.props.position.longitude - leftLongitude)
                    / (rightLongitude - leftLongitude))
        - (viewportWidth/PixelRatio.get()/2);
 // Y position of your component in pixels   
    top = ( (viewportHeight) /PixelRatio.get() 
            * (this.props.position.latitude - bottomLatitude) 
                    / (topLatitude - bottomLatitude))
    - (viewportWidth/PixelRatio.get()/2)
    ;
    var newMarkerPosition = {x: left , y:  top};
    this.setState({
      userMarkerPosition: newMarkerPosition
    });
  }

```

The custom view will be moved after the map, but it's a correct solution when the user don't interact with the map.

**Comment by neo125874** [comment]
@weswes thank you for your detail solution, maybe the owner could try to workaround like this, haha?

**Comment by reggie3** [comment]
I wrote a blog post detailing two additional ways to work around this problem on Android.  One involves using setTimeout to swap images.  The other uses requestAnimationFrame to update a state value that is used to set the size of a FontAwesome icon.  The post is here: [https://medium.com/@reginald.johnson/providing-location-aware-user-feedback-9ad50ca8c7ff](https://medium.com/@reginald.johnson/providing-location-aware-user-feedback-9ad50ca8c7ff)
I'm trying to extend on the requestAnimationFrame technique.  I hypothesized that I could force a redraw of the map on every requestAnimationFrame which would force a re-render of the the child location components allowing a more conventional animation technique like react-motion to work.  However, even though the map and marker both re-render, react-motion does not update the value that is should be updating.

**Comment by gpeal** [comment]
I'm going to close this unless you think this issue issue is specifically related to Lottie.

**Comment by lucasmouse** [comment]
Use refThis.mapView.current.animateToRegion(region, 400)
init mapView = React.createRef()
<MapView ref={this.mapView}/>

**Comment by khanh21011999** [comment]
Any solution for this :(
