### ISSUE TITLE
Error while linking

### ISSUE THREAD

**Issue by jksyrek** [airbnb/lottie-react-native#124]
I try to implement lib in my project using official installation guide.

When I try to link library with `react-native link lottie-react-native`, I get an error 
```
rnpm-install ERR! Something went wrong while linking. Error: Expected "/*" or ";" but "\"" found.
Please file an issue here: https://github.com/facebook/react-native/issues

Expected "/*" or ";" but "\"" found.
```

I use:
- "react": "16.0.0-alpha.6"
- "react-native": "0.43.4"
- "lottie-react-native": "^1.1.1"

**Comment by jksyrek** [comment]
After some more research I get some conclusions.

In the file `myapp/ios/myapp.xcodeproj/project.pbxproj` in the section `XCBuildConfiguration` we have a line `HEADER_SEARCH_PATHS`.

Its initial state is:
```
HEADER_SEARCH_PATHS = "$(REACT_HEADERS_PATH)";
```

After executing `react-native link lottie-ios` it is changed to:
```
HEADER_SEARCH_PATHS = "$(REACT_HEADERS_PATH)""$(SRCROOT)/../node_modules/lottie-ios/Lottie-Screenshot/**";
```

At this point, when I'm trying to execute `react-native link lottie-react-native` I get an error:
```
rnpm-install ERR! It seems something went wrong while linking. Error: Expected "/*" or ";" but "\"" found.
Please file an issue here: https://github.com/facebook/react-native/issues

Expected "/*" or ";" but "\"" found.
```

I don't really understand why I get this error message, since there is no " \ " sign in this line.

However, when I revert HEADER_SEARCH_PATHS to its initial state, I'm able to execute command without any errors.

Final state after successful `react-native link lottie-react-native` :
```
HEADER_SEARCH_PATHS = "$(REACT_HEADERS_PATH)""$(SRCROOT)/../node_modules/lottie-react-native/lib/ios/LottieReactNative";
```

Any ideas why it happen?

**Comment by yqbk** [comment]
I have found an issue.

The problem was in the line
```
HEADER_SEARCH_PATHS = "$(REACT_HEADERS_PATH)""$(SRCROOT)/../node_modules/lottie-react-native/lib/ios/LottieReactNative";
```

When I changed it to:
```
HEADER_SEARCH_PATHS = (
    "$(inherited)",
    "$(SRCROOT)/../../node_modules/lottie-react-native/lib/ios/LottieReactNative",
);
```

Everything started working correctly **without** linking manually in xcode.

So in my case the main problem was with going to the correct directory from the current path.

I think this solution could be connected with #82

**Comment by tomauty** [comment]
That worked for me, too. Note that some pbxproj files (mine...) have to be changed in multiple places.

**Comment by kelset** [comment]
I'm having this issue while trying to install latest `1.2.0` in `react-native: 0.46.4`.
As far as I can tell, there are actually two issues here:

1. When linking `react-native link lottie-ios`, the script doesn't escape properly what it needs to paste into `project.pbxproj`, so it "paste" in the config:
```
HEADER_SEARCH_PATHS = "$(inherited)""$(SRCROOT)/../node_modules/lottie-ios/Lottie-Screenshot/**";
```

instead of:

```
HEADER_SEARCH_PATHS = (
	"$(inherited)",
	"$(SRCROOT)/../node_modules/lottie-ios/Lottie-Screenshot/**"
);
```

Similarly, it also "paste": 

```
LIBRARY_SEARCH_PATHS = (
	"$(inherited)",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
);
```

instead of:

```
LIBRARY_SEARCH_PATHS = (
	"$(inherited)",
	"$(SRCROOT)/$(TARGET_NAME)",
);
```

2.  And similar issue happens when running `react-native link lottie-react-native`, where it gets again the LIBRARY part wrong.

Fixing them by hand allows me to build the app properly.

**Comment by gpeal** [comment]
I'm closing this to clean up old issues. Feel free to reopen if it's still an issue.
