### ISSUE TITLE
UNMET PEER DEPENDENCY Error 

### ISSUE THREAD

**Issue by dmolesworth** [airbnb/lottie-react-native#13]
When I run 
`npm i --save lottie-react-native`
I get an error message saying;

├─┬ lottie-react-native@1.0.0 
│ └── UNMET PEER DEPENDENCY react-native@*
├── UNMET PEER DEPENDENCY react@>=15.3.1
└── UNMET PEER DEPENDENCY react-native@>=0.35
npm WARN lottie-react-native@1.0.0 requires a peer of react@>=15.3.1 but none was installed.
npm WARN lottie-react-native@1.0.0 requires a peer of react-native@>=0.35 but none was installed.
npm WARN react-native-safe-module@1.1.0 requires a peer of react-native@* but none was installed.

Running the latest version of React Native

**Comment by lelandrichardson** [comment]
@dmolesworth which version of react and react-native are you using? Since those are peer dependencies, you will also need to install them if you don't have them already (which is what it looks like from your error message)

**Comment by dmolesworth** [comment]
thanks for getting back to me, i'm running version 0.40. I'll look at installing the dependancies

**Comment by lelandrichardson** [comment]
Closing. NPM is behaving as expected. react-native and react are peer dependencies.
