### ISSUE TITLE
Merged shapes not showing up on iOS using React Native

### ISSUE THREAD

**Issue by brianliebler** [airbnb/lottie-react-native#130]
We are using React Native for iOS and the animated icon only shows as a square and is missing the three triangles. Is this the Merged Path issue on iOS? If so, when do you expect it to be supported and is there a work around? Thanks!

**Comment by gpeal** [comment]
Fill types are not yet supported in iOS. You can track the progress here: https://github.com/airbnb/lottie-ios/issues/43

**Comment by breadadams** [comment]
Sorry to comment on an old issue, think we're running into this with some animations received from a client. They've said that there are "merged shapes with subtracts", which are basically the _holes_ in some map pins. However we're just getting a flat pin in the animation (with no cutout).

Does that seem to fit the bill for this problem? I notice in the issue mentioned by @gpeal it's been _resolved_ as of 2.0 🤔. Cheers
