### ISSUE TITLE
[Android] Animation would not play when starting off screen in ListView

### ISSUE THREAD

**Issue by motiazu** [airbnb/lottie-react-native#131]
I have an animation that appears in the bottom of my ListView and calls `play` on mount with loop=true. If the initial render is out of screen, the animation will just freeze on the first frame and never play even though `play` was called.

I looked at the play method in the native code and found that because `ViewCompat.isAttachedToWindow(view)` in `LottieAnimationViewManager.java` evaluates to `false` when the Animation is not in the visible part of my `ListView`.

I commented it out and it seems to work perfectly for me. I looked for some commit comments and didn't find anything suggesting why we shouldn't play the animation unless it's attached to a window.
It does seem to work without it in my scenario with no errors/warnings, is there a good reason for this condition to be there?
If so, shouldn't the lib do something other than completely ignore the `play` command?

Thanks

**Comment by gpeal** [comment]
@motiazu Playing an animation while it is off screen is problematic for performance and resource reasons. I suggest figuring out a way to set the initial progress or implement some other workaround that doesn't rely on the animation animating while off screen.
