### ISSUE TITLE
styling not working properly

### ISSUE THREAD

**Issue by cinder92** [airbnb/lottie-react-native#135]
Hello i just installed succesfully this awesome package, but i want to make the animation bigger, but instead, only the wrapper is making big, like the current image.

![captura de pantalla 2017-05-25 a la s 21 58 45](https://cloud.githubusercontent.com/assets/4725556/26478957/8c85b8c0-4195-11e7-8351-07fe4b894539.png)

how can i fix this issue?

```
<Animation
  style={{ 
       width: 80,
       height: 80,
      backgroundColor : colors.red
 }}
 source={pause}
 progress={pauseBtn}
 />
```

**Comment by gpeal** [comment]
[This](https://github.com/airbnb/lottie-react-native/commit/4c1bff110b735dbf16bef145d41fdb6274221490) should help
