### ISSUE TITLE
ios Individual animations not successfully reproduced

### ISSUE THREAD

**Issue by AlexDM0** [airbnb/lottie-react-native#138]
Hi, I tried using a simple animation of our logo with lottie. It consists of scale, rotation and position animations of two items. These items (ball and bar) are duplicated five times in precompositions.

The expected result (using the bodymovin demo export) 
https://cdn.rawgit.com/crownstone/CrownstoneApp/lottie/js/animations/demo.html

What I see (simulator and device)
https://github.com/crownstone/CrownstoneApp/blob/lottie/js/animations/screencapture.gif

The JSON:
https://github.com/crownstone/CrownstoneApp/blob/lottie/js/animations/crownstoneAnimatedLogo.json

If I export the bars individually, they animate perfectly so there are no unsupported methods.

Any ideas?

**Comment by AlexDM0** [comment]
I found the other issue I joined for this over at lottie-ios (https://github.com/airbnb/lottie-ios/issues/225). If this is a different team, my file can be found here if required. 
https://www.dropbox.com/s/5sdqkbjugcsegaz/crownstoneLogo.aep?dl=0

Technically I think this issue is a duplicate so you can close if you'd like

**Comment by buba447** [comment]
Ahh I see it. The issue is that you are using an expression to animate the bar. Lottie ios and android do not support expressions. A work around is to either animate it using keyframes or you can select the channel with the expression and in the animation menu convert it to keyframes!
