### ISSUE TITLE
Animation not running iOS

### ISSUE THREAD

**Issue by thanhtr** [airbnb/lottie-react-native#140]
Hello,

I am trying to implement Lottie as part of our React Native project. I am able to run jsons from the examples here but not ours. I wonder what's wrong with the json, or something specific has to be done in Lottie.

The animation loaded just simply by:
```
componentDidMount() {
      Animated.timing(this.state.progress, {
        toValue: 1,
        duration: 5000,
      }).start();
    }
....
render() {
      return (
        <View
          style={{
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <Animation
            style={{
              width: 300,
              height: 400,
            }}
            source={require('../../assets/Scan_part_one.json')}
            progress={this.state.progress}
            loop={true}
          />
        </View>
      );
```

Attached is the json I used.

Thank you very much.

[Scan_part_one.json.zip](https://github.com/airbnb/lottie-react-native/files/1071372/Scan_part_one.json.zip)

**Comment by sahanay** [comment]
I'm experiencing the same problem. Any help would be appreciated :).

**Comment by luyx2412** [comment]
Same issue, animation do not trigger on IOS
`this.animation.play()` do not handle. 
But i use 
`this.state.progress.setValue(0)
        Animated.timing(this.state.progress, {
            toValue: 1,
            duration: 2000,
        }).start((o) => {
            if (o.finished) {
                this._runAnimation()
            }
   })`
it will run, i don't understand what wrong?

**Comment by gpeal** [comment]
@thanhtr This is working for me on master and I'll push a new update tonight. Please reopen this on lottie-ios if it's an iOS specific rendering issue.
