### ISSUE TITLE
Animation is different

### ISSUE THREAD

**Issue by pfulop** [airbnb/lottie-react-native#141]
For some strange reasons, my actual animation is different from what it is supposed to look like.

this is how it should look like
![kapture 2017-06-13 at 11 17 49](https://user-images.githubusercontent.com/3984319/27084580-b30f8992-504c-11e7-8255-fb57d792bd69.gif)

and this is how it looks like
![kapture 2017-06-13 at 15 23 56](https://user-images.githubusercontent.com/3984319/27084584-b4ff334c-504c-11e7-876d-648287cc193a.gif)

here is my json: https://pastebin.com/qUmdH1si

If anybody knows why, I would really appreciate any help.

**Comment by gpeal** [comment]
@pfulop Can you file this individually on lottie-ios and lottie-android with the AEP attached as well?

**Comment by spearmootz** [comment]
what was the reason? im having this issue on ios

**Comment by pfulop** [comment]
Never found out. Since it wasn't crucial to our app, more like an experiment, we never tried to figure it out or open issues on other lottie repositories.

**Comment by gpeal** [comment]
@spearmootz Could be lots of things. Can you attach the animation?

**Comment by spearmootz** [comment]
i think its related to lottie-ios not lottie-react-native

https://github.com/airbnb/lottie-ios/issues/439
