### ISSUE TITLE
Animation not center correctly

### ISSUE THREAD

**Issue by yotavm** [airbnb/lottie-react-native#143]
hey,
i using lottie -v master
and react v0.44.0
when i use the animation component the position is going left and down 
but if i use backgroundcolor i see that the real location need to be in the center
i attached image to explain
<img width="344" alt="screen shot 2017-06-19 at 15 18 56" src="https://user-images.githubusercontent.com/11390250/27284935-72fe5214-5503-11e7-9721-4724ae924a7e.png">
this is the animation component style: 
  placeHolder:{
    height:272,
    width:272,
    backgroundColor:'black',
    marginBottom:39,
  },
* my json file use images

**Comment by palmm** [comment]
Hey @yotavm, I ran into a similar issue today. Try wrapping your `Animation` in a `View` with the same width and height.

e.g.
```
    <View style={{ flex: 1, justifyContent: 'center', alignContent: 'center' }}>
      <View
        style={{
          width: width - 100,
          height: width - 100,
        }}
      >
        <Animation
          style={{
            width: width - 100,
            height: width - 100,
          }}
          source={animationSrc}
          progress={this.state.progress}
        />
      </View>
    </View>
```

That workaround should hopefully let you align the animation as you want.

**Comment by yotavm** [comment]
thanks its working

**Comment by Creemli** [comment]
I don't think wrapping it two useless View is correctly. We would better find the reason in Native.

**Comment by alexlevy0** [comment]
+1
