### ISSUE TITLE
json with assets

### ISSUE THREAD

**Issue by yotavm** [airbnb/lottie-react-native#145]
When i use json with asset i get:
2017-06-19 18:58:23.108 Oklive[27198:7781275] -[LOTLayerView _setImageForAsset]: Warn: image not found: img_0
the animation working but without the image parts 
(v1.1.1)

**Comment by dioxide** [comment]
+1 ,same problem

**Comment by vmktharun** [comment]
Same problem, how to add the folder(of images) to the animations in react native....

**Comment by yotavm** [comment]
i find a way 

when you look on lottie ios code in [LOTLayerView.m](https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/AnimatableLayers/LOTLayerView.m):
in the lottie ios repo the function  look like this and 
```
- (void)_setImageForAsset {
    if (_layerModel.imageAsset.imageName) {
        UIImage *image;
        if (_layerModel.imageAsset.rootDirectory.length > 0) {
            NSString *rootDirectory  = _layerModel.imageAsset.rootDirectory;
            if (_layerModel.imageAsset.imageDirectory.length > 0) {
                rootDirectory = [rootDirectory stringByAppendingPathComponent:_layerModel.imageAsset.imageDirectory];
            }
            NSString *imagePath = [rootDirectory stringByAppendingPathComponent:_layerModel.imageAsset.imageName];
            image = [UIImage imageWithContentsOfFile:imagePath];
        }else{
            NSArray *components = [_layerModel.imageAsset.imageName componentsSeparatedByString:@"."];
            image = [UIImage imageNamed:components.firstObject inBundle:_bundle compatibleWithTraitCollection:nil];
        }
        
        if (image) {
            _childSolid.contents = (__bridge id _Nullable)(image.CGImage);
        } else {
            NSLog(@"%s: Warn: image not found: %@", __PRETTY_FUNCTION__, _layerModel.imageAsset.imageName);
        }
    }
}
```
and in the version i install with react native its look like this

```
(void)_setImageForAsset {
  if (_layerModel.imageAsset.imageName) {
    NSArray *components = [_layerModel.imageAsset.imageName componentsSeparatedByString:@"."];
    UIImage *image = [UIImage imageNamed:components.firstObject];
    if (image) {
      _childSolid.contents = (__bridge id _Nullable)(image.CGImage);
    } else {
      NSLog(@"%s: Warn: image not found: %@", __PRETTY_FUNCTION__, components.firstObject);
    }
  }
}
```

you can see that in the ios repo they handle folder and in react version just image name 
so the for me to fix it with out change is to get all the image from bodymovin image folder 
(ex: img_0,img_1 etc)
and add them to bundle resources
if this dont work try to had with the folder (you can search _setImageForAsset in xcode and see the function version )

hope this help =]

**Comment by bboyair** [comment]
+1 - the same problem

**Comment by kelset** [comment]
Same issue over here, on iOS the image doesn't get loaded.
Any update anyone?

In another issue, #80 (of which imho this is a duplicate) they were considering the [`imageAssetFolder` prop](https://github.com/airbnb/lottie-react-native/commit/6cafa8b1f44f973ca2aec173792c1b3ccfb407a6) as possible solution but it's Android only :(

**Comment by kelset** [comment]
Quick update: in iOS to have the animation pick up the image you need to - basically - open XCode, right click on the Resources folder, "Add file to [Project]" and add the image (and then rebuild the project) - so my suggestion is that you give that image a "recognizable name" when you import it;)

**Comment by cth0mas** [comment]
@kelset is it also required to update the lottie json to remove the 'image/' path ref's?
