### ISSUE TITLE
example works but not lottie files from 'lottiefiles.com' | Android

### ISSUE THREAD

**Issue by PARAGJYOTI** [airbnb/lottie-react-native#147]
All the 13 examples provided in  lottie-react-native works well , but importing other json files from 
lottiefiles.com doesn't work . the App crashes even before not playing the animation .
Any idea how to fix this ? I tried removing the "fr", "ip" but no help.

Edit : Figured out json having doubles values throws exeption . It only works with float numbers, but its impossible to convert every double values to float manually .

**Comment by yash2code** [comment]
same issue

**Comment by thotegowda** [comment]
This [PR](https://github.com/airbnb/lottie-react-native/pull/129) will fix it ?

**Comment by gpeal** [comment]
@PARAGJYOTI which ones don't work?

**Comment by gpeal** [comment]
@PARAGJYOTI @yash2code  Can you file any rendering issues on lottie-android or lottie-ios?
