### ISSUE TITLE
this.animation is `undefined` 

### ISSUE THREAD

**Issue by Herb-Sun** [airbnb/lottie-react-native#148]
When I used Modal containing Animation components
Crash info "this.animation is `undefined` "
```
import React from 'react';
import Animation from 'lottie-react-native';

export default class BasicExample extends React.Component {
  componentDidMount() {
    this.animation.play();
  }

  render() {
    return (
        <Modal animationType="slide" transparent={true} visible={false}>
            <Animation
                ref={animation => { this.animation = animation; }}
                style={{
                    width: 200,
                    height: 200,
                }}
                source={require('../path/to/animation.json')}
            />
        </Modal>
    );
  }
}
```

**Comment by gpeal** [comment]
@Herb-Sun This isn't a lottie specific issue. This is just a react issue.

**Comment by simonso-nzme** [comment]
@Herb-Sun Try doing the this.animation.play(); at **onShow** of the Modal

i.e. <Modal onShow={()=>{ this.animation.play(); }}>

**Comment by mikeKane** [comment]
If this isn't a Lottie issue, why would the api docs show that this is the way to play your animation? Is there not a way for React-Native to play these animations as expected?

**Comment by nescroft** [comment]
try:
 setTimeout(() => {
    this.animation.play();
  }, 200);
