### ISSUE TITLE
cocoapods and npm has different lottie-ios libs with same version number (1.5.2)

### ISSUE THREAD

**Issue by thotegowda** [airbnb/lottie-react-native#149]
react-native ios app fails to build with cocoapods lottie-ios (1.5.2). But works fine with npm downloaded lottie-ios 1.5.2.

I did check code, some commits are present only in lottie-ios distributed through npm but missing in  the library distributed through cocoapods

**Comment by gpeal** [comment]
I'll push a new version with updated dependencies today.
