### ISSUE TITLE
Support for Time-remapping

### ISSUE THREAD

**Issue by SayEason** [airbnb/lottie-react-native#150]
Just discovered the Lottie-android has Time-remapping support a few days ago. Don't know when the react-native version can get that, or will it ?

**Comment by gpeal** [comment]
@SayEason I'm going to publish a new release soon with the latest lottie-android changes. You may want to post an issue on lottie-ios to add support for it though.

**Comment by gpeal** [comment]
@SayEason 1.2.0 has been published. Check it out!
