### ISSUE TITLE
Text not rendering unless outlined

### ISSUE THREAD

**Issue by fentonbutcher** [airbnb/lottie-react-native#159]
We are using the latest Lottie (2.1.0) and the latest version 1.2.0 for React native (which apparently supports text). We exported from After Effects with google fonts enabled in bodymovin. The animation along with the text shows up when we test it online using bodymovin.js (example here: https://codepen.io/torrens/project/editor/DVvqmo/ ), but doesn't show up when we build it into the app.

A note from one of our devs 

"I'm using lottie-react-native v1.2.0 in an Expo application. @fentonbutcher has created a JSON file using After Effects 2017 and the BodyMovin plugin. Unfortunately, the text isn't showing in our react-native application, although it is showing correctly using bodymovin.js in a browser."

Any help would be greatly appreciated.

**Comment by gpeal** [comment]
@fentonbutcher Can you file an issue on lottie-android or lottie-ios for rendering issues?
