### ISSUE TITLE
Extra empty elements while making multiple elements

### ISSUE THREAD

**Issue by Obooman** [airbnb/lottie-react-native#160]
Code:

``` js
<Animation 
  progress={this.state.progress}
  style={{ width:20,height:20 }} 
  source={ require('./question.json') }
  />
<Animation 
  progress={this.state.progress}
  style={{ width:20,height:20 }} 
  source={ require('./question.json') }
  />
/>
```

![group](https://user-images.githubusercontent.com/9863282/28651197-f25ab120-72b2-11e7-8a10-b0df88bfcc49.png)

When I add more than one element each of theme will be followed by an empty element which share same size with Animation object.

**Comment by gpeal** [comment]
@Obooman I can't reproduce this. If you can attach a project that does, I'll take a look.
