### ISSUE TITLE
only one animation not work 

### ISSUE THREAD

**Issue by yotavm** [airbnb/lottie-react-native#163]
hey,
i have a working project with lottie all my animation work except 
one (when i check it on lottiefiles its work)
this is the json -> 
`{"v":"4.9.0","fr":40,"ip":0,"op":120,"w":36,"h":36,"nm":"check","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":1,"nm":"Blue Solid 2","sr":1,"ks":{"o":{"a":0,"k":100},"r":{"a":0,"k":0},"p":{"a":0,"k":[-109.5,-187.75,0]},"a":{"a":0,"k":[187.5,333.5,0]},"s":{"a":0,"k":[100,100,100]}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0]],"v":[[308.812,539.812],[313.125,544.125],[322.688,534.562]],"c":false}},"o":{"a":0,"k":100},"x":{"a":0,"k":0},"nm":"Mask 1"}],"ef":[{"ty":22,"nm":"Stroke","mn":"ADBE Stroke","ix":1,"en":1,"ef":[{"ty":10,"nm":"Path","mn":"ADBE Stroke-0001","ix":1,"v":{"a":0,"k":1}},{"ty":7,"nm":"All Masks","mn":"ADBE Stroke-0010","ix":2,"v":{"a":0,"k":0}},{"ty":7,"nm":"Stroke Sequentially","mn":"ADBE Stroke-0011","ix":3,"v":{"a":0,"k":1}},{"ty":2,"nm":"Color","mn":"ADBE Stroke-0002","ix":4,"v":{"a":0,"k":[1,1,1,1]}},{"ty":0,"nm":"Brush Size","mn":"ADBE Stroke-0003","ix":5,"v":{"a":0,"k":2}},{"ty":0,"nm":"Brush Hardness","mn":"ADBE Stroke-0004","ix":6,"v":{"a":0,"k":0.75}},{"ty":0,"nm":"Opacity","mn":"ADBE Stroke-0005","ix":7,"v":{"a":0,"k":1}},{"ty":0,"nm":"Start","mn":"ADBE Stroke-0008","ix":8,"v":{"a":0,"k":0}},{"ty":0,"nm":"End","mn":"ADBE Stroke-0009","ix":9,"v":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":0,"s":[0],"e":[100]},{"t":13}]}},{"ty":7,"nm":"Spacing","mn":"ADBE Stroke-0006","ix":10,"v":{"a":0,"k":15}},{"ty":7,"nm":"Paint Style","mn":"ADBE Stroke-0007","ix":11,"v":{"a":0,"k":2}}]}],"sw":375,"sh":667,"sc":"#3940f6","ip":0,"op":120,"st":0,"bm":0}]}`

and this is image for what i get -> (the black is a background the animation is the purple one and what i need to get is a white checkIcon )
<img width="358" alt="screen shot 2017-07-27 at 17 10 08" src="https://user-images.githubusercontent.com/11390250/28674581-79f1a7d4-72ee-11e7-99ae-cbcff367470b.png">

lottie-react-native@last
bodymovin@last

**Comment by gpeal** [comment]
@yotavm Lottie doesn't support layer effects. You can achieve this using just a shape and a trim path though.
