### ISSUE TITLE
Android build error when using React-Native 0.47

### ISSUE THREAD

**Issue by RyanMitchellWilson** [airbnb/lottie-react-native#166]
I just upgraded to React-Native 0.47.0 and when I try to run `react-native run-android`, the build fails with:
```
:lottie-react-native:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/ryanwilson/work/AthlinksMobile/node_modules/lottie-react-native/lib/android/src/main/java/com/airbnb/android/react/lottie/LottiePackage.java:18: error: method does not override or implement a method from a supertype
  @Override public List<Class<? extends JavaScriptModule>> createJSModules() {
  ^
1 error
:lottie-react-native:compileReleaseJavaWithJavac FAILED
```

Using:
react-native: 0.47.0
react: 16.0.0-alpha.12
lottie-react-native: 1.2.0

**Comment by bduyng** [comment]
+1

**Comment by aamctustwo** [comment]
See discussion: https://github.com/facebook/react-native/issues/15232

**Comment by RyanMitchellWilson** [comment]
@aamctustwo they have already closed that issue stating that there is no way to make this change without breaking something so the work to fix it needs to be done in the libraries themselves.

**Comment by lukecwilliams** [comment]
Fix is: in LottiePackage.java, remove createJSModules function entirely, or just remove @Override parameter.

This works locally (as long as the node_modules package isn't reinstalled) until a fix is issued from each library.

**Comment by radko93** [comment]
Submitted a PR #169.

**Comment by gpeal** [comment]
This will be fixed in the next release

**Comment by sospedra** [comment]
@gpeal when is next release? :)

**Comment by gpeal** [comment]
@sospedra @bduyng @RyanMitchellWilson  2.2.0 has been published!

**Comment by alexsmartens** [comment]
+1
