### ISSUE TITLE
lottie-ios dependency is significantly out-of-date

### ISSUE THREAD

**Issue by AWrightIV** [airbnb/lottie-react-native#172]
[This line in the package.json](https://github.com/airbnb/lottie-react-native/blob/e8234404c489a65aa0ee97ab456a673ecde781ed/package.json#L46) puts lottie-ios significantly behind the latest version. I'd like to write a pull request to improve lottie-ios for react native, but am blocked by this lagging dependency. When can we expect this will be brought up to speed?

**Comment by AWrightIV** [comment]
`lottie-ios` on npm just published version 2.0.5. `lottie-react-native` is still pointing at 1.5.2. Is there any incompatibility with versions 2.0.0 and higher blocking this from being updated?

**Comment by gpeal** [comment]
@AWrightIV I'll push an update today :)

**Comment by gpeal** [comment]
new updating coming today
