### ISSUE TITLE
Gradients along path supported? How?

### ISSUE THREAD

**Issue by JulianKingman** [airbnb/lottie-react-native#176]
OK, so I've identified several ways to create a gradient along a path, like this:
![gradientalongpath](https://user-images.githubusercontent.com/1566400/29490587-d593ef8e-850e-11e7-9621-a411c4ca9236.gif)

Unfortunately, none of them appear to work with Lottie. Here's what I've tried:
[x] Use Gradient Stroke from illustrator
[x] Use several Gradient Strokes from After Effects that connect (strokes only support linear gradients). Note, this works in the HTML demo, but not react native. [Gist here](https://gist.github.com/JulianKingman/3dd55a7fedf0ca4573e814cb67868071)
[x] Use stroke mask over image of gradient
[x] Use layer blending mode with angle gradient

There's one idea I'm holding off on because it will be so extremely tedious, and that is to create ~1,000 small circles of all the different colors in the gradient and change their opacity. I'm pretty sure that would work.

Before I go down that sad, lonely road, I wanted to see if stroke gradients are supported, and perhaps I'm missing something? Perhaps someone could tell me why the json file I linked to above doesn't work?

**Comment by JulianKingman** [comment]
One other thing I tried:
[x] Create 5 separate shapes (not strokes) with gradient fills, hack together the gradients, Trim Paths, and Trim Path offset angles until it looks acceptable. It displays in Lottie HTML, but not in react native (looks like below, one segment, no gradient fill)
<img width="317" alt="screen shot 2017-08-19 at 7 35 48 pm" src="https://user-images.githubusercontent.com/1566400/29490809-a08d088c-8515-11e7-9bf4-3cdd63c18865.png">

**Comment by D1no** [comment]
You should create animations along lotties supported properties. Bodymovin, which is simply an export format that come with a renderer for web, is *not* strict === lottie for native devices.

See here: 
https://github.com/airbnb/lottie-ios#supported-after-effects-features

In the case above I'd just create a circle with the gradient and rotate a mask on top of it. Done.

**Comment by JulianKingman** [comment]
Thanks for your reply! In reading over the features, it looks like the last option I tried should work, shouldn't it? Trim paths and trim path offsets appear to be allowed on shape layers...

For the circle gradient with mask, that would work if I could create an angled gradient, but it looks like only linear gradients are supported. Any ideas on how to get around that?

Thanks again for your help!

**Comment by D1no** [comment]
You can actually use radial gradients. Place it at one corner and rotate it accordingly. But the simplest thing is probably creating the gradient as you like as a image png and place it on the circle. People often forget that you can dynamically manage images in lottie and that it's a very performant solution to get baseline effects onto the stage (gpu bit mapping has been optimized on mobile for 15+ years).

**Comment by JulianKingman** [comment]
OK, so I've identified the problem. It turns out that Lottie in expo is currently pinned at v 1.2, which doesn't support gradients, so that kind of explains things! I opened an issue there (https://github.com/expo/expo/issues/528), and I'll close this one, as I'm confident one of these options will work.

I'm curious about what you said about radial gradients, is there a way to use them to get an asymmetric gradient that would allow a gradient like the one I pictured? Maybe using transparencies somehow?

**Comment by MadGraph** [comment]
Hi @JulianKingman for the gradient I found something from the bodymovin export I got and had to edit the json to add my gradient info there I made a quick post on medium https://medium.com/@mehdi.boumendjel/after-effects-x-bodymovin-x-lottie-gradients-black-white-rendering-issue-1ab36f2a2353

Also still didn't figure out how to get my gradient on a stroke yet or how to hack it for iOS (even though that works everywhere else)
