### ISSUE TITLE
Play from Frame 10 to Frame 20

### ISSUE THREAD

**Issue by D1no** [airbnb/lottie-react-native#178]
I was wondering how to **run an animation from and to a particular frame** (i.e. 10 to 20) at regular speed, than stop. The iOS and Android lottie implementation seem to support this.

The use case is simple. We have an animation of a counter, counting up and we would simply like to stop the animation at "the target count". Thous having one instance of an animation that can handle all states (max numbers possible in the counter).

![counter-example](https://user-images.githubusercontent.com/2397125/29528441-59d1321e-869c-11e7-99f9-c1ad3432aac1.gif)

**Comment by zolrath** [comment]
As a workaround until a proper API is introduced I've been doing something similar by setting my animated value driving progress to `desiredFrame/totalFrames` and ensuring I have a few frames in a row with the desired content.

**Comment by D1no** [comment]
Yeah, however, floating point in JS is a dangerous thing. We normalized all animations to 1000 frames now to get around it. However, I hope RN-Lottie starts to catches up now some what to the progress of the native libraries :/

**Comment by happyfloat** [comment]
Is there any news on that?
