### ISSUE TITLE
The part of https://www.lottiefiles.com cannot be displayed in Android

### ISSUE THREAD

**Issue by TrustTheBoy** [airbnb/lottie-react-native#179]
Some can't be used in Android, like https://www.lottiefiles.com/305-loader-4, not shown in Android

There is no problem with IOS

**Comment by zivchen** [comment]
another one
https://www.lottiefiles.com/117-progress-bar

**Comment by TrustTheBoy** [comment]
@zivchen I need IOS to be in agreement with Android

**Comment by zivchen** [comment]
@TrustTheBoy I meant another example of working in IOS and not android.
i found this one that works on both, https://www.lottiefiles.com/230-paginationpage-indicator

**Comment by TrustTheBoy** [comment]
@zivchen The boss asked to use https://www.lottiefiles.com/305-loader-4, and I did not want to change it

**Comment by TrustTheBoy** [comment]
@zivchen Because in the native, the use of normal, in the react native android, can not show, before I think I was not configured, the background only to find some show, some will not show

**Comment by Monte9** [comment]
@zivchen I am having the same issue. I am trying to use this animation: https://www.lottiefiles.com/596-pillow-animation

And it works fine on iOS, but it doesn't show up on Android. Any ideas on how to make sure an animation works for iOS and Android both?

**Comment by zivchen** [comment]
@Monte9  Unfortunately you will have to test them, the bug is if you have decimal values it wont work so you can look at the json and see.

**Comment by gpeal** [comment]
@TrustTheBoy @zivchen @Monte9 These all work with Lottie 2.2.5 on Android. I'm going to push a lottie-react-native release that uses that today

**Comment by Monte9** [comment]
@gpeal thanks for the update. Unfortunately, upgrading to `2.2.5` causes other issues which just fails to build the Android app. 

This is the related issue: https://github.com/airbnb/lottie-react-native/issues/196 Can you please look into this and maybe suggest a workaround/solution? Thanks
