### ISSUE TITLE
[!] Unable to find a specification for `lottie-ios`

### ISSUE THREAD

**Issue by wladyslaws** [airbnb/lottie-react-native#18]
When I want to run sample project (all steps followed) after running `nom run build:pods` i get following error:

> [!] Unable to find a specification for `lottie-ios` depended upon by `lottie-react-native`

when can cause this and how to fix it?
I also experienced this when integrating lottie to clean react native project (on pod install).

**Comment by kennydee** [comment]
Same problem here.

I'm using Pod 1.2.0

**Comment by kennydee** [comment]
Oh, just `pod repo update` :)

**Comment by grifotv** [comment]
@kennydee after running `pod repo update` I managed to run `npm run build:pods` successfully - thanks.

However, when running the example `npm run run:ios` although I get a `** BUILD SUCCEEDED **` message the app doesn't actually open.

Has anyone managed to run the iOS examples?


![atmhj2mcx2](https://cloud.githubusercontent.com/assets/435351/22546979/4d0580ec-e937-11e6-92d9-652e7319d629.gif)

**Comment by kennydee** [comment]
You have to launch the packager :)
`npm run start`

**Comment by grifotv** [comment]
@kennydee it worked! thanks again

**Comment by wladyslaws** [comment]
For me these steps combined also worked, so I vote for closing it or creating a PR for guidelines.

**Comment by lelandrichardson** [comment]
I'll add a note about the packager in the README, as well as the `pod repo update` in a troubleshooting section!  Thanks!
