### ISSUE TITLE
No ViewManager defined for class LottieAnimationView on android 

### ISSUE THREAD

**Issue by EyreGe** [airbnb/lottie-react-native#181]
my version:
"react-native": "^0.45.1",
"lottie-react-native": "^2.2.0",

I try :
react-native run-android
This might create a build failure.
cd android && ./gradlew clean

not fix

**Comment by tangtai** [comment]
I had the same problem on android, i fixed it by rebuild the app using a USB cable instead of over Wifi, try that and also remember to change 

android {
    compileSdkVersion 25 // <-- update this to 25
    // ...

according to the guide, hope it helps.

**Comment by gpeal** [comment]
Feel free to reopen this if @tangtai's solution doesn't work
