### ISSUE TITLE
File not rending properly on Android.

### ISSUE THREAD

**Issue by wandri** [airbnb/lottie-react-native#182]
Hello!

I'm using Lottie-android by Expo XDE (react-native-lottie).

My AAE file: 
[gear_problem_text.zip](https://github.com/airbnb/lottie-react-native/files/1264010/gear_problem_text.zip)

This is what I have with my bodymovin file  (the Gif recorder has some problem but all works)  :

![gear_demo](https://user-images.githubusercontent.com/15016833/29878406-bf0ae2bc-8da2-11e7-97c3-6e3edcc605a4.gif)

What I have on my emulator is the following:

![gear_smartphone](https://user-images.githubusercontent.com/15016833/29878484-eb82d25a-8da2-11e7-855b-2ab1f6e13cba.gif)

Do you have an idea why?

Thanks!

**Comment by MbF-Sathya** [comment]
https://stackoverflow.com/questions/46559504/error-on-bodymovin-animation-in-react-native

i am also facing the same issue like this. I am using create react native app and running through expo

**Comment by gpeal** [comment]
@wandri Can you file this on lottie-android or lottie-ios?
