### ISSUE TITLE
Problem in Android device

### ISSUE THREAD

**Issue by joaqtor** [airbnb/lottie-react-native#183]
When using the library, in Android I got the following error:

`undefined is not an object (evaluating '_reactNative.UIManager.LottieAnimationView.Commands')`

No problem in iOS.

I did run `react-native link lottie-react-native` successfully.

Any clue?

**Comment by sbehrends** [comment]
Having same issue here :(

**Comment by michaeltnguyen** [comment]
Looks like `react-native link` isn't working correctly.

You need to register the `LottiePackage` with your application.  

```
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return Arrays.<ReactPackage>asList(
                // my other packages here...
                new LottiePackage()
        );
    }
```

**Comment by gpeal** [comment]
If the LottiePackage step doesn't fix this, you can reopen.
