### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by cweise** [airbnb/lottie-react-native#184]
```
<View style={{ flexDirection: 'row', justifyContent: 'center', width: '100%', marginTop: 24 }}>
  <Animation ref={animation => { this.animation = animation; }} style={{ width: 200, height: 200 }} source={require('../../baum.json')} />
</View>
```

This leads to a warning: Failed prop type: Cannot read property 'style' of undefined...

Any ideas?

**Comment by vdesdoigts** [comment]
It may help you https://github.com/airbnb/lottie-react-native/pull/134

**Comment by gpeal** [comment]
@cweise I think this is fixed now

**Comment by analcy** [comment]
@cweise I have encountered the same problem as yours，solve it now?

**Comment by cubabit** [comment]
@cweise @analcy - me too.  Did you manage to fix this?

**Comment by himanshu309** [comment]
Same problem with me . Any Help

**Comment by emilioicai** [comment]
@himanshu309 can you post your stack trace?

**Comment by jeromeheissler** [comment]
Same problem with https://github.com/necolas/react-native-web 
It's because of ViewPropTypes who was deprecated see https://github.com/necolas/react-native-web/pull/1557
I haven't found any solution for the moment
