### ISSUE TITLE
 Reason: image not found

### ISSUE THREAD

**Issue by cq920702** [airbnb/lottie-react-native#187]
When I run on IOS,I encountered this problem.   Library not loaded: @rpath/Lottie.framework/Lottie
  Referenced from: /var/containers/Bundle/Application/18C84068-8163-4862-8A80-8874DDABA14C/service.app/service
  Reason: image not found
I try several methods but does not work!How to solve this problem.Thanks

**Comment by cq920702** [comment]
Simulator is correct.Only on my virtual device meets this problem.
lottie-react-native:  2.2.0      
"react": "16.0.0-alpha.6",
"react-native": "0.43.4",

**Comment by cq920702** [comment]
Solved. add copy files ,add Lottie.framework and change Destination to Frameworks.

**Comment by luisfuertes** [comment]
What destination changed to frameworks? I have the same error. 

I have added to frameworks `lottie-ios` and add to "Linked Frameworks and Libraries": Lottie.framework for MAC OS and for iOS

And `react-native link lottie-react-native`.

But not works

**Comment by alexmassicott** [comment]
For anyone still having issue with this, I fixed it by add Lottie.framework to embedded binaries  in the General tab

**Comment by danielmartinprieto** [comment]
Hi, @alexmassicott. Where is Lottie.framework located? I linked both libraries using `react-native link` but I can't find the framework to add it to the embedded binaries list...

**Comment by alexmassicott** [comment]
@danielmartinprieto In xcode, in the general tab. Scroll down till you see embedded binaries, click the plus sign. You will see all the libraries in your project, if you linked Lottie, you should see the framework there.

**Comment by danielmartinprieto** [comment]
All right. It seems that react-native link didn’t work 😢

**Comment by alexmassicott** [comment]
@danielmartinprieto  Just install the Lottie packages manually, not with react-native link.

Go in the node modules, lottie-ios folder.
There will be a Lottie.xcodeproj, drag that into xcode into your your libraries folder.

The Lottie.framework is in there. Then add it to embedded binaries.

**Comment by export-mike** [comment]
Strange I followed the instructions as shown on http://airbnb.io/lottie/react-native/react-native.html I also had to add the lottie embedded binary
