### ISSUE TITLE
[IOS v2.2.0] LOTAnimationTransitionController.m:37:11: 'LOTAnimationTransitionController' cannot use 'super' because it is a root class

### ISSUE THREAD

**Issue by kyle-ssg** [airbnb/lottie-react-native#190]
Got this updating from 1.2.0 to 2.2.0
<img src="https://image.prntscr.com/image/tlkFWL9OR9W7RLIsyckVGw.png"/>

**Comment by joshmadewell** [comment]
I'm seeing this too @kyle-ssg have you figured out any workarounds? @gpeal are ya'll able to reproduce this?

**Comment by madsleejensen** [comment]
solved it by deleting `[project-path]/ios/build` and running `react-native run-ios` again, it caches previous builds here (and thereby maybe a previous version of the library) 

i could understand why doing a build from xcode worked fine, but run-ios didnt, apparently they store builds in different locations :)

**Comment by j-wang** [comment]
I'm getting this problem with building from Xcode itself, so not solved for me with @madsleejensen's solution, unfortunately.

**Comment by j-wang** [comment]
Also, I think this is a duplicate of #175

**Comment by gpeal** [comment]
I'm closing this to clean up old issues. Feel free to reopen if it's still an issue.
