### ISSUE TITLE
Lottie rendering of animation in json file not (fully) working, while HTML demo does

### ISSUE THREAD

**Issue by annabeast** [airbnb/lottie-react-native#191]
We've used the bodymovin plugin to export both a json file and an HTML demo of an animation. The Lottie rendering does not fully work (i.e. some moving components missing: the minion-like shape that's supposed to move around, blink its eyes and move its mouth only moves around - but no eye blinking or mouth moving!), while the HTML demo works perfectly. Thanks for your help!

**Comment by gregoireLem** [comment]
same issue here, the html demo works fine but I've got only the shape of my Lottie that is rendering on iOS & android

**Comment by gpeal** [comment]
@annabeast @gregoireLem The Lottie render on web/iOS/and Android are all separate codebases so there may be slightly feature differences. We have a list of supported features [here](http://airbnb.io/lottie/after-effects/supported-features.html). Feel free to attach an animation if you can't figure it out.
Also, test it on Android and iOS and post it on each repo for render specific issues.

**Comment by hmolotsi** [comment]
Please can you let me know why this animation that works in the Lottie preview doesn't work in the app?

[ujama-logo.json.zip](https://github.com/react-native-community/lottie-react-native/files/3217862/ujama-logo.json.zip)

**Comment by ouoru** [comment]
some features are not supported yet on Lottie, check out the troubleshooting section [here](http://airbnb.io/lottie/#/after-effects?id=troubleshooting). Also, if you are not the one creating the Lottie animations, make sure the creator uses the LottiePreview application on both iOS and android to double check if the animation is working.
