### ISSUE TITLE
Initial yarn add lottie-react-native command broke due to Electron dependency

### ISSUE THREAD

**Issue by PimDeWitte** [airbnb/lottie-react-native#195]
When i run 

``
yarn add lottie-react-native@2.2.0
``

The output contains the following warning:

``
warning electron@1.8.0: this beta version of electron has been removed due to a security vulnerability. To get the latest beta, run 'npm install electron@beta'
``

And then fails on:

``
Error: Failed to find Electron v1.8.0 for darwin-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-darwin-x64.zip
``

**Comment by PimDeWitte** [comment]
Running
``
npm i --save lottie-react-native@2.2.0
``

Works fine and lets you install it btw :-)

**Comment by gpeal** [comment]
@PimDeWitte Lottie has no electron dependencies. This must be coming from another package.
