### ISSUE TITLE
Failed react-native run-android

### ISSUE THREAD

**Issue by koansang** [airbnb/lottie-react-native#196]
Error message : 
![image](https://user-images.githubusercontent.com/12390185/30795334-047c2c38-a208-11e7-8eee-f85cc85f9882.png)

Updated 2.2.0 to 2.2.7.

What's problem?

**Comment by ajmalpkc** [comment]
1. Open the build.gradle file for your application.
2. Make sure that the repositories section includes a maven section with the "https://maven.google.com" endpoint. For example:
`allprojects {
    repositories {
        jcenter()
        maven {
            ...
            url "https://maven.google.com"
        }
    }
}`

**Comment by koansang** [comment]
@ajmalpkc thanks~!!
But other issues have occurred.
![image](https://user-images.githubusercontent.com/12390185/30797590-88bb0d58-a211-11e7-8342-67194ba658a6.png)

**Comment by kelset** [comment]
Having the same issue, had to rollback :/

**Comment by Monte9** [comment]
I saw this same issue. @ajmalpkc solution helped, but now I am seeing this error:
```node_modules/lottie-react-native/lib/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.```

` error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.`

**Comment by Monte9** [comment]
This commit seems to have caused the `json.toHashMap` error: https://github.com/airbnb/lottie-react-native/commit/9868a704d76869c1d96348d589ddc2d62168f768#diff-e8684bd1c488b49e4b2a3f075962c504

@gpeal is there some android version/dependency that we need to upgrade to for it to work?

**Comment by kelset** [comment]
I don't have either of those errors, but it may be because I'm using version 26 for both the SDK & build tools - if you feel adventurous you can try using my version of the `android/build.gradle` file:

```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
ext {
    compileSdkVersion = 26 // Or what version you want (latest is recommended)
    buildToolsVersion = '26.0.1' // same thing
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3+'
        classpath 'org.apache.httpcomponents:httpclient:4.5.2'
        classpath 'de.undercouch:gradle-download-task:3.1.2'
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

```

**Comment by ducpt2** [comment]
@kelset solution work for me.
Thanks.

**Comment by gpeal** [comment]
This is correct. The Android SDK was bumped from 25 to 26.

**Comment by eduardomoroni** [comment]
Hi Folks, Tried https://github.com/airbnb/lottie-react-native/issues/196#issuecomment-332126271 with no lucky.

[ android/app/build.gradle](https://github.com/CaronaBoard/caronaboard-native/pull/77/files#diff-dc46f9f5dfe204e394fb41395ccd03cf)
```
compileSdkVersion 26
buildToolsVersion "26.0.1"
```

[android/build.gradle](https://github.com/CaronaBoard/caronaboard-native/pull/77/files#diff-7ae5a9093507568eabbf35c3b0665732)
```
+ext {
+    compileSdkVersion = 26
+    buildToolsVersion = '26.0.1'
+}
+
+subprojects { subproject ->
+    afterEvaluate{
+        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
+            android {
+                compileSdkVersion rootProject.ext.compileSdkVersion
+                buildToolsVersion rootProject.ext.buildToolsVersion
+            }
+        }
+    }
+}

-        classpath 'com.android.tools.build:gradle:2.2.3'
+        classpath 'com.android.tools.build:gradle:2.3.3'
```

I also updated [gradle wrapper](https://github.com/CaronaBoard/caronaboard-native/pull/77/files#diff-8c020fe060099cf8b2a337de2c45efb8)

<img width="644" alt="image" src="https://user-images.githubusercontent.com/823150/31055397-95e69dc2-a698-11e7-8f4f-90b0ef5171dd.png">
Any advises?

**Comment by gpeal** [comment]
@eduardomoroni toHashMap was added in RN 0.46

**Comment by gpeal** [comment]
@Monte9 toHashMap was added in RN 0.46 so you'll need to be on at least 0.46.

**Comment by Monte9** [comment]
That might be it. I am still on RN 0.44. I will update to 0.46 and report back in a couple days.

**Comment by eduardomoroni** [comment]
@gpeal @Monte9, upgrading to 0.46 solved the issue. Thanks so much @gpeal !

**Comment by Monte9** [comment]
@kelset @gpeal thanks for your help! Upgraded to RN v0.46 & also used @kelset's suggestion of using `subprojects` and the animations now work on iOS & Android. 💯

**Comment by emeka-osuagwu** [comment]
@kelset thanks men it worked for me
