### ISSUE TITLE
Do we have to change the generated JSON file for it to work?

### ISSUE THREAD

**Issue by XBLDev** [airbnb/lottie-react-native#197]
[Nike_Logo.zip](https://github.com/airbnb/lottie-react-native/files/1331654/Nike_Logo.zip)
I have some JSON files that were generated with bodymovin, and I'm testing on phone right now, nothing works, even just the simplest animations.

From what I see, there are some obvious differences between the JSON files I got and the ones in the example folder here: https://github.com/airbnb/lottie-react-native/tree/master/example/animations: 

1. Some values in the JSON files in example folder are int while mine are float, for example the "fr" value in the example JSON files are all 30, while my generated JSON files have fr values of something like 29.05446534....., always float values. I remember back when I was just testing the ones in the example folder, I changed the fr value from 30 to a float value, and it stopped working. So I think it might be one of the reasons 

2. The order of the assets, layers, f, v, fr etc in my JSON files and the ones in example folder JSON file are different: in my generated files the order is always: v, fr, ip, op, w, h, nm, ddd, assets, layers, and in the JSON files in the example folder the order is always: assets, layers, v, ddd, ip, op, fr, w, h.

3. It seems that the ones in the example folder doesn't have anything in their assets, always just a "[]" with nothing in it, and mine do have stuff in it, not images, but some other stuff.

Is it true that I have to change the generated JSON file in order for it to work? If so what should I change? I've attached one of my files, can someone have a look at it? 

Thanks in advance for any answers!

**Comment by Minishlink** [comment]
You can use my module https://github.com/bamlab/easy-lottie-react-native that fixes several things (including the JSON). It's a module and not a PR to this repo because it doesn't support JSON that is loaded from the native side. (but if you think it's worth doing, let me know :) )

**Comment by XBLDev** [comment]
Hi @Minishlink thanks for your reply! I'll try it once I have time, it looks like it can also help adjust the size of the animation as well?

**Comment by Minishlink** [comment]
Yes, the size (and most importantly the aspect ratio) is set automatically from the info that is in the JSON.

**Comment by XBLDev** [comment]
Hi @Minishlink I just tried your module with my JSON file and also another JSON file I downloaded: https://www.lottiefiles.com/733-settings, both of them have assets, and when the app loads there's just plain white like before. What do you think could be the problem? It works with the sample JSON files perfectly.

**Comment by Minishlink** [comment]
I never use Lottiefiles with assets, but if you do, you have to put the assets on the native side, cf. https://github.com/airbnb/lottie-react-native/blob/master/docs/api.md#using-animations-with-assets

**Comment by XBLDev** [comment]
Hi @Minishlink, The assets in my JSON file has no image URL, instead it's got something like "ADBE Vector Group", and other stuff that I don't really understand since i'm not an AE expert. Do you think maybe when the JSON file is generated the assets file that are needed are also generated? I think that's the case for image assets: when you generate JSON file for AE animation that requires an image, the image is also generated in the process, in a separate folder.

**Comment by Minishlink** [comment]
Yes the assets are exported alongside the json.

**Comment by XBLDev** [comment]
Update 27/09/2017: i've been trying all sorts of JSON animations from the lottiefiles website and also my own JSON animation which is in the attachment, nothing seems to be working, I thought it was about the size of the animation, but changing the size doesn't seem to be helping.

**Comment by XBLDev** [comment]
Update 3/10/2017: 

I found out what was the problem: if you look into the file I attached, there's a section in it that begins with "masksProperties", animations plays after deleting that entire section, don't know why. 

Closing this issue for now.

**Comment by Minishlink** [comment]
Thanks for mentioning this! Masks may not be supported on android or ios.
