### ISSUE TITLE
Property 'cacheKey' not found on object of type 'LOTComposition'

### ISSUE THREAD

**Issue by mrkentlng** [airbnb/lottie-react-native#199]
i got issue like picture below here!
Please check :( 
<img width="261" alt="screen shot 2017-09-30 at 3 32 55 pm" src="https://user-images.githubusercontent.com/12961488/31044183-a8deb6f2-a5f4-11e7-8ba5-d3476d10fba2.png">

**Comment by devon** [comment]
```
react-native unlink lottie-ios
react-native link lottie-ios
react-native link lottie-react-native
```

It works for me.

**Comment by jozan** [comment]
Do the above steps to relink and also clean your Xcode project and if necessary restart Xcode.

**Comment by prscX** [comment]
Hi @jozan + @devon,

I have tried both the solutions but none of them is working. Please fine below my software stack:

- RN: 0.48.3
- lottie-react-native: 2.2.0
- xcode: 9.0

Its been 3 Hours now I am hanging around this issue, can you please help me to resolve this issue

**Comment by jozan** [comment]
You can regenerate ios directory by deleting it and running `react-native upgrade`. Remember to back it up before hamd fe. habing it committed to git repo. I don't know anything else you could do.

**Comment by eyeCU113** [comment]
This is one hell of a persistent error. How do we get more attention to the matter?!

**Comment by sospedra** [comment]
Every upgrade breaks with this error. And honestly dunno how to fix it. I don't even know what's wrong 😞

**Comment by alexlevy0** [comment]
react-native unlink lottie-ios
react-native unlink lottie-react-native
clean the build
clean the build folder
close XCode
remove node modules
reinstall node modules
relink the 2 lotties

**Comment by sospedra** [comment]
I still don't know what's wrong but I identify the origin of the problem (at least in my case): Moving too much between branches.

And one solution that, so far, worked every time:

```
rm -rf ios/build
rm -rf ~/Library/Developer/Xcode/DerivedData/*
```

**Comment by gpeal** [comment]
I'm not sure if this issue is Lottie specific. Feel free to reopen this if it is.
