### ISSUE TITLE
Error when enable Debug JS Remotely

### ISSUE THREAD

**Issue by tidusvn05** [airbnb/lottie-react-native#201]
I have added lottie to my project.
It very good run normally.
but when i enable Debug JS Remotely, application can't open and have a error in logcat. 

java.lang.NoSuchMethodError: No virtual method getOpenSourceSoftwareLicenseInfo(Landroid/content/Context;)Ljava/lang/String; in class Lcom/google/android/gms/common/GoogleApiAvailability; or its super classes (declaration of 'com.google.android.gms.common.GoogleApiAvailability' appears in /data/app/com.whatsnext-2/base.apk)

My implement:
- build.gradle
dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

- app/build.gradle
compileSdkVersion 26
    buildToolsVersion "26.0.2"

dependencies {
    compile project(':lottie-react-native')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.1.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-config')
    compile project(':react-native-device-info')
    compile project(':react-native-linear-gradient')
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:+'
    compile 'com.google.android.gms:play-services-maps:+'
}

- packages.jgon
"dependencies": {
    "eslint": "^3.9.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "2.2.3",
    "eslint-plugin-react": "^6.6.0",
    "eslint-plugin-react-native": "^2.0.0",
    "eslint-watch": "2.1.14",
    "lottie-react-native": "^2.2.7",
    "prop-types": "^15.6.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.4",
    "react-native-config": "^0.7.1",
    "react-native-device-info": "^0.11.0",
    "react-native-device-log": "^1.0.2",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-maps": "^0.16.4",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-async-await": "^1.0.1",
    "redux-thunk": "^2.2.0",
    "sha1": "^1.1.1"
  },

### I try downgrade version to 2.2.2, 1.2.2
but still same problem.

### If uninstall app to stop debug remote is it run normally.
because can't stop via menu (Command + M)

Thank You.

**Comment by ejkkan** [comment]
+1

  "dependencies": {
    "@mapbox/polyline": "0.2.0",
    "bugsnag-react-native": "2.3.2",
    "date-fns": "1.28.2",
    "lottie-react-native": "^2.2.7",
    "phone": "1.0.12",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.4",
    "react-native-actionsheet": "2.3.0",
    "react-native-appsflyer": "git://github.com/AppsFlyerSDK/react-native-appsflyer.git",
    "react-native-background-geolocation": "2.9.4",
    "react-native-country-picker-modal": "0.3.0-rc1",
    "react-native-credit-card-input": "0.3.3",
    "react-native-device-info": "0.11.0",
    "react-native-drawer": "2.3.0",
    "react-native-fbsdk": "git://github.com/facebook/react-native-fbsdk.git#065507aa1d2b8b0b6cb50d13117694123f8303fa",
    "react-native-fcm": "8.0.0",
    "react-native-google-analytics-bridge": "5.2.2",
    "react-native-image-crop-picker": "0.15.0",
    "react-native-image-zoom-viewer": "2.0.5",
    "react-native-linear-gradient": "2.2.0",
    "react-native-maps": "0.16.3",
    "react-native-navigation": "1.1.235",
    "react-native-parallax-view": "2.0.6",
    "react-native-permissions": "1.0.0",
    "react-native-prompt": "1.0.0",
    "react-native-scrollable-tab-view": "0.6.7",
    "react-native-swiper": "1.5.9",
    "react-native-vector-icons": "4.3.0",
    "react-redux": "5.0.5",
    "redux": "3.7.1",
    "redux-logger": "2.10.2",
    "redux-thunk": "2.2.0",
    "remote-redux-devtools": "0.5.12",
    "reselect": "3.0.1"
  },

**Comment by gpeal** [comment]
@tidusvn05 Can you upgrade your Google Play Service API library in the Android app?

**Comment by gpeal** [comment]
@tidusvn05 I actually don't think this should happen with the latest version of lottie-react-native and the play services library. Feel free to reopen if it's still an issue.
