### ISSUE TITLE
Could not find com.android.support:appcompat-v7:26.1.0.

### ISSUE THREAD

**Issue by starchand** [airbnb/lottie-react-native#203]
I'm trying to run React Native on android for first time in a while. I'm getting:

> A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':lottie-react-native'.
      > Could not resolve all dependencies for configuration ':lottie-react-native:_debugPublishCopy'.
         > Could not find com.android.support:appcompat-v7:26.1.0.
           Required by:
               QuickChinese:lottie-react-native:unspecified > com.airbnb.android:lottie:2.2.5

Any ideas how to fix this?

**Comment by MatthieuPeyrot** [comment]
+1

**Comment by malikoum94** [comment]
+1

**Comment by spearmootz** [comment]
in the android gradle file you need to specify the following

    compileSdkVersion 26
    buildToolsVersion "26.0.1"

and then find this text "  compile "com.android.support:appcompat-v7"
and make sure it says
    compile "com.android.support:appcompat-v7:26.0.1"

**Comment by MatthieuPeyrot** [comment]
I already have that on my build.gradle it does come from that.

**Comment by spearmootz** [comment]
you are right, there is also something else.

your other build.gradle file add maven url 'https://maven.google' should look like this

```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by MatthieuPeyrot** [comment]
i try that but now i have : 

Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzev.class

**Comment by starchand** [comment]
Fixed by @spearmootz maven url comment.

**Comment by yammt** [comment]
Hi @spearmootz 
There are more errors.

.../node_modules/lottie-react-native/lib/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java
Error:(86, 46) error: cannot find symbol method toHashMap()

Error:Execution failed for task ':lottie-react-native:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by anniewey** [comment]
@yammt make sure your project version is RN 0.46 or above as mentioned here -> https://github.com/airbnb/lottie-react-native/issues/196#issuecomment-333400864

**Comment by ftao123** [comment]
Maven  Configuration：
allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven{
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

**Comment by AniPrat** [comment]
![screenshot 9](https://user-images.githubusercontent.com/28390572/33714257-4da394c8-db74-11e7-880a-3f92b49ca8db.png)
![screenshot 10](https://user-images.githubusercontent.com/28390572/33714258-4de72d32-db74-11e7-9eef-9f51d782d1b9.png)
![screenshot 11](https://user-images.githubusercontent.com/28390572/33714259-4e59e854-db74-11e7-8e51-01044a8d0379.png)
Please Fix this anyone

**Comment by evbarnett** [comment]
+1

**Comment by LeeReindeer** [comment]
@spearmootz I try to add `google()` or `        maven {
            url 'https://maven.google.com'
        }` in my build.gradle.But it seem can't connect to it.

```
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:26.1.0.

Could not resolve com.android.support:appcompat-v7:26.1.0.
Required by:
    project :app
 > Could not resolve com.android.support:appcompat-v7:26.1.0.
    > Could not get resource 'https://maven.google.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
          > Could not GET 'https://maven.google.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
                   > Network is unreachable (connect failed)
```

**Comment by tiwa1** [comment]
+1

**Comment by uehaj** [comment]
+1

**Comment by gianpaj** [comment]
FYI this is full list of changes that need to be done to install on Android:
```diff
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 51d47a1..547c223 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -94,8 +94,8 @@ def enableSeparateBuildPerCPUArchitecture = false
 def enableProguardInReleaseBuilds = false

 android {
-    compileSdkVersion 23
-    buildToolsVersion "23.0.1"
+    compileSdkVersion 26
+    buildToolsVersion "26.0.1"

     defaultConfig {
         applicationId "com.myrn"
@@ -141,12 +141,13 @@ android {
 }

 dependencies {
+    compile project(':lottie-react-native')
     compile project(':react-native-fetch-blob')
     compile project(':react-native-image-crop-picker')
     compile project(':react-native-fast-image')
     compile project(':react-native-vector-icons')
     compile fileTree(dir: "libs", include: ["*.jar"])
-    compile "com.android.support:appcompat-v7:23.0.1"
+    compile "com.android.support:appcompat-v7:26.0.1"
     compile "com.facebook.react:react-native:+"  // From node_modules

     // androidTestCompile(project(path: ":detox", configuration: "newOkhttpDebug"), {
diff --git a/android/app/src/main/java/com/myrn/MainApplication.java b/android/app/src/main/java/com/myrn/MainApplication.java
index 9dab4fc..fe76efb 100644
--- a/android/app/src/main/java/com/myrn/MainApplication.java
+++ b/android/app/src/main/java/com/myrn/MainApplication.java
@@ -3,6 +3,7 @@ package com.myrn;
 import android.app.Application;

 import com.facebook.react.ReactApplication;
+import com.airbnb.android.react.lottie.LottiePackage;
 import com.RNFetchBlob.RNFetchBlobPackage;
 import com.reactnative.ivpusic.imagepicker.PickerPackage;
 import com.dylanvann.fastimage.FastImageViewPackage;
@@ -27,6 +28,7 @@ public class MainApplication extends Application implements ReactApplication {
     protected List<ReactPackage> getPackages() {
       return Arrays.<ReactPackage>asList(
           new MainReactPackage(),
+            new LottiePackage(),
             new RNFetchBlobPackage(),
             new PickerPackage(),
             new FastImageViewPackage(),
diff --git a/android/build.gradle b/android/build.gradle
index f3145dd..21d6181 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -20,6 +20,9 @@ allprojects {
         jcenter()
         maven { url "https://jitpack.io" }
         maven {
+            url 'https://maven.google.com'
+        }
+        maven {
             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
             url "$rootDir/../node_modules/react-native/android"
         }
diff --git a/android/settings.gradle b/android/settings.gradle
index b902d12..ea0b3b5 100644
--- a/android/settings.gradle
+++ b/android/settings.gradle
@@ -1,4 +1,6 @@
 rootProject.name = 'myRN'
+include ':lottie-react-native'
+project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')
 include ':react-native-fetch-blob'
 project(':react-native-fetch-blob').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fetch-blob/android')
 include ':react-native-image-crop-picker'
```

**Comment by alexsmartens** [comment]
I'm also having the same problem. No comment helps :'-(

**Comment by gianpaj** [comment]
@alexsmartens I think that's a different issue. try this
https://stackoverflow.com/a/45438018/728287
https://stackoverflow.com/questions/35158205/react-native-run-android-fail-on-appprocessdebugresources

if it's a Windows file system issue, I wouldn't know

**Comment by guysoulab** [comment]
SOUHEIL BEN SLIMANE : RESOLVED 
    // UI AIRBNB LOTTIE
    compile 'com.airbnb.android:lottie:2.0.0'

**Comment by kapil532** [comment]
![bugs](https://user-images.githubusercontent.com/3415327/40902654-5983ee90-67f2-11e8-99e7-50e73118420f.png)

**Comment by kapil532** [comment]
please help me, i am getting the above issues .

**Comment by zhangjunpeng** [comment]
Gays,I solved this problem.I do not add buildToolsVersion at android {} in buidl.gralde.So check your configuration and make sure your compileSdkVersion and buildToolsVersion keep same version

**Comment by sfm2222** [comment]
Put jcenter() after maven()

**Comment by leandrofp** [comment]
finally worked to me adding the following:

on android/build.gradle

repositories {
        mavenLocal()
        **maven {
            url 'https://maven.google.com'
        }**
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        jcenter()
    }

and on app/build.gradle

    **compileSdkVersion 26
    buildToolsVersion "26.0.1"**

    defaultConfig {
        applicationId "com.demolootie"
        minSdkVersion 16
        **targetSdkVersion 26**
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }


......
**compile "com.android.support:appcompat-v7:26.0.1"** //  same buildToolsVersion
**compile 'com.airbnb.android:lottie:2.3.1'**  //(your version of lottie)

**Comment by pouryash** [comment]
1

**Comment by Ej-leone** [comment]
> @gianpaj solution + adding the following to my root build.gradle did the trick for me (taken from [this related issue](https://github.com/rt2zz/react-native-contacts/issues/312))
> 
> ```
> subprojects {
>         afterEvaluate { project ->
>             if (project.hasProperty("android")) {
>                 android {
>                     compileSdkVersion 26
>                     buildToolsVersion '26.0.2'
>                 }
>             }
>         }
>     }
> ```
> 
> alternatively, i noticed a related problem with react native 0.56 and babel versions < 7, so by reverting my project back to 0.55 i was able to fix the problem

me too seems the issue is within gradle

**Comment by smwsk** [comment]
i resolve this problem, the problem due to gradle proxy ，you can change gradle.properties file. replace that content to
`systemProp.https.proxyPort=80
systemProp.http.proxyHost=mirrors.opencas.org`

**Comment by smwsk** [comment]
> @yammt make sure your project version is RN 0.46 or above as mentioned here -> [#196 (comment)](https://github.com/react-community/lottie-react-native/issues/196#issuecomment-333400864)
change gradle.properties file, the file in .gradle folder 
replace that content to
`systemProp.https.proxyPort=80` 
`systemProp.http.proxyHost=mirrors.opencas.org`

**Comment by smwsk** [comment]
> I'm trying to run React Native on android for first time in a while. I'm getting:
> 
> > A problem occurred configuring project ':app'.
> > Could not resolve all dependencies for configuration ':app:_debugApk'.
> > A problem occurred configuring project ':lottie-react-native'.
> > > Could not resolve all dependencies for configuration ':lottie-react-native:_debugPublishCopy'.
> > > Could not find com.android.support:appcompat-v7:26.1.0.
> > Required by:
> > QuickChinese:lottie-react-native:unspecified > com.airbnb.android:lottie:2.2.5
> 
> Any ideas how to fix this?

> @yammt make sure your project version is RN 0.46 or above as mentioned here -> [#196 (comment)](https://github.com/react-community/lottie-react-native/issues/196#issuecomment-333400864)
change gradle.properties file, the file in .gradle folder 
replace that content to
`systemProp.https.proxyPort=80` 
`systemProp.http.proxyHost=mirrors.opencas.org`
