### ISSUE TITLE
build failed after update

### ISSUE THREAD

**Issue by yotavm** [airbnb/lottie-react-native#204]
i update my lottie to the last version 
and after i link the new files 
my build failed and i get 
<img width="252" alt="screen shot 2017-10-05 at 0 47 45" src="https://user-images.githubusercontent.com/11390250/31201289-e151844a-a966-11e7-9d35-87a74f83d650.png">
```

1 Property 'sceneModel' not found on object of type 'LOTAnimationView *'
2 No visible @interface for 'LOTAnimationView' declares the selector 'setSceneModel:'
```

**Comment by mitch104** [comment]
@yotavm I have raised this issue with `lottie-ios` as that is where I believe the issue originates.

**Comment by kelset** [comment]
I had some issues too but relinking lottie fixed it

**Comment by mitch104** [comment]
@kelset that seems to have worked, thanks!

**Comment by spearmootz** [comment]
my build issue is a bit different, it builds when using xcode but not the react-native cli.

```CompileC projectFolder/ios/build/Build/Intermediates.noindex/Lottie.build/Debug-iphonesimulator/Lottie_iOS.build/Objects-normal/x86_64/LOTAnimatedControl.o lottie-ios/Classes/Private/LOTAnimatedControl.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by Leeds-eBooks** [comment]
I am seeing the same issue as @spearmootz. I don't fully understand what `run-ios` does differently to building with xcode, but this error comes as part of the following step:
```sh
=== BUILD TARGET Lottie_iOS OF PROJECT Lottie WITH CONFIGURATION Debug ===
```

It seems that building with xcode doesn't carry out this step, or not in the same way. Does anyone have any suggestions as to how I can proceed with this? Thanks!

**Comment by kytwb** [comment]
@spearmootz @Leeds-eBooks double check you have Lottie.framework in Embedded Binaries.

**Comment by Leeds-eBooks** [comment]
@kytwb Thanks, I do, I think it's configured correctly?

<img width="479" alt="screen shot 2017-10-17 at 10 57 56" src="https://user-images.githubusercontent.com/4380655/31658826-12168aae-b32a-11e7-9bf9-e3132c754565.png">

**Comment by kelset** [comment]
Original issue still happens with RN 0.49 - seems related to XCode tbh, it happened to me again today when I updated XCode from 9.0.0 to 9.0.1.

**Comment by bithavoc** [comment]
@kelset this happened to me again, after doing all the re-linking shit all I have to do is drop Lottie from embedded frameworks in my target:
<img width="949" alt="screen shot 2017-10-17 at 4 38 18 pm" src="https://user-images.githubusercontent.com/219289/31690881-ba1b4e9a-b359-11e7-9485-d562c02a1570.png">

**Comment by Leeds-eBooks** [comment]
@bithavoc Do you mean that removing Lottie from embedded frameworks fixes the issue for you? Doesn't that mean Lottie will no longer work?

**Comment by Leeds-eBooks** [comment]
I just managed to fix this issue for my project (maybe temporarily ¯\_(ツ)_/¯ )

The key steps, to add to @kelset's solution above, are:

- after @kelset's step 2, remove all references to lottie from `Embedded Frameworks` and `Linked Frameworks and Libraries`
- after @kelset's step 4, delete `/Users/<your_username>/Library/Developer/Xcode/DerivedData/<your_app_name>-<random_string>`

**Comment by bithavoc** [comment]
@Leeds-eBooks I should clarify that I'm using cocoapods so I remove it from Embedded Frameworks since the project already links with Pod_<target>.framework which already includes Lottie.

This is my cocoapod:
```
  pod 'lottie-ios', path: '../node_modules/lottie-ios'
  pod 'lottie-react-native', path: '../node_modules/lottie-react-native'
```

**Comment by RobPando** [comment]
still happens in rn@0.50 and lottie-react-native@2.2.7

**Comment by gpeal** [comment]
It seems like there are a few issues here that are likely related to react-native link/xcode/some combination of the two. If there are actionable items for lottie-react-native, please open a PR or a new issue to track it.

**Comment by kyle-ssg** [comment]
I've followed all these instructions attempting to upgrade and none of them work. I'm still getting 

Property 'sceneModel' not found on object of type 'LOTAnimationView *'
No visible @interface for 'LOTAnimationView' declares the selector 'setSceneModel:'

**Comment by kyle-ssg** [comment]
Received this for a project a year on the following did fix it for me this time:

```
# Remove previous build
rm -rf ios/build

# Remove cache build fragments
rm -rf ~/Library/Developer/Xcode/DerivedData/*
```
