### ISSUE TITLE
Android assets size not relative to Animation component

### ISSUE THREAD

**Issue by sospedra** [airbnb/lottie-react-native#205]
I notice that the aspect ratio and size are not the same between ios and Android. But nothing very extreme. Tho, today I tried an animation with assets and then the differences became strongly evident. 

I tried quite a lot of things: apply styles to Animation, different exports from bodymovin, etc. But nothing seems to work. Honestly, right now I don't know what else could I try.

Here's a snapshot showing the (si/e)mulators (blue box is the animation):

![image](https://user-images.githubusercontent.com/3116899/31275456-9072dbaa-aa97-11e7-81ac-0a00925a9473.png)

This is the React Native code:

```jsx
<View style={{ flex: 1 }}>
  <Animation
    ref={(node) => { this.animation = node }}
    source={require('./animations/coco.json')}
    imageAssetsFolder='lottie'
    style={{ flex: 1 }}
  />
</View>
```

PNG images are placed in `android/app/src/main/assets/lottie` for Android and linked inside `Resources` for iOS.

What's happening here? Why is rendering so different between platforms?
Thanks

**Comment by sospedra** [comment]
😞

**Comment by gpeal** [comment]
Try https://github.com/airbnb/lottie-react-native/commit/4c1bff110b735dbf16bef145d41fdb6274221490 with resizeMode="contain"

**Comment by gpeal** [comment]
I'll push an update soon

**Comment by Dimasprog** [comment]
Any solutions?
