### ISSUE TITLE
Loop animation property

### ISSUE THREAD

**Issue by eneskaya** [airbnb/lottie-react-native#21]
First of all: 👍 👍 👍 

Would be nice to have a convenient way of starting looped animations! So not only calling `play()` but also `loop()`

**Comment by lelandrichardson** [comment]
Great idea.

**Comment by eneskaya** [comment]
Nice, works great 👍

**Comment by femontanha** [comment]
@eneskaya do you know how I do a loop? I tried to add this `loop` property but doesn't work

```
<Animation
  source={ json }
  progress={ this.state.progress }
  loop={ true }
/>
```

**Comment by eneskaya** [comment]
@femontanha It only works with the imperative API, so be sure NOT to use `progress` prop. Instead do something like this:

```javascript
...

componentDidMount() {
    this.animation.start();
}

render() {
    <Animation
        source={json}
        style={{width: 100, height: 100}}
        ref={(animation) => this.animation = animation} // the ref to the LottieAnimation component 
        loop
    />
}

```

**Comment by xeroxoid** [comment]
@eneskaya can you please post the whole snippet. I cant seem to figure out how you referenced the animation.

**Comment by eneskaya** [comment]
@xeroxoid what do you mean, how I initialized the animation? (sorry for late reply)

**Comment by saddacracker** [comment]
Echoing @xeroxoid. I get a reference error when I use the imperative API.

`undefined is not an object (evaluating 'this.animation.start')`

**Comment by agrosner** [comment]
```
 <Animation
            loop
            source={source}
            ref={(animation) => animation.play()}
          />
```
This seems to work even better

**Comment by mjsisley** [comment]
Thoughts on allowing loop to take a number as an option?

For cases where you want the animation to loop some amount of times less than infinity.

**Comment by matthieupinte** [comment]
@agrosner is working but need to add a check (plz don’t ask me why ^^) :
```javascript
<Animation
  loop
  source={source}
  ref={animation => {
    if (animation) animation.play()
  }}
/>
```
