### ISSUE TITLE
No way to know when an animation is loaded

### ISSUE THREAD

**Issue by VincentFTS** [airbnb/lottie-react-native#210]
When a quite big animation is loaded with the Animation component, there’s no way to know when the component is "ready" to play the animation.
As a result, I get a countdown animation which displays nothing for more than a half second, a flashing '3', then '2', then '1'…
We should at least be able to get the ready information through a callback for exemple.
Ideally a preloading system would be great.

**Comment by gpeal** [comment]
@VincentFTS I think https://github.com/airbnb/lottie-react-native/commit/0064c3b55c92d84e8ccd5d710916ab9a64850d91 will fix your problem.
