### ISSUE TITLE
Possible error in Get started docs

### ISSUE THREAD

**Issue by sfratini** [airbnb/lottie-react-native#213]
I couldn't compile my project with the basic steps in the documentation. 

I had to add this in my settings.gradle since the link command was not doing it:

```
include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/lib/android')
```

and this in my build.gradle:

```
  //compile 'com.airbnb.android:lottie:2.2.5'
    compile project(':lottie-react-native')
```

Notice that the first commented line is the one in the docs that to me was not working. Second one worked. 

Just leaving it here in case there is something I am missing. 
Thanks

**Comment by gpeal** [comment]
@sfratini Thanks. I will update airbnb.io/lottie to reflect this.
