### ISSUE TITLE
Android doesn't scale

### ISSUE THREAD

**Issue by sospedra** [airbnb/lottie-react-native#214]
If we have an asset, say, with 1080x1920 dimensions. This will be the max size of the animation.
With ios we can scale using the style prop.

Shall we export from bodymovin ina different way?
Why isn't a `scale` prop for `lottie`. Becuase, for Android it not possible right now. And for ios is very easy to break the aspect ratio using `style`.

Hope someone answers this time 😞

**Comment by gpeal** [comment]
@sospedra Would https://github.com/airbnb/lottie-react-native/commit/4c1bff110b735dbf16bef145d41fdb6274221490 solve your problem?

**Comment by gpeal** [comment]
I think the above will solve this. Feel free to reopen if it doesn't.

**Comment by sospedra** [comment]
Sorry @gpeal I didn't find the time to try again.
I'll assume is correct and came back if don't ;)
Many thanks

**Comment by dvolland** [comment]
@peal This does not seem solved for me. As soon as I set the width or height larger than the screen dimensions in Android (which works perfectly fine on iOS),  the animation does not show up at all. I tried several `resizeMode` configurations – but this did not help.

The following works fine on iOS, but not on Android. Would be great if anybody has a hint.

```
import React from 'react'
import { Animated, Dimensions, ScrollView} from 'react-native'
import LottieView from 'lottie-react-native'

const {height, width} = Dimensions.get('window')
const sourceWidth = 1875 // the width of the animation
const sourceHeight = 10005 // the height of the animation

export default class App extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      progress: new Animated.Value(0)
    }
  }

  componentDidMount () {
    Animated.timing(this.state.progress, {
      toValue: 1,
      duration: 5000
    }).start()
  }

  render () {
    return (
      <ScrollView
        contentContainerStyle={{ width: width, height: width * sourceHeight / sourceWidth}}>
        <LottieView source={require('./data/AnimationNeuTest2.json')}
          style={{width: width, height: width * sourceHeight / sourceWidth}}
          // resizeMode='cover'
          imageAssetsFolder='lottie'
          progress={this.state.progress} />
      </ScrollView>
    )
  }
}
```

**Comment by sospedra** [comment]
This was exactly my problem back before

**Comment by gpeal** [comment]
@dvolland The sizes are dps on Android which means they'll be ~2.6x the number of pixels on an average Android device. If your animation is that large, Android will try and allocate a backing buffer that's 4800x30,000 pixels which is larger than it can and it will silently fail. It may log to logcat though so check that. can you make your animation smaller?

**Comment by dvolland** [comment]
Thanks @gpeal. It seems that indeed that the dimension were the problem. I reduced the size and it seems to be working fine on Android now.

**Comment by axelnormand** [comment]
I had this issue so made the animation smaller, then also had to do resize mode cover on android.

**Comment by lauraliism** [comment]
Yes, resizeMode='cover' fixed the size issue for me as well. 🎉

**Comment by araufdogan** [comment]
@lauraliism @gpeal When I use resizeMode cover, animation's resolution decreasing and looks blurry on android but there is no problem on ios. Do you have any idea?

**Comment by felansu** [comment]
@araufdogan same problem with resolution decreasing and looks blurry in version 3.4.0

**Comment by felansu** [comment]
@gpeal can reopen?

**Comment by sow1ch** [comment]
experiencing the same issue with blurry lottie view on Android

**Comment by paulik123** [comment]
I've found a solution. Increasing the size of the animation in the json file. 

```
{
    "v": "5.5.1",
    "fr": 60,
    "ip": 0,
    "op": 120,
    "w": 1000, // was 100 increased it 10x and now it looks good
    "h": 1000, // was 100 increased it 10x and now it looks good
    "nm": "barcode",
    "ddd": 0,
    "assets": [],
    "layers": [
........
```

**Comment by theneekz** [comment]
For iOS, provide `width` and `height` in the style obj. For android, add `flexGrow: 1` and `aspectRatio: width / height`(or in a way that does not mess up iOS). Good luck!

**Comment by Harukisatoh** [comment]
> For iOS, provide `width` and `height` in the style obj. For android, add `flexGrow: 1` and `aspectRatio: width / height`(or in a way that does not mess up iOS). Good luck!

That did worked for me, but I also had to make sure the lottie view had the same width and height as the device screen, and set the resizeMode as `cover`
