### ISSUE TITLE
Lottie doesn't play with imperative API when in a Modal

### ISSUE THREAD

**Issue by ay5000** [airbnb/lottie-react-native#215]
I have a lottie file that works great in a normal view, but when I try to add it to a Modal (https://github.com/maxs15/react-native-modalbox) it doesn't play at all. I just get a rendering of the first frame. How can I fix? I am using the imperative API.

**Comment by sfratini** [comment]
@ay5000 Please post your code. I had a similar issue and my problem was my reference to 'this' which was lost.

**Comment by ay5000** [comment]
export default class LottieView extends React.Component {
      componentDidMount() {
        this.animation.play();
      console.log("LOTTIE VIEW MOUNTED")
    }

    render() {

    return (
      <View style={this.props.style}>
        <Animation
          ref={animation => { this.animation = animation; }}
          loop 
          style={{
            width: '100%',
            height: '100%',
            backgroundColor:'transparent'
          }}
          source={'file.....'}
        />
      </View>
    );
    }
  }

So in console "LOTTIE VIEW MOUNTED" does print when the parent view renders (and the modal which holds the LottieView is off screen.

**Comment by sfratini** [comment]
Without looking at the Modal code, I would think that the modal is always loaded but hidden so basically the animation already played by the time you show the modal. 
Try replacing loop with loop={true} or playing the animation right after you open the modal. 

Note: I could never made loop worked, I always used a setInterval to keep the animation playing.

**Comment by ay5000** [comment]
@sfratini thanks for the tips. Can you show an example of how you're using setInterval? I think that may just be easier.

**Comment by sfratini** [comment]
Sure. So these are snippets of my EmptyComponent that shows when a list is empty:

```
constructor(props){
        super(props);
        this.state = {
            emptyProgress: new Animated.Value(0)
        };
    }


<Animation
                    style={this.getStyle(styles, ['emptyAnimation'])}  //This is a generic method that returns the merged style because I support Themes. 
                    source={this.getAnimationManager().getAnimationSource(empty.animation.id)} //I keep a dictionary of animations sources so I can change it from backend
                    progress={this.state.emptyProgress}
                    />



componentDidMount(){
        this.loadData();  //Just my function that loads the info
        this.startEmptyAnimation();     
    }

    startEmptyAnimation = () =>{
        this.timingAnimation();  // First we run the animation once because otherwise the animation does not start right away
        setInterval(this.timingAnimation, 2500);  //Restarts every 2.5 seconds
    }

    timingAnimation = () => {
        this.setState({emptyProgress: new Animated.Value(0)}, () => {
            Animated.timing(this.state.emptyProgress, {
                toValue: 1,
                duration: 1500,  //Duration of my animation
              }).start();
        });   
    }

```

**Comment by gpeal** [comment]
@ay5000 My guess is that this isn't Lottie specific. If you think there is something wrong with Lottie, you can reopen this

**Comment by aphillipo** [comment]
```javascript
  componentDidMount() {
   setTimeout(() => this.animation.play(), 100);
  }
```

Fixed things for me. This should really work with this though but I guess the modal mounts stuff before it fades in breaking things?

**Comment by anniewey** [comment]
Place the code in Modal body makes it works for me. 
PS: I'm using native Modal

**Comment by luqiuyuan** [comment]
It seems the bug is caused by that play() requires the root view in the native codes. However, the root view is detached by the react native Modal component.

The workaround is to call play() one frame later than componentDidMount()

`
componentDidMount() {
    Platform.OS === 'ios'? requestAnimationFrame(this.animation.play.bind(this.animation)) : this.animation.play();
  }
`
