### ISSUE TITLE
When using imperative API and loop, lottie flickers for a second between plays

### ISSUE THREAD

**Issue by ay5000** [airbnb/lottie-react-native#216]
I am using the imperative API and passed in the "loop" prop for my lottie to play continuously. However as soon as it's done the view flickers very briefly (1/2 second) before it restarts. 

Basically it will loop and keep playing but between each player a brief flicker. I have checked my lottie file and it loops just fine on other players.

Thanks.

**Comment by gpeal** [comment]
@ay5000 I can't repro this. It may be helped by https://github.com/airbnb/lottie-react-native/commit/0064c3b55c92d84e8ccd5d710916ab9a64850d91. If you can create a repro project and reopen if it's still an issue, that would be great.
