### ISSUE TITLE
Is this project still mantained?

### ISSUE THREAD

**Issue by sospedra** [airbnb/lottie-react-native#217]
Nobody is answering questions, request, etc.
Just minor irrelevant changes are being pushed recently

Is anyone in charge of this project? 😞

**Comment by dinzo** [comment]
@sospedra we are beginning to wonder the exact same thing!

**Comment by iroshanAV** [comment]
typical issue with RN and it's packages

**Comment by gpeal** [comment]
@sospedra @dinzo @iroshanAV. Yes, this is still being maintained. I'm sorry that most of my effort has been in moving the Android lib forward but I will try and be more responsive to issues here.

**Comment by sospedra** [comment]
@gpeal good to know
