### ISSUE TITLE
LRNAnimationViewManager doesn't implement requiresMainQueueSetup

### ISSUE THREAD

**Issue by AmyNgithub** [airbnb/lottie-react-native#222]
When running my app I get the following warning: 

`2017-11-07 12:22:12.736 [warn][tid:main][RCTModuleData.mm:69] Module LRNAnimationViewManager requires main queue setup since it overrides constantsToExport but doesn't implement requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`

I have understood that it has to do with iOS11 and I have seen several other modules which has had this issue and have solved it or are working on a solution. However I have not been able to find anything regarding  LRNAnimationViewManager. So I just wanted to raise the issue.

**Comment by Naoto-Ida** [comment]
I have a PR out #226 which will hopefully fix this.

**Comment by gpeal** [comment]
Fixed by #226
