### ISSUE TITLE
cannot find symbol view.setAnimation(new JSONObject(json.toHashMap()));

### ISSUE THREAD

**Issue by whysetiawan** [airbnb/lottie-react-native#227]
Hi guys,I have problems when i tried to build my Android Project using lottie.

```
:lottie-react-native:processReleaseManifest UP-TO-DATE
:lottie-react-native:processReleaseResources
:lottie-react-native:generateReleaseSources
:lottie-react-native:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:lottie-react-native:compileReleaseJavaWithJavac
:lottie-react-native:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/studio/Documents/React-Native/JASTIPAPP/node_modules/lottie-react-native/lib/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java:86: error: cannot find symbol
        view.setAnimation(new JSONObject(json.toHashMap()));
                                             ^
  symbol:   method toHashMap()
  location: variable json of type ReadableMap
1 error
:lottie-react-native:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lottie-react-native:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```

I got this errors, i have tried to use **react native 0.50.1 version**, **0.49.3** and **0.48.1** but still got same error. I tried to change the error above with comment, but i got more error in **MainApplication.java** and **MainActivity.java**

**package.json**

>`{
	"name": "JASTIPAPP",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"lottie-react-native": "2.2.6",
		"react": "16.0.0-alpha.12",
		"react-native": "0.48.1"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}`

**Comment by starchand** [comment]
+1

**Comment by gpeal** [comment]
@whysetiawan @starchand Can you attach a sample project that repros this? It shouldn't happen if you are on 0.46+

**Comment by gpeal** [comment]
Fixed by https://github.com/airbnb/lottie-react-native/commit/0064c3b55c92d84e8ccd5d710916ab9a64850d91

**Comment by patilrevansidh** [comment]
:+1:
