### ISSUE TITLE
Display issue (red cloud) when exported from After Effects with Bodymovin

### ISSUE THREAD

**Issue by dwmcc** [airbnb/lottie-react-native#229]
I'm having a bit of trouble using a JSON file in react-native that was exported from AE using the Bodymovin plugin. I exported it successfully using default settings, and when loaded back in to the bodymovin preview, it displays correctly.

Next, I imported the data.json file and the associated Images to xcode in the same directory, and instantiated the animation object. Using a file such as soda_loader.json works, so it leads me to believe that lottie is not recognizing my data.json correctly. I'm attaching a video of the loading screen -- you can see that some of the objects are faintly visible but surrounded by (for lack of a better explanation), a red cloud.

I've read through the issues here, and tried things like changing the FPS values in the data.json to full integers, etc, but nothing will make the cloud disappear. I'm sure it's something simple that I've overlooked, so if you can point me in the right direction that would be much appreciated.

data.json: [https://pastebin.com/3qKF6Pvq](https://pastebin.com/3qKF6Pvq)
video: [https://streamable.com/domc3](https://streamable.com/domc3)

I'm assuming it has to do with the export process, but it's curious that the bodymovin preview displays as expected but it does not in lottie-react-native.
Thank you for your time.

**Comment by gpeal** [comment]
@dwmcc Why are there images in your lottie animation? Is that expected?

**Comment by gpeal** [comment]
@dwmcc Can you also file the issue on lottie-android and or lottie-ios if it's a rendering issue?
