### ISSUE TITLE
Couldn't find preset "airbnb" relative to directory

### ISSUE THREAD

**Issue by farid-neopixe** [airbnb/lottie-react-native#23]
hello guys , 

firstly i wanna thank you for the amazing library , the problem is when i tried to use it it shows me this error and i can't figure out where the problem is !
![simulator screen shot 2 feb 2017 14 41 19](https://cloud.githubusercontent.com/assets/20015003/22553736/b551f284-e955-11e6-8638-e623bc8ea676.png)

**Comment by AlexDM0** [comment]
Hi, I had this too! Turns out I had to add babel-preset-airbnb to my package.json in the dependencies and rerun npm install.

Cheers

**Comment by nextriot** [comment]
I'm also getting this exact error, tried @AlexDM0 fix, but didn't resolve it for me. Any other suggestions for this one?

**Comment by AlexDM0** [comment]
So you have babel-presets-airbnb in your node_modules folder? Odd, that should fix it...

**Comment by nextriot** [comment]
Sadly so, and sadly for me - no go :(
<img width="723" alt="screen shot 2017-02-02 at 2 03 26 pm" src="https://cloud.githubusercontent.com/assets/711457/22557082/79e21062-e950-11e6-98ef-005a9e906a6c.png">

**Comment by nextriot** [comment]
Perhaps I'm missing a step here, do I need to install the Lottie iOS project separately? All I've followed are the instructions for getting up and running using React Native.

**Comment by jhen0409** [comment]
A better way is remove `.babelrc` in [deline](https://github.com/airbnb/deline) (Ignore at publish), it looks unnecessary in a npm package.

**Comment by AlexDM0** [comment]
@nextriot Yes, for me it was necessary. Take a look at #19. It seems to have issues with RN 0.40 though (#24).

**Comment by nextriot** [comment]
Tried removing `.babelrc` also to no resolve. And as far as the link to issue 19, all of those steps are already produced correctly, nothing to change there. I'll report back if there's a fix at any point.

**Comment by ljharb** [comment]
See https://github.com/airbnb/deline/pull/6#issuecomment-277010054.

.babelrc is both necessary, and in many npm packages. This flaw in the RNP should be worked around with a postinstall script in your app that removes all babelrc files in node_modules, not making PRs to the thousands of packages in the ecosystem that publish a babelrc file.

**Comment by janicduplessis** [comment]
@ljharb I'll bring this up to the RNP team, in the meantime could we either fix deline or remove this dep (it's used once).

As far as I'm concerned this is the only package out of thousands that cause this issue as most of them that had this issue were fixed by not publishing .babelrc when RNP started having this behavior.

**Comment by ljharb** [comment]
@janicduplessis i already have: https://github.com/facebook/react-native/issues/10966

**Comment by janicduplessis** [comment]
The current behavior of RNP is more or less like the `raw` case of your proposal (runs babel while considering .babelrc). In that case would it makes sense to move babel-preset-airbnb to deps instead of dev deps so it is installed, knowing it will be used since .babelrc is published?

**Comment by ljharb** [comment]
In the world where RNP handles that behavior, they'd have to install the dev deps of all the packages as well - it wouldn't be a dev dep for normal usage.

**Comment by farid-neopixe** [comment]
adding this line "babel-preset-airbnb": "^2.1.1" to my dependencies in my package.json worked out for me but when i tried to run an animation nothing appears at all!

**Comment by farid-neopixe** [comment]
from what i've seen , a lot of folks been having the same build failure as me ! here's a screenshot of the error 
![screen shot 2017-02-02 at 17 56 36](https://cloud.githubusercontent.com/assets/20015003/22561839/fe6e2322-e971-11e6-84e8-3725f0540bf0.png)

**Comment by dhwrwmgwra** [comment]
![screen shot 2017-02-02 at 11 39 49 pm](https://cloud.githubusercontent.com/assets/17001301/22562048/ec742994-e9a0-11e6-8b7f-9b7301acb291.png)
Same here

**Comment by lelandrichardson** [comment]
@farid-neopixe @dhwrwmgwra This is related to #12. Please move discussion of those errors to that issue thread. (Will try and fix ASAP).

**Comment by janicduplessis** [comment]
I would still like to figure out a solution that doesn't make everyone have to install an extra dep or add a postinstall script Since changes to RN packager to properly handle .babelrc files are still far off.

Some ideas:
- remove deline
- add babel-preset-airbnb to lottie-react-native deps
- document that you have to also install babel-preset-airbnb in lotties installation docs (less ideal)
- dont publish .babelrc in deline (at least temporarly)

**Comment by zeljkoX** [comment]
Add this to postinstall hook
 (find node_modules -type f -name .babelrc | grep -v /react-native/ | xargs rm) || true

As noted in https://github.com/airbnb/react-with-styles/issues/30 thread.

**Comment by ljharb** [comment]
I think documenting the postinstall script is the best approach.
