### ISSUE TITLE
Error:(86, 46) error: cannot find symbol method toHashMap()

### ISSUE THREAD

**Issue by starchand** [airbnb/lottie-react-native#230]
I took a whole 2 weeks off developing my RN project, and in typical RN fashion everything has broken on my return... 

Building in android is giving me:
view.setAnimation(new JSONObject(json.toHashMap()));

I'm running RN 0.48.

Any ideas?

**Comment by gpeal** [comment]
@starchand Are you sure you're on RN 0.48? That method was added in 0.46
https://github.com/facebook/react-native/commit/fe229f810475e90f7438c1b4b611b37953937782

**Comment by starchand** [comment]
Below fixed the issue.

```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```
