### ISSUE TITLE
Android build error.

### ISSUE THREAD

**Issue by koansang** [airbnb/lottie-react-native#236]
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :lottie-react-native.
```
setting.gradle
```
include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/lib/android')
```

app/build.gradle
```
compile project(':lottie-react-native')
```

What's problem?

**Comment by kelset** [comment]
Same issue here.
Updated to `2.3.0` and I get this error. By investigating I think it's related to updating to newer versions of gradle and the way `lottie` is configured:
* [SO-1](https://stackoverflow.com/questions/44218614/gradle-4-0-unable-to-find-a-matching-configuration)
* [SO-2](https://stackoverflow.com/questions/44242945/android-studio-3-gradle-4-0-shrinkresources-libraryproject-unable-to-fin) that leads to [SO-3](https://stackoverflow.com/questions/46038945/gradle-plugin-3-0-0-beta-4-buildtypematching-has-been-removed-use-buildtypes/46038946#46038946)
* [SO-4](https://stackoverflow.com/questions/45679847/android-studio-3-0-compile-issue-cannot-choose-between-configurations)

And I finally found out in the docs where it speaks about [this issue](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#variant_aware).

Also, by running `./gradlew assembleDebug --info` a weird thing happens: for lottie no configurations get created:

```sh
> Configure project :lottie-react-native
Evaluating project ':lottie-react-native' using build file '/Users/kelset/Developer/ETV/the-week-react/node_modules/lottie-react-native/lib/android/build.gradle'.

> Configure project :react-native-device-info
Evaluating project ':react-native-device-info' using build file '/Users/kelset/Developer/ETV/the-week-react/node_modules/react-native-device-info/android/build.gradle'.
Creating configuration androidTestUtil
```

So my guess is that `lottie-react-native/lib/android/build.gradle` is missconfigured. But can't really understand how to fix.
Hopefully it's an easy one @gpeal

**Comment by gpeal** [comment]
Replace `/lib/` with `/src/`

**Comment by tommeier** [comment]
@gpeal where do I update the http://airbnb.io/lottie/react-native/react-native.html#getting-started section? The manual steps still show `/lib/`

**Comment by oximer** [comment]
https://github.com/airbnb/lottie/pull/22

**Comment by oximer** [comment]
On my project I had to replace lib to src and rename the project include to 'lottie''

`include ':lottie'
project(':lottie').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')`

instead of

`include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/lib/android')`

As consequence, I use 

`compile project(path: ':lottie')`

instead of

`    compile project(path: ':lottie-react-native')`

**Comment by alexsmartens** [comment]
hi @oximer,

I initially had the same error as @koansang described. I followed the steps you proposed and got a different error:

```
Error: Cannot create directory D:\myPATH\myApp\node_modules\lottie-react-native\src\android\build\intermediates\incremental\mergeReleaseResources\merged.dir\values
:lottie:mergeReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lottie:mergeReleaseResources'.
> Error: Cannot create directory D:\myPATH\myApp\node_modules\lottie-react-native\src\android\build\intermediates\incremental\mergeReleaseResources\merged.dir\values

```

Would you have any suggestions?

**Comment by razvanilin** [comment]
Just in case people still encounter this issue, make sure you include `lottie` only one time in `settings.gradle`. My `react-native link` script screwed things up for me and I was getting this error because I was including `lottie-react-native` twice
