### ISSUE TITLE
Animation not showing getting warning "request key of value that is not an object"

### ISSUE THREAD

**Issue by ranvirgorai** [airbnb/lottie-react-native#238]
i am passing json from [https://www.lottiefiles.com/storage/datafiles/pzeBT0Z8PdakKewas2M8Q8mkb8PMP6CjJYxtvbsG/loop.json](url)

**Comment by gpeal** [comment]
There isn't enough information to debug here. It's possible that this warning doesn't come from lottie as well. If you could add more repro steps, please reopen.

**Comment by dasblitz** [comment]
I got the same error when I left out the style attribute with a width and height on the Lottie component:

This works:

```
<Lottie
  style={{
    width: 50,
    height: 50
  }}
  loop
  source={LottieAnimation}
  ref={ref => { this.animation = ref }}
/>
```

This doesn't:

```
<Lottie
  loop
  source={LottieAnimation}
  ref={ref => { this.animation = ref }}
/>
``` 

![schermafbeelding 2018-02-22 om 10 25 43](https://user-images.githubusercontent.com/6230374/36530251-e1368e02-17ba-11e8-8710-68f27e89269d.png)

**Comment by andrscrrn** [comment]
This seems to be related to specific assets.
