### ISSUE TITLE
Unrecognized platform name iOS

### ISSUE THREAD

**Issue by RyanMitchellWilson** [airbnb/lottie-react-native#239]
I am using lottie-react-native version 2.2.7 and have been for over a month with no problems, but a couple days ago a new version of lottie-ios (2.1.4) was release which is now being pulled in by lottie-react-native because there is a dependency on `lottie-ios: "^2.1.3"`. This latest version of lottie-ios has a breaking change in the LOTAnimatedSwitch.m file here https://github.com/airbnb/lottie-ios/blob/2.1.4/lottie-ios/Classes/Private/LOTAnimatedSwitch.m#L152 
This is causing the build to fail due to the error: `Unrecognized platform name iOS`
This happens because the syntax used in the new version of lottie-ios is only supported with xcode 9 and Swift 4, and since xcode 9 is essentially unusable at this time, I cannot update to it. Can this please get fixed?

**Comment by RyanMitchellWilson** [comment]
I've got a workaround for now, if you add `"lottie-ios": "2.1.3"` to your package.json, that will cause npm to install the version you specified other than the version that lottie-react-native wants.

**Comment by gpeal** [comment]
Just released 2.3.1 Should fix it.
