### ISSUE TITLE
Update header paths for React Native 0.40

### ISSUE THREAD

**Issue by MyGuySi** [airbnb/lottie-react-native#24]
It would be great it React file headers paths could be updated to work with RN 0.40

I tried to do it myself but just got a bunch more errors so probably worth someone who actually knows what they're doing taking a look:

<img width="344" alt="screen shot 2017-02-02 at 15 25 34" src="https://cloud.githubusercontent.com/assets/12952977/22555542/ead066ec-e95b-11e6-8599-50f1636c815f.png">

**Comment by MyGuySi** [comment]
Sorry, I didn't notice the other issue related to 0.40. Feel free to close this if you'd like as it's the newer issue

**Comment by lelandrichardson** [comment]
Thanks. Closing and continuing to track this in #12
