### ISSUE TITLE
[SOLVED] Project won't compile with 'Configuration for name 'default' not found

### ISSUE THREAD

**Issue by sfratini** [airbnb/lottie-react-native#241]
I just realized that the Android gradle has changed folders and is now in the src folder. This was breaking my build. Just replace your settings.gradle with this:

project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')

It was /lib/ before. The docs should be updated.

**Comment by YufJi** [comment]
thanks !!!!

**Comment by chenjinya** [comment]
Thanks
