### ISSUE TITLE
Animation inside wordpress is not smooth in chrome

### ISSUE THREAD

**Issue by nowwwmad** [airbnb/lottie-react-native#244]
Hi there !

First huge thanks for the good job.
It's so cool to play with your script :-)
I'm not a developer, so i'm not sure that it's a script issue but maybe someone experienced the same problem and could guide me :-)

On the WIP [home page of my site](http://hasenfratz.fr/) i have a logo animation that run really well on firefox but seems to be slower in chrome.
The strange think is that it work well on chrome with the [same code using codepen](https://codepen.io/nowmad/full/POLOLo/).

Do you know what could cause this issue ?

Thank's to give "a code newbie" the ability to play with animations :-)

**Comment by gpeal** [comment]
@nowwwmad Glad you like Lottie :) This repo is for mobile apps. Please file this on https://github.com/airbnb/lottie-web
