### ISSUE TITLE
Have you any way or alternative to create the JSON easier?

### ISSUE THREAD

**Issue by dflourusso** [airbnb/lottie-react-native#245]
Can i create it without After effects dependency for example. How to make it?

**Comment by gpeal** [comment]
[Haiku](https://medium.com/haiku-blog/lottie-without-after-effects-9c5a8e74c239) is working on it but it's still very early.

**Comment by gpeal** [comment]
@dflourusso [proto.io](https://proto.io/en/new-features/bodymovin/) just happened to release this today actually.
