### ISSUE TITLE
is there a way to use Android SDK lower then 26?

### ISSUE THREAD

**Issue by Mactub07** [airbnb/lottie-react-native#247]
I have modules which work on Android SDK < 26 , and I want to make work Lottie and this module? could you help me?

**Comment by Noitidart** [comment]
I think we only set compileVersion to 26 is this correct?

    compileSdkVersion 26 // <-- update this to 26

And that lottie should work in all Android versions when released to production. API 26 only needed for compiling. I think. Is this correct?

**Comment by gpeal** [comment]
That is correct. minSdk is the only thing you have to worry about. This should work all the way down to 14.

**Comment by Noitidart** [comment]
Thanks @gpeal that is great news that this works down to 14 in production build! :)
