### ISSUE TITLE
Nothing shows up on iOS Simulator, easy to reproduce

### ISSUE THREAD

**Issue by markzero** [airbnb/lottie-react-native#248]
I'd like to add Lottie to my project for loaders and other neat stuff but unfortunately can't do it at the moment. I'm new to this so didn't try versions below 2.2.7. Didn't try on Android though.

Steps to reproduce: 

**1.** 
Go to: https://facebook.github.io/react-native/docs/getting-started.html
Step: `Building Projects with Native Code`
Run: `npm install -g react-native-cli`
Run: `react-native init LottieTest`
Run: `cd LottieTest`

**2.**
Go to: http://airbnb.io/lottie/react-native/react-native.html
Run: `yarn add lottie-react-native@2.2.7`
Run: `react-native link lottie-ios`
Run: `react-native link lottie-react-native`
Also added `Lottie.framework` to `Embedded Binaries`.

Next run: `yarn start` and `react-native run-ios`.

Added both examples from [the page](http://airbnb.io/lottie/react-native/react-native.html) but with both I only have this:

![image](https://user-images.githubusercontent.com/170480/33808953-04e3f0e8-ddef-11e7-96e0-9b6455bc2826.png)

App is very simple:

![image](https://user-images.githubusercontent.com/170480/33808968-48c5da7e-ddef-11e7-934f-08de3ab1e403.png)

With basic component:

![image](https://user-images.githubusercontent.com/170480/33808973-5fb3ced0-ddef-11e7-840e-3776f41585ad.png)

I also tried `source={anim}`.

This (test) project structure is just like this:

![image](https://user-images.githubusercontent.com/170480/33808980-7dca6924-ddef-11e7-9741-a1e32bc70af9.png)

Also tried using [imperative API](http://airbnb.io/lottie/react-native/react-native.html#getting-started) as a basic component but same results.

Anything else I'm missing?

**Comment by gpeal** [comment]
@markzero Can you try 2.3.1?

**Comment by markzero** [comment]
@gpeal it seems it's getting somewhere, now I have this error, basically which ever file I get from lottiefiles.com:

![image](https://user-images.githubusercontent.com/170480/33809829-4af2ad1e-ddfd-11e7-8095-f22a07a2cd6d.png)

Seems JSON files are missing something or badly formed?

**Comment by jeffsteinmetz** [comment]
If this is helpful, we can reproduce the same issue.
Worked with `"lottie-react-native" : "2.2.7"`
Error with  `"lottie-react-native" : "2.3.1"`

![image](https://user-images.githubusercontent.com/5488059/34074972-b332a8f0-e26e-11e7-9524-19d975e19a5f.png)


```

**Comment by markzero** [comment]
I use both codes from [getting started](http://airbnb.io/lottie/react-native/react-native.html#getting-started) and it works for versions 2.3.0 and 2.3.1, but only when NOT using `style` property on `LottieView` component.
