### ISSUE TITLE
Build error in newest v2.3.1

### ISSUE THREAD

**Issue by SimenFjellstad** [airbnb/lottie-react-native#249]
We are having issues getting any project with v2.3.1 building on android (haven't tested iOS). Everything works great when rolling back to 2.3.0. Nothing we did in gradle config or re-linking the library seemed to do anything.

The error we're facing when running react-native run-android is as following:
```
Error:Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :lottie-react-native.
     Required by:
         project :app
      > Unable to find a matching configuration of project :lottie-react-native: None of the consumable configurations have attributes.
```

Replacing the folder pointer to src as suggested by #241 & #246 didn't help either.

**Comment by SimenFjellstad** [comment]
Uhm, have no idea how or what i did, but somehow installing 2.3.0, removing it, and re-installing 2.3.1 seemed to work. Closing issue as this may have been user-error

**Comment by SimenFjellstad** [comment]
This issue just came back without us touching  any of the native code, so reason it worked installing 2.3.0 and then 2.3.1 may have been some sort of caching issue.

**Comment by gpeal** [comment]
@SimenFjellstad The only difference between 2.3.0 and 2.3.1 is that I bumped the native library versions. This may have to do with your build config trying to lottie-android 2.3.0 instead of 2.3.0
