### ISSUE TITLE
Issues with Building

### ISSUE THREAD

**Issue by indivisable** [airbnb/lottie-react-native#25]
Tried installing via:

```
yarn add lottie-react-native
react-native link lottie-react-native
```

Fixed the header paths (See: https://github.com/airbnb/lottie-react-native/issues/12) but then got error saying it could not find the lottie headers.

So I tried to install via CocoaPods but got this error:

`pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'`

![image](https://cloud.githubusercontent.com/assets/22860891/22559102/b4f0ec84-e935-11e6-8e31-be9525c1b0c6.png)

`/Users/...LottieReactNative/LottieAnimationViewManager.m:40:37: Incompatible block pointer types sending 'void (^)(RCTUIManager *__strong, NSDictionary<NSNumber *,UIView *> *__strong)' to parameter of type 'RCTViewManagerUIBlock' (aka 'void (^)(RCTUIManager *__strong, RCTSparseArray *__strong)')`

Maybe some conflict with React/RN versions, I saw the Cocoa Pod installs react which seems kind of odd.
![image](https://cloud.githubusercontent.com/assets/22860891/22559462/c74788a6-e936-11e6-80ba-d1c1f0082c22.png)

I am using:

```
"react": "15.3.2",
"react-native": "0.36.0",
```

Any ideas? It seems the building for this project still needs some work, but its worth it 👍 

**Update -** Want to clarify, I was able to build the example fine (however some of the animations did not play) but when I try to integrate into existing project is where the errors above occur.

**Comment by grifotv** [comment]
Had the exact same problem - examples worked fine but had this issue when trying to integrate into an existing project.

**Comment by lelandrichardson** [comment]
@indivisable thanks for the detailed error report. The version of React that it's installing looks very off. It looks like this is because it is getting the React pod from the cocoapods specs repo, rather than in your node_modules (0.11.0 was the last RN version published to the main specs repo). I'll try and figure out what the right fix for this is. Sorry!

**Comment by srshah19** [comment]
Had a similar issue while building for android. Hope this helps. 
![screen shot 2017-02-02 at 15 56 10](https://cloud.githubusercontent.com/assets/1692626/22573896/2e6dc166-e960-11e6-9629-68982a79aae6.png)

**Comment by indivisable** [comment]
@lelandrichardson 

I still get this error:

![image](https://cloud.githubusercontent.com/assets/22860891/22580187/d17bec9e-e99b-11e6-8760-c722de59ffaa.png)
