### ISSUE TITLE
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:26.1.0.

### ISSUE THREAD

**Issue by TBoyLi** [airbnb/lottie-react-native#253]
i get one error :
`Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:26.1.0.

Could not resolve com.android.support:appcompat-v7:26.1.0.
Required by:
    project :app
 > Could not resolve com.android.support:appcompat-v7:26.1.0.
    > Could not get resource 'https://maven.google.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
          > Could not HEAD 'https://maven.google.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom'.
                   > Remote host closed connection during handshake
                               > SSL peer shut down incorrectly`

This is the configuration of the build.gradle file in my app directory
`android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "com.lottieexample"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
    compile project(':lottie-react-native')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:support-annotations:26.1.0'
    // From node_modules
    compile 'com.facebook.react:react-native:+'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}`

**Comment by gpeal** [comment]
Lottie uses support lib 27 which you should upgrade to anyway. If, for some reason you can't, add this:
```
compile project(':lottie-react-native') {
        exclude group: 'com.android.support'
}
```

**Comment by alexsmartens** [comment]
@gpeal, this does not solve the problem. New Error:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\myPATH\myApp\android\app\build.gradle' line: 147

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method exclude() for arguments [{group=com.android.support}] on project ':lottie-react-native' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.274 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by azazrehman** [comment]
If you are using **Proxy** at any time in your Studio try to remove those proxy.
C->User->(User Name)->.gradle->gradle file.
Edit this file and remove proxies.

**Comment by MrSuntb** [comment]
azazrehman , your suggest is very useful  for me.

**Comment by Hu-Wentao** [comment]
If you are using Proxy at any time in your Studio try to remove those proxy.
C->User->(User Name)->.gradle->gradle file.
Edit this file and remove proxies.


azazrehman , your suggest is very useful for me.

**Comment by DongjinLiu** [comment]
> If you are using **Proxy** at any time in your Studio try to remove those proxy.
> C->User->(User Name)->.gradle->gradle file.
> Edit this file and remove proxies.

useful to me ,thanks

**Comment by rachanb** [comment]
@azazrehman your solution worked for me as well. thanks!

**Comment by MohammadHammoud** [comment]
use
implementation 'com.github.chrisbanes:PhotoView:2.3.0'
and add these two in build.gradle of your project
maven { url "https://jitpack.io" }
maven { url "https://maven.google.com" }
