### ISSUE TITLE
[Android] Overlapping shapes with opacity keyframe fades have an artifact where overlapped

### ISSUE THREAD

**Issue by jeffsteinmetz** [airbnb/lottie-react-native#255]
Works on iOS
opacity fades show overlap on Android
(ignore the gradient background in this screen capture, the test was the overlapping circles)
<img width="264" alt="android_emulator_-_nexus_5_api_26_5554" src="https://user-images.githubusercontent.com/5488059/34169743-3aef4d7c-e49d-11e7-9f38-5b3ccae75f15.png">

Attaching .json and After Effects

[fade-animation-example.zip](https://github.com/airbnb/lottie-react-native/files/1572584/fade-animation-example.zip)

**Comment by jeffsteinmetz** [comment]
moved to 
https://github.com/airbnb/lottie-android/issues/606

**Comment by losh11** [comment]
In lottie-android this was fixed with the new option `setApplyingOpacityToLayersEnabled`. It seems that lottie-react-native doesn't have such an option?

**Comment by zsombor-somogyi** [comment]
> In lottie-android this was fixed with the new option `setApplyingOpacityToLayersEnabled`. It seems that lottie-react-native doesn't have such an option?

Well, yeah, `lottie-android` introduced `applyOpacityToLayers` property in v6.6.0 but `lottie-react-native` with its latest (v7.2.2) version is still using the v6.5.2
