### ISSUE TITLE
Animation works on iOS but looks strange on Android

### ISSUE THREAD

**Issue by dustynl** [airbnb/lottie-react-native#264]
Hi,
This animation (attached)  
[coffeanim.zip](https://github.com/airbnb/lottie-react-native/files/1616125/coffeanim.zip)

works perfectly on iOS, but behaves really strangle on Android.
Could you guys possibly give us an idea as to why?

Kind Regards,
Dustyn

**Comment by gpeal** [comment]
Closing in favor of https://github.com/airbnb/lottie-android/issues/587
