### ISSUE TITLE
"Unable to load script from assets 'index.android.bundle'..."

### ISSUE THREAD

**Issue by kpolley** [airbnb/lottie-react-native#269]
When I follow the instructions [here](http://airbnb.io/lottie/react-native/react-native.html#getting-started) for Android, I immediately receive the error "unable to load script from assets 'index.android.bundle' as shown in the screenshot. I have refreshed my project and followed the instructions closely several times. My project runs fine until I try to link Lottie. Any idea why I am getting this error?

![screenshot_1516491511](https://user-images.githubusercontent.com/13952270/35189113-fd583f76-fdf8-11e7-937e-b03d8bd13a37.png)

**Comment by bluesea** [comment]
The name in the "package.json" is wrong. Change it into: "name": "example"

**Comment by deva11** [comment]
Do this For the first Time in your project root folder
Step 1 : 
`mkdir android/app/src/main/assets`

Step 2: 
```
$ react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main
/assets/index.android.bundle --assets-dest android/app/src/main/res
```

Step 3 : 
`react-native run-android`

From next time on wards, need to follow the Step 2 in order to update the bundle before you run on device.

**Comment by VKGraphics** [comment]
same error give me solution ?

**Comment by Bimantoro** [comment]
just edit "package.json" file, and add this code
`"android-linux": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && react-native run-android"`

**Comment by gpeal** [comment]
I don't think this is lottie specific.

**Comment by sabbyt54** [comment]
I think it is related to this module. App was working fine and installed this module following the specified instructions and now app crashes on android. No failures on building and installing the apk, but crash on app load. 

Running `lottie-react-native@2.2.7` on `react-native@0.53.3`

**Comment by akbarsha03** [comment]
If anyone gets any errors on running `react-native run-android` do use `yarn` before the command

**Comment by AzizUrRehman1** [comment]
you just install app-release.apk and it's work

**Comment by gurbela** [comment]
For IOS:

In a terminal:

`cd ios`
Remove the build folder with: `rm -r build`

Run again: `react-native run-ios`

Alternatively, you could open Finder, navigate to **YOUR_PROJECT/ios and delete the build folder**.

Then run again: `react-native run-ios`

For ANDROID:

In a terminal:
`cd android/app`

Remove the build folder with: `rm -r build`

Run again: `react-native run-android`

Alternatively, you could open Finder, navigate to **YOUR_PROJECT/android/app** and **delete** the **build folder.**

Then run again: `react-native run-android`

**Comment by gianca970226** [comment]
En linux ejecutar estas linea  solucionado

sysctl -w fs.inotify.max_user_instances=1024
sudo sysctl -w fs.inotify.max_user_watches=12288

**Comment by Seffah** [comment]
I was able to resolve this error by firstt disabling my LAN setings from  proxy then running the app.
Thus Disable use proxy server for your LAN and now run the app

**Comment by Kevin-Ogechi** [comment]
@morfsys .... this is perfect thanks

**Comment by morfsys** [comment]
@Kevin-Ogechi , right. Thank you for pointing out.

**Comment by rafaelpadovani** [comment]
Thank you @morfsys this worked perfectly!

**Comment by reytum** [comment]
@morfsys you are a lifesaver. Kudos..

**Comment by LucasShaffer** [comment]
@morfsys 

From your root project directory do
cd android && ./gradlew clean

When I do this, I get " '.' is not recognized as an internal or external command, operable program or batch file"

Please advise.

**Comment by morfsys** [comment]
@LucasShaffer , this is gradle specific issue. Try googling related to this issue. Sorry, I couldn't help much.

**Comment by mahendramahi** [comment]
For window user only:- 
1>if you are using window then copy the path of adb location and set into Path in your system variable 
2> open project structure and delete node module folder.
3> now edit your project package.JSON file
             change react-native version "react-native": "0.55.2", and
            babel "babel-preset-react-native": "4", after that run "npm install"

4> now re start  cmd and js server and run your react native project by "react-native run-android"

**Comment by noctavel** [comment]
> in **android manifest** (/android/app/src/main/AndroidManifest.xml) there must be permission for internet (if you had deleted it) . it worked for me
> 
> ```
>     <uses-permission android:name="android.permission.INTERNET" />
> ```

worked for me too

**Comment by Jeyasee** [comment]
This error showing due to the missing of below files in project
index.android.bundle
index.android.bundle.meta
We need to create this files using command prompt first.

1)Select project folder in command prompt.
2)make sure , npm is installed.
3)Then check android/app/src/main has assets folder.
4)If does not have asset folder.Then create assets folder in like -->\android\app\src\main\assets
5)Then run below code
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res﻿
6)After that successful completion , these two files created in assets folder.

Then debug app normally..

**Comment by sryze** [comment]
How is it a solution if you have to manually run a command each time? It's just a workaround... a real solution would be making react-native's build script/whatever generate this bundle file automatically when runnin on Android, like it does for iOS presumably (for iOS I don't have to run any additional commands).

**Comment by HemantSharmaVB** [comment]
To resolve Unable to load script from assets index.android.bundle - React Native follow below process :

You have to create dir assets manually in your android project or make Directory by Terminal/CMD enter `mkdir android/app/src/main/assets`

Go at the created Directory if that is successfully created then

run step 3 Command:

`
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
`
you have your missed files in the folder now you can Run your React Native project npm run android.
i have found working solution from [Qna](http://qna.vbagetech.com/question/347/Unable-to-load-script-from-assets-indexandroidbundle-React-Native)

**Comment by ttdat2510** [comment]
enable wifi on emulator devices . it's work for me

**Comment by AuraSales** [comment]
> enable wifi on emulator devices . it's work for me

seems stupid but, I works for me

**Comment by joseph-perez** [comment]
I was running into the same error when trying to build a release version on a device. I was running react native 0.57.1 and was able to fix my issue by changing the gradle version. More info here https://github.com/facebook/react-native/issues/23739#issuecomment-469417259. Hopefully, the fix I used can fix someone else's build also 😄

**Comment by IjzerenHein** [comment]
For those that are running into this on Android 9 specifically (and don't want any dirty workarounds..), this was fixed in RN59 and requires additional network config to be added to your project.

To solve, add the following files to the `android/app/src/debug` folder.


> android/app/src/debug/res/xml/react_native_config.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
  <domain-config cleartextTrafficPermitted="true">
    <domain includeSubdomains="false">localhost</domain>
    <domain includeSubdomains="false">10.0.2.2</domain>
    <domain includeSubdomains="false">10.0.3.2</domain>
  </domain-config>
</network-security-config>
```

> android/app/src/debug/AndroidManifest.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools">

  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

  <application tools:targetApi="28"
      tools:ignore="GoogleAppIndexingWarning" 
      android:networkSecurityConfig="@xml/react_native_config" />
</manifest>
```

Source: https://stackoverflow.com/a/55147267/3785358

**Comment by thinklinux** [comment]
@IjzerenHein that's the correct thing to do... while I was updating I probably didn't created that files...

**Comment by renishdeveloper** [comment]
http://www.learnandroidcodeonline.com/Blogs/blogs_listing/unable-to-load-script.html
This blog helps to solve this issue.

**Comment by deserthurricane** [comment]
I had this issue only on Mac OS and only while trying to build for Android. It started to happen after my update from RN 0.57 to 0.59.

To understand what is going on I started a new RN project and compared differences with my project. I noticed that there is a new folder in the new project - android/app/src/debug. And there is only one file in this folder - AndroidManifest.xml with the following contents:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application android:usesCleartextTraffic="true" tools:targetApi="28" tools:ignore="GoogleAppIndexingWarning" />
</manifest>
```
After adding this file to my old project Metro Bundler started working for Android as expected.

**Comment by deserthurricane** [comment]
I had this issue only on Mac OS and only while trying to build for Android. It started to happen after my update from RN 0.57 to 0.59.

To understand what is going on I started a new RN project and compared differences with my project. I noticed that there is a new folder in the new project - android/app/src/debug. And there is only one file in this folder - AndroidManifest.xml with the following contents:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application android:usesCleartextTraffic="true" tools:targetApi="28" tools:ignore="GoogleAppIndexingWarning" />
</manifest>
```
After adding this file to my old project Metro Bundler started working for Android as expected.

**Comment by suwu150** [comment]
> This post fixes the issue: https://medium.com/@adityasingh_32512/solved-unable-to-load-script-from-assets-index-android-bundle-bdc5e3a3d5ff

thanks.

**Comment by waynemcfadden** [comment]
None of this is in 
https://facebook.github.io/react-native/docs/integration-with-existing-apps#adding-react-native-to-your-app

I mean wtf.

**Comment by yatendubey** [comment]
When you install the NodeJS using the choco command(**choco install -y nodejs.install python2 jdk8**), it will install the latest version of node which is 12.12.0 at the time of writing this answer. You have to downgrade it to 10.16.3 and ***run the react-native run-android*** command and it should work fine

**Comment by iamMoh3en** [comment]
> When you install the NodeJS using the choco command(**choco install -y nodejs.install python2 jdk8**), it will install the latest version of node which is 12.12.0 at the time of writing this answer. You have to downgrade it to 10.16.3 and _**run the react-native run-android**_ command and it should work fine

worked for me.

**Comment by CoSNaYe** [comment]
> enable wifi on emulator devices . it's work for me

God, I can't believe I've stuck at this for hours. Enable Wifi fixes the problem.

**Comment by alina-beck** [comment]
@sryze even two years later your solution still saved my day! This was the missing hint:

> I found a way to automatically run the bundle script: add this to your app/build.grandle:
```
project.ext.react = [
    entryFile: "index.js",
    bundleAssetName: "index.android.bundle",
    bundleInDebug: true,
    bundleInRelease: true
]
```

I had a working `debug` and `release` build after upgrading to react-native 0.63.2 but my `staging` build was broken. Adding `bundleAssetName: 'index.android.bundle'` and `bundleInStaging: true` did the trick! Thank you! 💚 :wink:

**Comment by abbasmoosavi** [comment]
> @sryze even two years later your solution still saved my day! This was the missing hint:
> 
> > I found a way to automatically run the bundle script: add this to your app/build.grandle:
> 
> ```
> project.ext.react = [
>     entryFile: "index.js",
>     bundleAssetName: "index.android.bundle",
>     bundleInDebug: true,
>     bundleInRelease: true
> ]
> ```
> 
> I had a working `debug` and `release` build after upgrading to react-native 0.63.2 but my `staging` build was broken. Adding `bundleInStaging: true` did the trick! Thank you! 💚 😉

Very thank you, Safe my life, it is worked for me

**Comment by bernica** [comment]
What if one wants to debug staging? How should I make it work like debug?

**Comment by mouhsnimohamed** [comment]
if you'r using proguard add an exception to android/app/proguard-rules.pro:

 -keep class com.mypackage.BuildConfig { *; }

com.mypackage should match the package value in your app/src/main/AndroidManifest.xml file.

**Comment by khiemnoob** [comment]
> You have to create dir assets m

seem stupid but it works for me

**Comment by 9christian9** [comment]
Ciao,
I'm writing for all the people who, like me, have experienced this problem.

**Affected Versions**
- React Native: 0.67.x
- Gradle 7.2.x - 7.3.x


**The common error**
> Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.

In short, index.android.bundle is missing
Common problem when trying to use productFlavors 


**The problem**
I found that the problem is in a native react gradle task, to be precise in the copy task called `currentAssetsCopyTask` located in `react.gradle`file.
As I understand, this "task" is responsible for copying the `assets` and in particular `index.android.bundle` and pasting them into the temporary directories used to generate the APK.


**The solution**
I created a repo that with a js script solves the problem before building the android app
[https://github.com/9christian9/FIX-Android-productFlavors-RN0.67-gradle7.2-7.3](https://github.com/9christian9/FIX-Android-productFlavors-RN0.67-gradle7.2-7.3)


I hope this will help.
With ♥ by Christian

**Comment by CascadiaTech** [comment]
For anyone who needs it again i know this was closed what fixed it for me is my computer crashed mid way through working on the application with the emulator open.

Do into your emulator and turn off wifi, and back on, do the same with your data. 

Clean your cache in your project. 

Good luck happy coding!
