### ISSUE TITLE
Example animations not always running on iOS

### ISSUE THREAD

**Issue by janicduplessis** [airbnb/lottie-react-native#27]
There seems to be an issue on iOS where the animation won't always start and run properly, it only happens when driving progress with an Animated.value, works fine when using the imperative API.

Repro:
In the lottie example
- Run the first animation -> works
- Change example to another one
- Run the animation -> sometimes doesn't work, if it works keep changing example until it doesn't

iPhone 6 simulator (iOS 10), RN 0.40 (exponent)

Also tested on Android and the bug is not present.

**Comment by lelandrichardson** [comment]
@janicduplessis when it doesn't start, will hitting "Reset" work?

**Comment by janicduplessis** [comment]
No, I logged the Animated.Value's value and that works properly, also android works fine so I guess the issue is in lottie-ios.

If I pop the screen that has the lottie example then go back to it it starts working again.

**Comment by janicduplessis** [comment]
However as soon as I start switching between examples and playing animations is stop working after a few times (the animation doesnt start, only the first frame is shown)

**Comment by lelandrichardson** [comment]
Interesting. OK. Must be a real bug then. Will take a look cc @buba447

**Comment by indivisable** [comment]
@janicduplessis I can confirm this as well - on iPhone 6S lastest iOS 10 running examples.

For me it seemed like specific examples would not load , I will test again and see I can help be more specific.

**Comment by lelandrichardson** [comment]
It looks like this only affects the declarative (Animated driven) API. My guess is that there's some issue with setting progress and then setting the json to something different. I'm pretty sure this used to work, so i'll take a look.

**Comment by rqzheng2015** [comment]
got same issue here, any solutions now?

**Comment by ferologics** [comment]
+ 1

**Comment by MattyK14** [comment]
Before switching animation examples, dragging the progress bar back to the start seems to avoid this bug for me.

**Comment by clucasalcantara** [comment]
Try to add the lottie-ios to you xcode embed libraries. 
![image](https://cloud.githubusercontent.com/assets/6919712/23196065/0dfa07ce-f896-11e6-9392-690389d47ae9.png)
![image](https://cloud.githubusercontent.com/assets/6919712/23196065/0dfa07ce-f896-11e6-9392-690389d47ae9.png)

**Comment by g3r4n** [comment]
You have to remove libLottie.a

**Comment by janicduplessis** [comment]
Updated to the latest version and the bug doesn't happen anymore.
