### ISSUE TITLE
Is there any typescript type definition for lottie?

### ISSUE THREAD

**Issue by rodrigoelp** [airbnb/lottie-react-native#270]
Hi, I'm looking into using lottie heavily in some of my applications and I want to know if you guys have it exposed in typescript.

If you don't, is there an API documentation I can browse so I can generate the type definition for this package and push it as a pull request?

**Comment by rodrigoelp** [comment]
I am closing this... just found the typedef

**Comment by casizzi** [comment]
@rodrigoelp where did you find the typings? I am looking to use on an angular project and it's been painfull trying to find the typings! Thanks in advance!

**Comment by angusm** [comment]
Noting that this might be it: https://github.com/react-native-community/lottie-react-native/blob/master/src/js/index.d.ts

In case I forget to come back and update this after I confirm.
