### ISSUE TITLE
Proposal of channel discussion

### ISSUE THREAD

**Issue by MichelDiz** [airbnb/lottie-react-native#282]
Hi, I took the liberty of creating a public chat in the discord facing React-Native. With the intention of uniting the React-native community and improving communication.

I'm creating a channel for public discussions about your project. To avoid flooding "chat" on your github. If you can support the initiative, great! Just share the link below xD

I'm adding RN only projects to this public chat service. And I commit myself to manage chat rooms.
You would just need to observe the chat related to your project.

here's the link
https://discord.gg/RvFM97v

Cheers.

**Comment by gpeal** [comment]
Neat, thanks!
