### ISSUE TITLE
ios build failed - Use of undeclared identifier 'LOTKeypath'

### ISSUE THREAD

**Issue by androsanta** [airbnb/lottie-react-native#283]
$npm -v `5.0.3`
$react-native -v `react-native-cli: 2.0.1
react-native: 0.45.1`
lottie-react-native `2.3.2`
lottie-ios `2.5.0`

Hello, I'm facing this issue when building my project on real device (using the simulator everything works fine)
This is the full error on Xcode:

<img width="814" alt="screen shot 2018-02-14 at 5 16 23 pm" src="https://user-images.githubusercontent.com/23356967/36214884-d901320c-11aa-11e8-8f74-34fd35512dc6.png">

I installed the library this way:
`npm i lottie-react-native`
`react-native link lottie-ios`
`react-native link lottie-react-native`
Then I add Lottie.framework in Embedded Binaries and libLottieReactNative.a in Linked framework and libraries (as suggested by Issue #59)

**Comment by eabait** [comment]
I have the same error, but only when building from cli. Is working when building from Xcode.

**Comment by androsanta** [comment]
I actually resolve deleting  `~/Library/Developer/Xcode/DerivedData/*` and  `~/Library/Developer/Xcode/Archives/*`, thank you anyway

**Comment by mlm249** [comment]
Deleting ~/Library/Developer/Xcode/DerivedData/* worked for me as well.

Any ios devs wanna chime in to what the DerivedData folder does? I assume some sort of build caching but it'd be nice to know it's purpose.

**Comment by justinmakaila** [comment]
DerivedData is just build artifacts from Xcode. Xcode started using incremental building and tries to pull data from this folder to shorten build times, and some times it will use the wrong artifact.
