### ISSUE TITLE
Animation working on web but not working on iOS platform(using React Native)

### ISSUE THREAD

**Issue by purvil12c** [airbnb/lottie-react-native#285]
The animation is working completely fine as expected when using web version of Lottie. But, I have been developing a react-native app wherein I need to use this animation. I have made this animation using Adobe After Effects and exported it using Bodymovin to JSON file. Since, text animations cannot be rendered by Lottie yet on iOS, I am converting the text layer to shapes using the option "Create shapes from Text". I am attaching the AEP file as well as the JSON file.

JSON File - https://storage.googleapis.com/cloud-vision-api-test-1/dietchek.json
AEP File - https://storage.googleapis.com/cloud-vision-api-test-1/Untitled%20Project.aep

**Comment by rexlow** [comment]
+1

**Comment by gpeal** [comment]
Please post this on lottie-ios
