### ISSUE TITLE
LOTAnimationView not centering correctly

### ISSUE THREAD

**Issue by iCappsCedric** [airbnb/lottie-react-native#297]
Hi, 

I am using the following code inside my project:

        let animationView = LOTAnimationView(name: "anubis")
        animationView.frame = lottieView.bounds
        animationView.center = lottieView.center
        animationView.contentMode = .scaleAspectFill
        
        lottieView.addSubview(animationView)
        
        animationView.loopAnimation = true
        animationView.play()

The `lottieView` is a UIView which I set in my storyboard using constraints (seen in the picture by the bright light green color). For some reason the image isn't set correctly inside the view, but it appears more to the left bottom.

![screen shot 2018-03-16 at 14 47 37](https://user-images.githubusercontent.com/27772856/37524215-79755f02-2929-11e8-805d-ae1a83240023.png)

Device: iPhone SE

**Comment by wzbozon** [comment]
I fixed this by moving LOTAnimationView code from ViewDidLayoutSubviews to the ViewDidAppear. Strange bug.

**Comment by picturehit** [comment]
Hello @iCappsCedric 
Do you find a solution ? 
Thank you
