### ISSUE TITLE
package com.airbnb.android.react.lottie does not exist

### ISSUE THREAD

**Issue by arunkumarcap91** [airbnb/lottie-react-native#302]
**error**: package com.airbnb.android.react.lottie does not exist
import com.airbnb.android.react.lottie.LottiePackage;

MainApplication.java

import com.airbnb.android.react.lottie.LottiePackage;
       ....

**error**: cannot find symbol
     new LottiePackage(),
         ^
  symbol: class LottiePackage

@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
                ....
        new LottiePackage(),

**Comment by pedpess** [comment]
@arunkumarcap91 Check if your `settings.gradle` file in your android folder is using the right path for the `node_module`. Recently, Lottie has changed the path for the lib

This is the right one:
`project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')`

**Comment by gpeal** [comment]
I believe @pedpess is correct

**Comment by munonn430** [comment]
@pedpess both also not working right now

**Comment by tampham1210** [comment]
i have the same issue, but i used the right path
![image](https://user-images.githubusercontent.com/54975300/67999160-a88e5800-fc8d-11e9-9da1-a6350c901e13.png)
