### ISSUE TITLE
JSON animation file works perfect in iOS but in Android shows a blank screen

### ISSUE THREAD

**Issue by xMaarf** [airbnb/lottie-react-native#304]
I've implemented an animation but it doesn't works with Android but it does in iOS. 
I have another animation in my app and it works fine.
I've tried moving it to assets folder and nothing.
Here's the animation JSON: https://pastebin.com/Yb5ZeGqr

**Comment by xMaarf** [comment]
Removing enableMergePathsAndroidForKitKatAndAbove from LottieView props fixed this issue.

**Comment by Arshiamidos** [comment]
pls show your gradle and build setting and which lottie version u use?
@xMaarf

**Comment by Arshiamidos** [comment]
@Hao3o5  check my answer in #242

**Comment by joshuapinter** [comment]
FYI, we went through the painstaking process of updating from 0.59.10 to 0.60.6 just to get this working and after a few days of upgrade hell, Lottie works perfectly now without any monkeying around.
