### ISSUE TITLE
Thread 1: signal SIGABRT build ios

### ISSUE THREAD

**Issue by VesperDev** [airbnb/lottie-react-native#334]
when I executed the project with lottie installed I have the following error
<img width="1142" alt="screen shot 2018-05-29 at 12 32 07 am" src="https://user-images.githubusercontent.com/14016458/40639773-5ebba7e6-62d8-11e8-9c5d-18ec636afa5d.png">

more details:

> Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.0 AI-171.4443003

> Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

Package.json

{
  "name": "easypay",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "firebase": "^5.0.3",
    "lottie-react-native": "^2.3.2",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "^0.19.1",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-router-flux": "^4.0.0-beta.31",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.0.4",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "22.4.4",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.4",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

other image

<img width="837" alt="screen shot 2018-05-29 at 12 40 53 am" src="https://user-images.githubusercontent.com/14016458/40639879-0294401c-62d9-11e8-9f3c-d81b9c7f56d3.png">

Why is this happening? I think there is a configuration in xcode that I am forgetting
Thank you very much for your time

**Comment by VesperDev** [comment]
In the Embedded Binaries section above click the + icon and add the Lottie.framework.iOS from Lottie.xcodeproj

https://medium.com/react-native-training/lottie-react-native-tutorial-162d91840720

**Comment by cdra0624** [comment]
if you are using `firebase`, this works for me.

https://github.com/invertase/react-native-firebase/issues/1633#issuecomment-432801902

**Comment by imansalhi** [comment]
I added lottie.framework in embedded binaries and it worked ...

**Comment by atrimn** [comment]
where is embedded binaries? theres no such thing on my xcode

**Comment by heyproject** [comment]
> Hello Guys,
> I was having the same issue on RN 0.60.4
> The error was actually caused by this:
> libswiftCore.dylib requires an OS version prior to 12.2.0
> 
> And the easy fix for this issue in my case was to create an empty swift file on my project.
> 
> I hope this can help anyone facing the same issue.

Hi Mate, 

I got the same issue on RN 0.60.5. Can you please provide screenshot of your blank swift file? what's the name of the file? and where to put it? Thank you before.



Regards,
