### ISSUE TITLE
 Merge paths problem android api 19 

### ISSUE THREAD

**Issue by Farzad-rh** [airbnb/lottie-react-native#338]
Hi guys and thank you for developing such awesome library .
I recently found out my react-native app crashes on android 18 and 19 apis. 

## environment :
  {
    "lottie-react-native": "^2.5.0",
    "native-base": "^2.3.9",
    "react": "^16.3.0-alpha.1",
    "react-native": "0.55.3",
     ...
} 
android emulator : 
genymotion 
api :19 

## logcat :

 `W/LOTTIE  ( 4810): Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
D/AndroidRuntime( 4810): Shutting down VM
W/dalvikvm( 4810): threadid=1: thread exiting with uncaught exception (group=0xa4cabb20)
E/AndroidRuntime( 4810): FATAL EXCEPTION: main
E/AndroidRuntime( 4810): Process: com.enzymeclient, PID: 4810
E/AndroidRuntime( 4810): java.lang.NullPointerException
E/AndroidRuntime( 4810):        at com.airbnb.lottie.animation.content.BaseStrokeContent.<init>(BaseStrokeContent.java:63)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.animation.content.StrokeContent.<init>(StrokeContent.java:26)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.model.content.ShapeStroke.toContent(ShapeStroke.java:77)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:29)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:46)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:236)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:198)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:488)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.LottieAnimationView$1.onCompositionLoaded(LottieAnimationView.java:81)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:29)
E/AndroidRuntime( 4810):        at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:12)
E/AndroidRuntime( 4810):        at android.os.AsyncTask.finish(AsyncTask.java:632)
E/AndroidRuntime( 4810):        at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime( 4810):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
E/AndroidRuntime( 4810):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4810):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4810):        at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 4810):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4810):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4810):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 4810):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 4810):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  624):   Force finishing activity com.enzymeclient/.MainActivity
`

JS code : 

<View style={{backgroundColor: '#fff', flex: 1, alignItems: 'center', justifyContent: 'center'}}>
                 **<LottieView
                    enableMergePathsForKitKatAndAbove={true}
                    source={require('../assets/animation/world.json')}
                    progress={this.state.progress}/>**
             
 </View>

As u can see ive added enableMergePathsForKitKatAndAbove={true} but i dont know why still get this error and app crashes.

**Comment by emilioicai** [comment]
Try changing your `<LottieView />` to this:

```
<LottieView
enableMergePathsAndroidForKitKatAndAbove ={true}
source={require('../assets/animation/world.json')}
progress={this.state.progress}/>
```

The property in React Native is annotated as `enableMergePathsAndroidForKitKatAndAbove` instead of `enableMergePathsForKitKatAndAbove`
