### ISSUE TITLE
react-native run-ios crashing 

### ISSUE THREAD

**Issue by jinshin1013** [airbnb/lottie-react-native#342]
After a successful installation and linking of lottie-react-native, the ios app is not opening from react-native run-ios command. The app is building successful and running fine when running from xcode, however react-native run-ios command still builds however the app opens and closes after a few seconds. The bundler is not doing anything, not sure what is happening.

Versions:
react-native: 0.55.4
lottie-react-native: 2.3.2

**Comment by jinshin1013** [comment]
Solved it. I included `Lottie.Framework` to only `Linking Binaries` rather than `Embedded Binaries`. This somehow still worked when running from XCode, however did not work on `react native run-ios` command. Closing the issue now.

**Comment by nicovak** [comment]
@jinshin1013  I have the same issue and `Embedded Binaries` is empty. It only works by running It directly from xcode. Maybe It should be opened again.

**Comment by jinshin1013** [comment]
@nicovak You should be importing Lottie.Framework to Embedded Binaries.

**Comment by nicovak** [comment]
@jinshin1013 include `Lottie.framework` to only `Embedded Binaries` did the fix. Thank you.
