### ISSUE TITLE
cannot override getUseDeveloperSupport() as protected

### ISSUE THREAD

**Issue by lc3t35** [airbnb/lottie-react-native#38]
When I execute : npm run run:android, I have this error
````
/***/lottie-react-native/example/android/app/src/main/java/com/example/MainApplication.java:21: error: getUseDeveloperSupport() in <anonymous com.example.MainApplication$1> cannot override getUseDeveloperSupport() in ReactNativeHost
    protected boolean getUseDeveloperSupport() {
                      ^
  attempting to assign weaker access privileges; was public
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
````
Changing "protected" to "public" corrects the issue.

**Comment by zhaojiakang917** [comment]
change protected to public

**Comment by the-simian** [comment]
to be more specific:
in your `MainApplication.java` file, 
`public boolean getUseDeveloperSupport() {` <-----

**Comment by lc3t35** [comment]
@zhaojiakang917 @the-simian thanks but did you read the end of my post : "Changing "protected" to "public" corrects the issue" ;) Maybe I should have submitted a PR that would be more visible ;)

**Comment by spikebrehm** [comment]
Indeed, in a recent version the method changed from `protected` to `public`: https://github.com/facebook/react-native/pull/11329

**Comment by vijayperlakota** [comment]
Changing 'protected' to 'public' works. 💯

**Comment by bkhurjawal** [comment]
Changing private to public saved my life. Thank you guys, I don't know java I am working in react native!

**Comment by yusuf987** [comment]
Changing 'protected' to 'public' works. but now my app is crashing ,
does someone has any idea ???
