### ISSUE TITLE
Cannot read property 'Commands' of undefined

### ISSUE THREAD

**Issue by ferologics** [airbnb/lottie-react-native#39]
It doesn't appear that your React Native support for Android works.

`AirbnbLottieView` in undefined in `Animation.js` line 97 when calling `UIManager.AirbnbLottieView.Commands[commandName]`

Where is this coming from?

After some source digging I believe it should be called `LottieAnimationView` instead.

**Comment by rqzheng2015** [comment]
it works for me, thx~

**Comment by offwhite** [comment]
@ferologics did you have to add lottie for android to your build gradle to get this lib to work on android?

**Comment by rqzheng2015** [comment]
@offwhite i have tested it on real device, no need to do that

**Comment by offwhite** [comment]
thanks for the reply @rqzheng2015 - I'm also testing on a real device, and I'm still getting an error after updating Animation.js (screen grab attached)

Inspecting UIManager, I can see no reference to LottieAnimationView, so I'm thinking that Lottie for android library isn't available, though this is in my build.gradle: `compile 'com.airbnb.android:lottie:1.0.1'`

![screenshot_20170207-181447](https://cloud.githubusercontent.com/assets/3521570/22705012/be0a5a82-ed61-11e6-80d8-40203c9d2f2f.png)

**Comment by ferologics** [comment]
@offwhite all you need is 'lottie-react-native', link it, and make the change mentioned in the PR.

**Comment by joaqtor** [comment]
This is happening to me now, with last version of Lottie, on line 99.

`UIManager.LottieAnimationView.Commands[name],` throws `Cannot read property 'Commands' of undefined`

**Comment by ThakurKarthik** [comment]
Issue still exists

**Comment by Anisha95** [comment]
> react-native link lottie-react-native

I have already linked it,! Still the error is coming
