### ISSUE TITLE
cant get the examples to work

### ISSUE THREAD

**Issue by nikitph** [airbnb/lottie-react-native#43]
latest react-native. copy pasted both examples and tried it with attached data.json to no avail. i just get a blank screen. clearly it has worked for people. i m not sure wht i m doing wrong. help?
[data.json.zip](https://github.com/airbnb/lottie-react-native/files/759653/data.json.zip)

**Comment by nikitph** [comment]
my best guess is a incompatible json file

**Comment by offwhite** [comment]
are you running it on ios or android?

**Comment by nikitph** [comment]
Ios

**Comment by g3r4n** [comment]
See an example running here : https://github.com/g3r4n/react-native-lottie-example

**Comment by lelandrichardson** [comment]
I believe this should now be fixed. Please try it out and let me know if you still have trouble. Closing this issue for now. Thanks!
