### ISSUE TITLE
Execution failed for task ':app:dexDebug'

### ISSUE THREAD

**Issue by kresogalic8** [airbnb/lottie-react-native#44]
Hey guys, I tried to run your example on android and I got this error, can you tell me what's the problem?

![screen shot 2017-02-08 at 11 14 03 am](https://cloud.githubusercontent.com/assets/7289406/22732784/caaa8e7c-edef-11e6-9d1d-bc0b96d0d8dd.png)

**Comment by Fdom92** [comment]
I have the same issue. Just make some test to try react-native with lottie but fails. I followed all the steps on the README, but got that error so i cant see my watermelon.

I dont have a huge code just the starter kit and lottie.

```
export default class RNtest extends Component {
  componentDidMount() {
    this.animation.play();
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      <Animation
        ref={animation => { this.animation = animation; }}
        style={{
          width: 150,
          height: 150,
        }}
        source={require('Watermelon.json')}
      />
      </View>
    );
  }
}
```

**Comment by lelandrichardson** [comment]
I'm able to reproduce this locally as well. Not sure what has changed. cc @gpeal @felipecsl do you think you can help out ?

**Comment by jozan** [comment]
I got this working by cleaning build caches in `android` directory. `./gradlew clean`.
