### ISSUE TITLE
1.0.4 Build Missing Header / Errors

### ISSUE THREAD

**Issue by indivisable** [airbnb/lottie-react-native#49]
I recently tried to update to latest build (1.0.4) and got some issues:

First the LottieReactNative projects asks for the Lottie.h

![image](https://cloud.githubusercontent.com/assets/22860891/22768404/92d74906-ee47-11e6-8716-a0dc16ac6a22.png)

Then if I update the header path to include the path `$(SRCROOT)/../../../lottie-ios` then I get a bunch of errors:

![image](https://cloud.githubusercontent.com/assets/22860891/22768512/58a3436a-ee48-11e6-8b2c-c2299c45e912.png)

![image](https://cloud.githubusercontent.com/assets/22860891/22768475/0c14d69e-ee48-11e6-8b54-469e6653c444.png)

Any ideas?

RN 0.38.0 / Latest OSX / XCode

**Comment by lelandrichardson** [comment]
@indivisable i apologize for the turbulence here. I have figured out how to make a project with other ios dependencies work for RN for all types of projects (both cocoapods and not). The last thing we need is for https://github.com/airbnb/lottie-ios/pull/64 to get merged. That will hopefully happen tomorrow morning.

Thanks so much for your patience! This project has been a learning experience for me :P

**Comment by indivisable** [comment]
@lelandrichardson No problem at all :) Considering how awesome this library is it is worth it! Thanks for the update and look forward to testing updated version.

**Comment by coolnameismy** [comment]
this issue because the pod not install completely, i cross same situation. 
i insert a line at 12, `  pod 'lottie-ios', :path => '../../node_modules/lottie-ios/lottie-ios.podspec'` for down load the lottie-ios, after wait, the problem is gone .

**Comment by lelandrichardson** [comment]
@coolnameismy is this still happening?

**Comment by mikehobi** [comment]
I am getting the `'Lottie/Lottie.h' file not found` error on a fresh install. Haven't tried updating the header path; is that an additional install step for the project?

**Comment by indivisable** [comment]
This seems to be resolved with 1.0.6 release.

**Comment by Kowaio** [comment]
Hi guys,

Sorry to bother you again with this but I can't find a way to build my project using lottie-react-native in Release. When trying to build and deploy my app on Testflight using fastlane, I've got the following message: `node_modules/lottie-react-native/lib/ios/LottieReactNative/LRNContainerView.h:19:9: 'Lottie/Lottie.h' file not found`

In debug and simulator, everything is working properly. It seems like it's the release build that's failing. I'm using 1.06 and RN 0.39. Unfortunately I can't update RN just now but I read that it was working for 0.38 somewhere so I don't think that's the problem.

I tried removing embedded Lottie.framework and adding it but nothing so far.

Thanks for your help guys!

**Comment by gschattenhofer** [comment]
I have the same issue still. Can we reopen this?

**Comment by WeeTom** [comment]
You guys must have missed this step

"After this, open the Xcode project configuration and add the Lottie.framework as Embedded Binaries."

The steps in the readme is easily to miss this step, because the next two steps are "If you use cocoapods", people using npm -i would carelessly miss the embedded binaries step!

@Kowaio @gschattenhofer

**Comment by paulief** [comment]
@WeeTom I've done that step and still have the issue, so that's not it. This problem seems to happen intermittently. If I quite Xcode and re-open, then clean my build folder, sometimes it will build successfully. Sometimes if I unlink and link again, it will work.

RN - v0.43.3 and Lottie - v1.1.1

**Comment by WeeTom** [comment]
@paulief look, it's not link a binary but embed one. like this: it's in Project -> General -> Embedded Binaries
![image](https://user-images.githubusercontent.com/1827137/26910874-32fcfdf2-4c3c-11e7-9a76-1d8ff1dbcdc4.png)

**Comment by hecomzhangzhiguo** [comment]
Build Phases -> Target Dependencies -> add Lottie_iOS  -> resolved

**Comment by ricardoorellana** [comment]
In my case linking again the library fixed the problem:

```
react-native link lottie-ios
react-native link lottie-react-native
```
