### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by datwheat** [airbnb/lottie-react-native#5]
Hey there,

The README is missing a simple installation guide. I'm very interested in using this in the future, but I don't want people to get their hopes up when using something like Exponent thinking that they can use it like any JS library (before they look at the code and see the *.gradle files of course). I'm assuming it's just a simple `npm i -S lottie-react-native && react-native link lottie-react-native`, but there are often caveats to native modules that could be explained if they exist with this one.

Thanks and great job guys!

**Comment by lelandrichardson** [comment]
@datwheat Agreed! I'll get one up ASAP.
