### ISSUE TITLE
Compiles fine but iOS crashes on startup

### ISSUE THREAD

**Issue by carleryd** [airbnb/lottie-react-native#63]
Runs fine on Android, runs fine on XCode simulator, but crashes instantly on iOS startup, giving me nothing but a stack trace to some assembly line..

I found out through another post that the issue was that I had not added Lottie.framework to "Embedded Frameworks" in the "General" tab.
Hope this helps someone out!

**Comment by eneskaya** [comment]
Thank you, helped me
