### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by lee-you** [airbnb/lottie-react-native#66]
RN version :0.41.2
after npm i --save lottie-react-native  
react-native link lottie-ios
react-native link lottie-react-native/

<img width="532" alt="509e06fa-21e6-4935-adeb-50660ac22161" src="https://cloud.githubusercontent.com/assets/18346188/23053845/181955f2-f517-11e6-8f44-c78bc071d0c1.png">

**Comment by indivisable** [comment]
@lee-you Could you confirm which version of lottie-react-native got installed? You can see this in node_modes/lottie-react-native/package.json 

Also try using this command:

npm -i --save github:airbnb/lottie-react-native to get latest release from repo as the npm package may not have been updated yet

**Comment by madsleejensen** [comment]
i receive samme error: i tried doing a clean install of node_modules/ but still same error

> lottie-ios@^1.0.2:
>   version "1.0.2"
>   resolved "https://registry.yarnpkg.com/lottie-ios/-/lottie-ios-1.0.2.tgz#8c6ec0a9a349a3816c597dc975505f6df8b4c17b"
> 
> lottie-react-native@^1.0.6:
>   version "1.0.6"
>   resolved "https://registry.yarnpkg.com/lottie-react-native/-/lottie-react-native-1.0.6.tgz#f9f074372addc1fbb365072f022ed0291e2b866a"
>   dependencies:
>     invariant "^2.2.2"
>     lottie-ios "^1.0.2"
>     react-native-safe-module "^1.1.0"

**Comment by JanPeter** [comment]
Any update on this?
