### ISSUE TITLE
Unable to build iOS examples

### ISSUE THREAD

**Issue by MyGuySi** [airbnb/lottie-react-native#69]
I tried Lottie when it was initially release but figured I'd give it a bit of time to iron out some of the issues that were present at launch. I've made a fresh clone though and I'm still unable to build:

<img width="257" alt="screen shot 2017-02-21 at 14 49 37" src="https://cloud.githubusercontent.com/assets/12952977/23169898/5d300916-f845-11e6-87bb-3948d190e520.png">

I'm using v1.0.6 if that helps, thanks.

**Comment by huangbow** [comment]
run `pod update` in the example/ios file

**Comment by therealsalih** [comment]
@MyGuySi did running pod update work for you?

**Comment by MyGuySi** [comment]
Hey sorry, I must have missed the last notification. I'll give it a try today and report back

**Comment by MyGuySi** [comment]
Yeah that worked, thanks!
