### ISSUE TITLE
How to run the example?

### ISSUE THREAD

**Issue by jacklam718** [airbnb/lottie-react-native#7]
Not really know how to run the example. If have a more explicit instruction is better 😬

**Comment by browniefed** [comment]
I got them running by
`npm install` in the root of the folder
`pod install` in `examples/ios`

If you don't have cocoapods installed you can do so by using brew `brew install cocoapods`

then start the packager by running `npm run start`

Finally launch one of the versions

```
npm run run:ios
```

or with android if you have your emulator running (untested)

```
npm run run:android
```

**Comment by hsavit1** [comment]
@browniefed I have been having a hard time running this as well... I'm greeted with the red screen of death

it says "cannot find entry file example/index.js in any of the roots..."

Any idea what that means?

**Comment by huchenme** [comment]
thanks, start the packager by running `npm run start` in a separate terminal tab/window works for me, the packager does not start automatically

**Comment by hsavit1** [comment]
@huchenme that worked, thanks!
