### ISSUE TITLE
Where to find JSON adobe effect animation

### ISSUE THREAD

**Issue by yelkamel** [airbnb/lottie-react-native#72]
Hello,

It's not really an issue but I completely shit on adobe (I never use it).
Do you know if there is any site where I can find some animation in JSON ? 

Regards

**Comment by verybadassninja** [comment]
Hi,
There is a few animation here,
http://www.lottiefiles.com

**Comment by grifotv** [comment]
You can get the bodymovin JSON files from these examples http://codepen.io/search/pens?q=bodymovin&limit=all&type=type-pens
