### ISSUE TITLE
lottie-android 1.5 support in react native?

### ISSUE THREAD

**Issue by jdpigeon** [airbnb/lottie-react-native#78]
I was really excited to hear that pre-compositions and images are now supported in the last version of Lottie for Android.

However, introducing the new update (1.5.2) through both my app's build.gradle or the lottie-react-native build.gradle in node_modules leads to a null object exception in the parseLayers method of LottieComposition.java

`
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
                                                                     at com.airbnb.lottie.LottieComposition$Factory.parseLayers(LottieComposition.java:200)
                                                                     at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:194)
`

I tried the new update with my animations in a pure Android app and it works totally fine. 

Is this error due to lottie-react-native being behind lottie-android? When do you think an update will come? Or am I doing something wrong?

**Comment by panunu** [comment]
Would also like to know when the RN version is going to catch up with native Lotties :-)

Is there something blocking the upgrade or just a lot of work?

**Comment by aaronsky** [comment]
I would also like to know the status of this upgrade. Not using precomps or image layers while still integrating this preferable animation solution would require my designers to redo their work without those features, which I'd rather not have them do

**Comment by panunu** [comment]
@lelandrichardson any comment? :-)

**Comment by jozan** [comment]
I debugged this a bit and seems like `lottie-react-native` is somehow bugged. It doesn't pass correct JSON data to `lottie-android` which results `jsonLayers` always to be `null`.

![image](https://cloud.githubusercontent.com/assets/388265/23892633/15f55c8a-08a4-11e7-8859-3de20d3840dc.png)

As you can see in the screenshot, `jsonLayers` is `null`. You can also see method argument `json` is `ReadableNativeMap`. It should be `JSONObject` as shown in the screenshot below which is taken from `lottie-android` LottieAndroid example app.

![image](https://cloud.githubusercontent.com/assets/388265/23892802/c66b4494-08a4-11e7-835e-15ad20acc93c.png)

**Comment by panunu** [comment]
Ok, seems like `<Animation source={require(...)} />` is bugged when bumping the version manually.

So `<Animation source="asset-filename.json" />` works in `lottie-react-native` when using `compile 'com.airbnb.android:lottie:1.5.3'` (tested *only* in Android, dunno about iOS).

**Comment by panunu** [comment]
@jdpigeon did you have your JSON file in `app/src/main/assets/` folder?

**Comment by jdpigeon** [comment]
Of course! Moved my jsons there and It works now

I guess your workaround sneakily avoids `lottie-react-native` processing the JSON before it gets to the android library. It definitely makes sense in that case to store the app in the Android source.

Hopefully we've identified some issues that can be fixed for everybody in an upcoming update :slightly_smiling_face:

**Comment by jdpigeon** [comment]
Note: image support through `lottie-react-native` with this workaround is probably still impossible because it's impossible to call the `setImageAssetsFolder` function that the android library requires.
