### ISSUE TITLE
Lottie images not showing up in IOS

### ISSUE THREAD

**Issue by cgruca** [airbnb/lottie-react-native#802]
Hey everyone,

I have an animation that includes a scrolling background image, but I can't get it to show up on IOS.
I followed the steps for android and it worked great. I created my lottie view and put my json in my react native project/assets/animations folder and put the image folder in android\app\src\main\assets\animations.

```
<LottieView
              ref={animation => {
                this.animation = animation;
              }}
              source={require('../../assets/animations/anim.json')}
              imageAssetsFolder={'animations/images'}
              resizeMode = 'cover'
      />
```

How do I get this to work for IOS? Where do I put the image folder?

I followed the documentation here: https://github.com/lottie-react-native/lottie-react-native/blob/master/docs/api.md
Which said to add the images to the Resource folder in the XCode project.
My project didn't have a Resources folder by default, so I added one in and then added the image into it but still no luck.
The animation plays but it only shows the vector graphics which are built in the json file which is in the react native project/assets/animations folder.

Using:
    "lottie-ios": "3.2.3",
    "lottie-react-native": "^4.0.3",
    "react-native": "0.63.4",

Any help is appreciated!

**Comment by Feyddy** [comment]
Hello ,I have the same question. Can you give me some photos to show how to do it? Thank you very much!
