### ISSUE TITLE
Don't see any animation

### ISSUE THREAD

**Issue by tetrakiss** [airbnb/lottie-react-native#82]
Hello,
react-native-cli: 2.0.1
react-native: 0.42.0
lottie v1.0.6

I try build app with simple code from basic usage:
```javascript
import React from 'react';
import Animation from 'lottie-react-native';

export default class BasicExample extends React.Component {
  componentDidMount() {
    this.animation.play();
  }

  render() {
    return (
      <Animation
        ref={animation => { this.animation = animation; }}
        style={{
          width: 200,
          height: 200,
        }}
        source={require('./HamburgerArrow.json')}
      />
    );
  }
}
```
I took HamburgerArrow.json from example. All ok it build success, but I don't see any animation.
Any ideas?

**Comment by g3r4n** [comment]
Remove LibLottie.a from the linked dependancies

**Comment by irrigator** [comment]
@g3r4n Thanks for a working example! Could you please explain a bit more about why the official example fail to run? It will be even nicer to help make it work!

**Comment by g3r4n** [comment]
@irrigator I'm not a IOS developper so it will be hard for me to explain in details why it's not working. 
The official example use Cocoapods to build and run the project. My example use  the react-native client. this is a major difference between the official example and mine.
The error come from tthe lottie-ios project that don't correctly link the dependencies to the iOS Xcode project.

**Comment by ryancoughlin** [comment]
I am having a similar issue. Is that example at the repo using CocoaPods?

**Comment by g3r4n** [comment]
@ryancoughlin I'm not using CocoaPods

**Comment by joypatel04** [comment]
@g3r4n Can you please explain your setup steps? It would be helpful to all of us who is not using CocoaPods.

**Comment by g3r4n** [comment]
@joypatel04 see PR #86

**Comment by mini-eggs** [comment]
@g3r4n thanks for the example, appreciate it v much

**Comment by AdityaAgg** [comment]
Removed  LibLottie.a from my dependencies. 
Added Lottie.Framework to XCode. 
lottie-react-native is linked
logged json and could output all of it. 
Animation doesn't appear still. :( Probably doing something silly but any help would really be appreciated! 

Here's snippets of my code that'd probably relevant:

`
import ProgressJson from 'lottie-react-native/example/animations/gliaprogress.json'

this.state = {
     progress: new Animated.Value(0.5),
   };

        <Animation
        source={ProgressJson}
        progress={this.state.progress}
        style = {styles.image_css_indicator}
        />
`
This might have a slight chance of being relevant because I scale the animation down in the css attributes. 

`transform: [{scale: 3.2/8.0}]`

when I change the scale to certain values, place two animations (repeated) and wrap the animation components with views that have borders I get parts of the animation. 

Think everything about the scale is not relevant/doesn't apply to the issue I am facing. But just thought I'd add it just incase. Works perfectly fine on Android doesn't work on iOS.

**Comment by mini-eggs** [comment]
@AdityaAgg 

Figured this out for my proj. I'll post a short how-to then update sometime tomorrow with more details.

Removing LibLottie.a from linked iOS dependencies did not working for me. Here's what I did:

1. Follow this repo's guide on installing (react-native link etc)
2. Make your Link Binary With Libraries in xcode look like this (only lottie things are relevant): http://i.imgur.com/83VPlEs.png
3. Make your Embedded Binaries look like this (only lottie things are relevant): http://i.imgur.com/SV7iyei.png
4. Build!

More details coming tomorrow.

**Comment by AdityaAgg** [comment]
@mini-eggs unfortunately your suggestions did not work out for me. But let me know the reason this worked out for you and what you are going to share tomorrow. That may help.

**Comment by mini-eggs** [comment]
Here's my current environment:
react 15.4.1,
react-native 0.42.3,
yarn 0.21.3

Steps:
1) react-native init Lottie
2) cd Lottie
3) Dragged my previous projects code into this project, with package.json dependencies, etc.
4) yarn
5) yarn add https://github.com/airbnb/lottie-react-native.git
6) yarn add babel-plugin-module-resolver (@g3r4n 's project had this)
7) react-native link lottie-ios
8) react-native link lottie-react-native
9) Open up xcode
10) Link Binary With Libraries -> add -> search `lottie` -> choose Lottie.framework from 'lottie_iOS'
11) Embedded Binaries -> add Lottie.framework iOS

Tell me if this work for you @AdityaAgg . If it does I'll submit a PR and add a FAQ about iOS animations not throwing errors but also not appearing on device and give a cleaned up version of these steps.

**Comment by AdityaAgg** [comment]
@mini-eggs, wish I could tell you your suggestion worked for me but it doesn't. Tried the instructions above. I know that I am reading the file properly so I think there could be an issue with the library that's not resolved or reported.

**Comment by mattk90** [comment]
To add to g3r4n's answer:
Go to your app project very at the top > Targets > [Your App Name] > Build Phases. Then under Target Dependencies there needs to be `Lottie_iOS (Lottie)` included.
Under Link Binary With Libraries there needs to be `libLottieReactNative.a` & `Lottie.framework`, included but remove the` LibLottie.a`

**Comment by yongching** [comment]
For those who are using cocoapods:

Remember to install these 2 dependencies in your react-native project
`yarn add lottie-react-native@2.2.7 && yarn add lottie-ios`

And add these two lines to your Podfile
`pod 'lottie-ios', :path => '../node_modules/lottie-ios'`
`pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'`

Inside your Xcode project, Product -> Clean, Product -> Build

Note: Do not add anything to embedded libraries and linked libraries.

Voila, there you go! At least it works for me

**Comment by PatrickPD** [comment]
In my case, I had forgotten to rebuild the project after pod install
