### ISSUE TITLE
No ViewManager defined for class LottieAnimationView

### ISSUE THREAD

**Issue by mynane** [airbnb/lottie-react-native#83]
No ViewManager defined for class LottieAnimationView

**Comment by amalChandran** [comment]
I had the same issue. I resolved it like:

- Re run : react-native run-android
- This might create a build failure.
- cd android && ./gradlew clean

 Now run again.. it should wait.

**Comment by lelandrichardson** [comment]
I believe this should now be fixed in `lottie-react-native@1.1.1`. Please try it out and let me know if you still have trouble. Closing this issue for now. Thanks!

**Comment by jkdrangel** [comment]
I did have the same problem using `lottie-react-native@1.1.1` today

**Comment by jcbiznoff** [comment]
I ran into the same issue here and i found a work around below. Just for context i'm using a hybrid app (react + android) with other RN modules and react native v0.42. A doc on this would really help devs like me.

1. include modules under the settings.gradle file and resync.
```
include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../../node_modules/lottie-react-native/lib/android')
```

2. Override the react native host with LottiePackage in the activity where RN is initialized.
```
           @Override
            public ReactNativeHost getReactNativeHost() {
                    reactNativeHost = new ReactNativeHost(getApplication()) {
                      ...
                        @Override
                        protected List<ReactPackage> getPackages() {
                            return Arrays.asList(
                                  ...
                                    new LottiePackage()
                            );
                        }
                    };
                return reactNativeHost;
            }

```

**Comment by ChrnoLynch** [comment]
Don't forget write the import line or will not compile.

`import com.airbnb.android.react.lottie.LottiePackage;`

**Comment by mientjan** [comment]
please reopen, having this issue on android not on ios

**Comment by yujintao529** [comment]
i did have the same problem and 'ottie-react-native' of version is 1.1.1 。what can i do?

**Comment by alexlevy0** [comment]
Same Issue

**Comment by MLescaudron** [comment]
Same problem Here 
RN : 0.48.4
Lottie : 2.2.7

**Comment by adyscorpius** [comment]
True. Same issue, even after react-native link.
