### ISSUE TITLE
Add supported / unsupported After Effects features

### ISSUE THREAD

**Issue by fdnhkj** [airbnb/lottie-react-native#88]
Example in `lottie-ios`
* https://github.com/airbnb/lottie-ios#supported-after-effects-features
* https://github.com/airbnb/lottie-ios#currently-unsupport-after-effects-features

**Comment by lelandrichardson** [comment]
@fdnhkj what lottie supports is a function of the ios and android projects, not this one. As a result, I think those projects are the right "sources of truth" for this information.  I think it's a good idea to add a link to these in the documentation though, and will do that...

**Comment by fdnhkj** [comment]
Great, thank you!
