### ISSUE TITLE
Build Web React API by wrapping bodymovin library

### ISSUE THREAD

**Issue by lelandrichardson** [airbnb/lottie-react-native#9]

**Comment by mannyhenri** [comment]
@lelandrichardson if you need help or if you have this completed let me know. Very interested in using Lottie in my react projects. Might include it in a course at Linkedin, I have several courses upcoming in production around React and React Native I think this fits perfectly....

**Comment by lelandrichardson** [comment]
I will let you know! I haven't started working on this, but I think all of the actual hard work is already done in the bodymovin library, so I don't think it will be too bad

**Comment by Olical** [comment]
It's not much, but here's a very simple wrapper I created, [react-bodymovin](https://github.com/QubitProducts/react-bodymovin). I'm sure more requirements and ideas / features will pour in if a few people start using it. Right now it'll just embed an animation with some options as SVG or HTML. Haven't thought about runtime methods and canvas just yet, but easy enough to do.

**Comment by chenqingspring** [comment]
I moved [ng-lottie](https://github.com/chenqingspring/ng-lottie) to [react-lottie](https://github.com/chenqingspring/react-lottie), hope this may match your requirements. [Demo](https://chenqingspring.github.io/react-lottie/iframe.html)

**Comment by watert** [comment]
@chenqingspring Same react props / methods for web would be better.

**Comment by chenqingspring** [comment]
@watert Thanks for your suggestion. I'll continuous improve it.

**Comment by gpeal** [comment]
Thanks for the work on this guys! I'll close this issue.
