### ISSUE TITLE
Build fails on release (iOS)

### ISSUE THREAD

**Issue by Kowaio** [airbnb/lottie-react-native#91]
Hi guys,

Posting here because I've got a similar problem. I succeeded to make lottie work on my RN project using Lottie 1.0.6 and RN 0.39 on iOS in debug. I removed `libLottie.a` as said on ticket #59 from the linked frameworks and libraries and it's building well on the simulator and animations correctly appear.

However, when using fastlane to generate an .ipa to deploy on Testflight for my team, the build is not working and I've got the following message node_modules/lottie-react-native/lib/ios/LottieReactNative/LRNContainerView.h:19:9: 'Lottie/Lottie.h' file not found
http://cl.kowaio.me/2w0M2027462S

Here is also a screenshot of my embedded and linked frameworks: http://cl.kowaio.me/3O3Z3E392i2S

FYI, I also tried to make an archive not using fastlane, by hand, and I've got exactly the same error as said above. http://cl.kowaio.me/0M3E3L0A2m44

I don't know why it's doing this in release. Did you encounter this while trying to build on your side?

Thanks again guys

**Comment by lelandrichardson** [comment]
@Kowaio I believe this should now be fixed in `lottie-react-native@1.1.1`. Please try it out and let me know if you still have trouble. Closing this issue for now. Thanks!

**Comment by Kowaio** [comment]
Hello @lelandrichardson,

As said on #59, sorry for the duplicate answer but I still wanted to comment this thread. I tested with `lottie-react-native@1.1.1` but I've got the same problem while building for release.

Here's a screenshot: http://cl.ly/0s0U1a211f2j

Thanks

**Comment by Vasiliev90** [comment]
+1

**Comment by lyw0149** [comment]
@Kowaio I am using fastlane too, and I have same problem.

**Comment by Kowaio** [comment]
Hi @lyw0149,
Check #103 answer, using `Parallelize Build` did the trick for me.

**Comment by elizamaria** [comment]
I still get a code signing error even with unchecking parallelize build. This only happens when I want to generate an .ipa file.
