### ISSUE TITLE
How can I create a JSON that works with android

### ISSUE THREAD

**Issue by xhuang3** [airbnb/lottie-react-native#95]
I use bodymovin export an animation from AE, but for some reason this JSON doesn't work with android (I can see some flashing but not the whole animation). But if I replace the JSON with one from the example folder, it works really well. So I wonder what is the difference between the one I made and the one from the example folder? Is there option I need to choose in AE?

Here is the versions I use:
bodymovin 4.6.1
AE 14.1.0.57

Thanks a lot!

[doesnotworkwithandroid.json.zip](https://github.com/airbnb/lottie-react-native/files/867072/doesnotworkwithandroid.json.zip)

**Comment by therealsalih** [comment]
@xhuang3 can you attach your AE file?

**Comment by lelandrichardson** [comment]
cc @gpeal this might be fixed now in the newer lottie android versions. I'll be releasing an update shortly. Hopefully that will fix your problem!

**Comment by sean-johnson** [comment]
Any updates on this? I am having the exact same issue, same specs also

**Comment by lelandrichardson** [comment]
@sean-johnson now that https://github.com/airbnb/lottie-ios/pull/191 is merged, I should be able to publish a release. Will try to do so some time today!

**Comment by lelandrichardson** [comment]
@sean-johnson just published 1.1.1! Please try it out and let me know if it's fixed. I will close this issue for now.
